CREATE TABLE IF NOT EXISTS crewbrief_weight_balance (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  trip_id text NOT NULL,
  document_date text,
  aircraft_registration text,
  aircraft_type text,
  basic_empty_weight text,
  basic_empty_weight_cg text,
  basic_empty_weight_moment text,
  operating_empty_weight text,
  operating_empty_weight_cg text,
  operating_empty_weight_moment text,
  max_ramp_weight text,
  max_takeoff_weight text,
  max_landing_weight text,
  max_zero_fuel_weight text,
  zero_fuel_weight text,
  zero_fuel_weight_cg text,
  zero_fuel_weight_moment text,
  ramp_weight text,
  takeoff_weight text,
  takeoff_weight_cg text,
  takeoff_weight_moment text,
  landing_weight text,
  landing_weight_cg text,
  landing_weight_moment text,
  fuel_unit text,
  fuel_ramp text,
  fuel_trip text,
  fuel_contingency text,
  fuel_alternate text,
  fuel_final_reserve text,
  fuel_taxi text,
  payload text,
  passenger_count text,
  passenger_weight text,
  cargo_weight text,
  baggage_weight text,
  crew_count text,
  crew_weight text,
  stations jsonb,
  raw_extraction jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS cb_wb_document_id_idx ON crewbrief_weight_balance (document_id);
CREATE INDEX IF NOT EXISTS cb_wb_trip_id_idx ON crewbrief_weight_balance (trip_id);
