export interface SecurityAlertPayload {
  cveId: string;
  severity: string;
  cvssScore: number | null;
  description: string;
  affectedDependency: string;
  ecosystem: string;
  publishedAt: string;
  references: string[];
}

export interface PaperclipAlertOptions {
  apiUrl: string;
  apiKey: string;
  companyId: string;
  securityReviewerAgentId: string;
  runId?: string;
}

export class SecurityAlerter {
  private options: PaperclipAlertOptions;

  constructor(options: PaperclipAlertOptions) {
    this.options = options;
  }

  private async request<T>(
    method: string,
    path: string,
    body?: unknown
  ): Promise<T> {
    const url = new URL(path.slice(1), `${this.options.apiUrl}/`);
    const headers: Record<string, string> = {
      Authorization: `Bearer ${this.options.apiKey}`,
      Accept: "application/json",
      "Content-Type": "application/json",
    };

    if (this.options.runId) {
      headers["X-Paperclip-Run-Id"] = this.options.runId;
    }

    const response = await fetch(url, {
      method,
      headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`Paperclip API error: ${response.status} ${response.statusText} - ${text}`);
    }

    const text = await response.text();
    if (!text) return {} as T;
    return JSON.parse(text) as T;
  }

  async createCveAlertIssue(payload: SecurityAlertPayload): Promise<string> {
    const severityEmoji = payload.severity === "CRITICAL" ? "🔴" : payload.severity === "HIGH" ? "🟠" : "🟡";
    const cvssStr = payload.cvssScore !== null ? `**CVSS Score:** ${payload.cvssScore}/10\n` : "";

    const title = `${severityEmoji} CVE Alert: ${payload.cveId} affects ${payload.affectedDependency}`;

    const description = `## CVE Security Alert

**CVE ID:** ${payload.cveId}
**Severity:** ${payload.severity}
${cvssStr}
**Ecosystem:** ${payload.ecosystem}
**Affected Dependency:** ${payload.affectedDependency}
**Published:** ${new Date(payload.publishedAt).toISOString()}

### Description

${payload.description}

### References

${payload.references.map((ref) => `- ${ref}`).join("\n")}

---
*This alert was automatically generated by the CVE Watcher.*`;

    const issue = await this.request<{ id: string; identifier: string }>(
      "POST",
      `/companies/${this.options.companyId}/issues`,
      {
        title,
        description,
        status: "todo",
        priority: payload.severity === "CRITICAL" ? "critical" : payload.severity === "HIGH" ? "high" : "medium",
        assigneeAgentId: this.options.securityReviewerAgentId,
      }
    );

    return issue.identifier;
  }

  async resolveAlert(paperclipIssueId: string, resolution: string): Promise<void> {
    await this.request(
      "PATCH",
      `/issues/${paperclipIssueId}`,
      {
        status: "done",
        comment: `## Resolution\n\n${resolution}\n\n*Auto-resolved by CVE Watcher.*`,
      }
    );
  }
}