area/github:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*

area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - docs/**/*
          - SECURITY.md

area/src:
  - changed-files:
      - any-glob-to-any-file:
          - src/**/*
          - app/**/*
          - packages/**/*

area/tests:
  - changed-files:
      - any-glob-to-any-file:
          - test/**/*
          - tests/**/*
          - __tests__/**/*
