repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: 37d3055fece566105cf8cff7c17b7b2355a01677 # v1.14.2
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=deploy/helm
          - --template-files=README.md.gotmpl
          - --sort-values-order=file
