import type { AdapterConfigSchema } from "@paperclipai/adapter-utils";
import { DEFAULT_EVENT_RECONNECT_MS, DEFAULT_TIMEOUT_SEC } from "../shared/constants.js";

export function getConfigSchema(): AdapterConfigSchema {
  return {
    fields: [
      {
        key: "apiBaseUrl",
        label: "API base URL",
        type: "text",
        required: true,
        hint: "Hermes API server base URL, such as http://127.0.0.1:8642 or a private HTTPS URL.",
      },
      {
        key: "apiKey",
        label: "API key",
        type: "text",
        required: true,
        hint: "Hermes API_SERVER_KEY. Stored in adapter config; avoid sharing exported configs.",
        meta: { secret: true },
      },
      {
        key: "sessionKeyStrategy",
        label: "Session key strategy",
        type: "select",
        default: "issue",
        options: [
          { value: "issue", label: "Issue scoped" },
          { value: "agent", label: "Agent scoped" },
          { value: "run", label: "Run scoped" },
          { value: "none", label: "None" },
        ],
        hint: "Controls X-Hermes-Session-Key. Issue scoped prevents cross-task memory bleed by default.",
      },
      {
        key: "timeoutSec",
        label: "Timeout seconds",
        type: "number",
        default: DEFAULT_TIMEOUT_SEC,
      },
      {
        key: "eventReconnectMs",
        label: "Event reconnect ms",
        type: "number",
        default: DEFAULT_EVENT_RECONNECT_MS,
        hint: "Delay before reconnecting the Hermes SSE events stream after a nonterminal disconnect.",
      },
      {
        key: "paperclipApiUrl",
        label: "Paperclip API URL",
        type: "text",
        hint: "Optional Paperclip API URL reachable by the remote Hermes host. This is not a credential.",
      },
      {
        key: "headers",
        label: "Extra headers",
        type: "textarea",
        hint: "Optional JSON object of extra nonsecret headers. Security-critical headers are generated by the adapter.",
      },
      {
        key: "instructions",
        label: "Instructions",
        type: "textarea",
        hint: "Optional stable Hermes instructions sent separately from the wake input.",
      },
    ],
  };
}
