import { defineConfig, devices } from "@playwright/test";

/**
 * Playwright config for the Viracue acceptance skill.
 *
 * - `anonymous` project: clean, cookieless Chromium. Default for all URL specs.
 * - `authenticated` project: loads a seeded Clerk test user storageState from .auth/qa-user.json
 *   (generated by helpers/login-clerk.ts — Phase 4).
 *
 * The verification worker invokes playwright with --project=<context> --reporter=json and
 * captures the trace bundle produced in the output dir as evidence-of-record.
 */
export default defineConfig({
  testDir: "./tests",
  timeout: 30_000,
  expect: { timeout: 5_000 },
  fullyParallel: false,
  forbidOnly: true,
  retries: 0,
  workers: 1,
  reporter: [["json"], ["list"]],
  use: {
    baseURL: "https://viracue.ai",
    trace: "on",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
    actionTimeout: 10_000,
    navigationTimeout: 20_000,
  },
  projects: [
    {
      name: "anonymous",
      use: { ...devices["Desktop Chrome"], storageState: undefined },
    },
    {
      name: "authenticated",
      use: { ...devices["Desktop Chrome"], storageState: ".auth/qa-user.json" },
    },
  ],
});
