apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "codereview.fullname" . }}
  labels:
    {{- include "codereview.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccountRoleArn | default "" }}
