import { Router } from "express";
import type { Db } from "@ironworksai/db";
import { knowledgeService } from "../services/knowledge.js";
import { logActivity } from "../services/activity-log.js";
import { assertCompanyAccess, getActorInfo } from "./authz.js";
import { lookupPlaybook, reindexPage, reindexAllPlaybooks } from "../services/playbook-rag.js";
import { auditAgentRun } from "../services/playbook-audit.js";

function actorForService(actor: ReturnType<typeof getActorInfo>) {
  return {
    agentId: actor.agentId ?? undefined,
    userId: actor.actorType === "user" ? actor.actorId : undefined,
  };
}

export function knowledgeRoutes(db: Db) {
  const router = Router();
  const svc = knowledgeService(db);

  // List all KB pages for a company
  router.get("/companies/:companyId/knowledge", async (req, res) => {
    const companyId = req.params.companyId as string;
    assertCompanyAccess(req, companyId);
    const search = typeof req.query.q === "string" ? req.query.q : undefined;
    const visibility = typeof req.query.visibility === "string" ? req.query.visibility : undefined;
    const department = typeof req.query.department === "string" ? req.query.department : undefined;
    const agentId = typeof req.query.agentId === "string" ? req.query.agentId : undefined;
    const pages = await svc.list(companyId, { search, visibility, department, agentId });
    res.json(pages);
  });

  // Get a single page by ID
  router.get("/knowledge/:pageId", async (req, res) => {
    const page = await svc.getById(req.params.pageId as string);
    if (!page) { res.status(404).json({ error: "Page not found" }); return; }
    assertCompanyAccess(req, page.companyId);
    res.json(page);
  });

  // Get a page by slug
  router.get("/companies/:companyId/knowledge/slug/:slug", async (req, res) => {
    const companyId = req.params.companyId as string;
    assertCompanyAccess(req, companyId);
    const page = await svc.getBySlug(companyId, req.params.slug as string);
    if (!page) { res.status(404).json({ error: "Page not found" }); return; }
    res.json(page);
  });

  // Create a new page
  router.post("/companies/:companyId/knowledge", async (req, res) => {
    const companyId = req.params.companyId as string;
    assertCompanyAccess(req, companyId);
    const actor = getActorInfo(req);
    const { title, body, visibility, projectId, department, folder } = req.body;
    if (!title || typeof title !== "string" || title.trim().length === 0) {
      res.status(400).json({ error: "Title is required" }); return;
    }
    if (title.trim().length > 200) {
      res.status(400).json({ error: "Title must be 200 characters or less" }); return;
    }
    const page = await svc.create(companyId, { title, body, visibility, projectId, department, folder }, actorForService(actor));
    await logActivity(db, {
      companyId,
      actorType: actor.actorType,
      actorId: actor.actorId,
      action: "knowledge.page_created",
      entityType: "knowledge_page",
      entityId: page.id,
      details: { title: page.title, slug: page.slug },
    });
    res.status(201).json(page);
  });

  // Update a page
  router.patch("/knowledge/:pageId", async (req, res) => {
    const page = await svc.getById(req.params.pageId as string);
    if (!page) { res.status(404).json({ error: "Page not found" }); return; }
    assertCompanyAccess(req, page.companyId);

    // HR document immutability: auto-generated personnel records cannot be modified
    const immutableDocumentTypes = new Set(["hiring-record", "termination-record", "employment_history"]);
    if (page.autoGenerated && page.documentType && immutableDocumentTypes.has(page.documentType)) {
      res.status(403).json({ error: "HR documents are immutable" });
      return;
    }

    const actor = getActorInfo(req);
    const { title, body, visibility, projectId, department, changeSummary } = req.body;
    const updated = await svc.update(page.id, { title, body, visibility, projectId, department, changeSummary }, actorForService(actor));
    await logActivity(db, {
      companyId: page.companyId,
      actorType: actor.actorType,
      actorId: actor.actorId,
      action: "knowledge.page_updated",
      entityType: "knowledge_page",
      entityId: page.id,
      details: { title: updated.title, changeSummary },
    });
    res.json(updated);
  });

  // Delete a page
  router.delete("/knowledge/:pageId", async (req, res) => {
    const page = await svc.getById(req.params.pageId as string);
    if (!page) { res.status(404).json({ error: "Page not found" }); return; }
    assertCompanyAccess(req, page.companyId);
    const actor = getActorInfo(req);
    await svc.remove(page.id);
    await logActivity(db, {
      companyId: page.companyId,
      actorType: actor.actorType,
      actorId: actor.actorId,
      action: "knowledge.page_deleted",
      entityType: "knowledge_page",
      entityId: page.id,
      details: { title: page.title },
    });
    res.json({ ok: true });
  });

  // List revisions for a page
  router.get("/knowledge/:pageId/revisions", async (req, res) => {
    const page = await svc.getById(req.params.pageId as string);
    if (!page) { res.status(404).json({ error: "Page not found" }); return; }
    assertCompanyAccess(req, page.companyId);
    const revisions = await svc.listRevisions(page.id);
    res.json(revisions);
  });

  // Get a specific revision
  router.get("/knowledge/:pageId/revisions/:revisionNumber", async (req, res) => {
    const page = await svc.getById(req.params.pageId as string);
    if (!page) { res.status(404).json({ error: "Page not found" }); return; }
    assertCompanyAccess(req, page.companyId);
    const rev = await svc.getRevision(page.id, parseInt(req.params.revisionNumber as string, 10));
    if (!rev) { res.status(404).json({ error: "Revision not found" }); return; }
    res.json(rev);
  });

  // Revert to a specific revision
  router.post("/knowledge/:pageId/revisions/:revisionNumber/revert", async (req, res) => {
    const page = await svc.getById(req.params.pageId as string);
    if (!page) { res.status(404).json({ error: "Page not found" }); return; }
    assertCompanyAccess(req, page.companyId);
    const actor = getActorInfo(req);
    const revNum = parseInt(req.params.revisionNumber as string, 10);
    const updated = await svc.revertToRevision(page.id, revNum, actorForService(actor));
    await logActivity(db, {
      companyId: page.companyId,
      actorType: actor.actorType,
      actorId: actor.actorId,
      action: "knowledge.page_reverted",
      entityType: "knowledge_page",
      entityId: page.id,
      details: { title: updated.title, revertedToRevision: revNum },
    });
    res.json(updated);
  });

  // Seed default pages
  router.post("/companies/:companyId/knowledge/seed", async (req, res) => {
    const companyId = req.params.companyId as string;
    assertCompanyAccess(req, companyId);
    const result = await svc.seedDefaults(companyId);
    res.json(result);
  });

  // ===== RAG over playbooks =====
  // Agents and UI call this to fetch top-K relevant chunks instead of
  // loading full playbook bodies. See ~/.claude/standards/PLAYBOOK_STANDARD.md.

  // Semantic lookup — returns top-K chunks by cosine similarity
  router.post("/companies/:companyId/knowledge/lookup", async (req, res) => {
    const companyId = req.params.companyId as string;
    assertCompanyAccess(req, companyId);
    const body = req.body as {
      query?: string;
      department?: string;
      ownerRole?: string;
      documentType?: string;
      topK?: number;
    };
    if (!body.query || typeof body.query !== "string" || body.query.trim().length === 0) {
      res.status(400).json({ error: "query is required" });
      return;
    }
    if (body.query.length > 1000) {
      res.status(400).json({ error: "query too long (max 1000 chars)" });
      return;
    }
    const topK = Math.min(Math.max(body.topK ?? 3, 1), 10);
    const results = await lookupPlaybook(db, {
      companyId,
      query: body.query,
      department: body.department,
      ownerRole: body.ownerRole,
      documentType: body.documentType ?? "playbook",
      topK,
    });
    res.json({ results, topK, query: body.query });
  });

  // Reindex one page (admin or after playbook edit)
  router.post("/knowledge/:pageId/reindex", async (req, res) => {
    const pageId = req.params.pageId as string;
    const page = await svc.getById(pageId);
    if (!page) {
      res.status(404).json({ error: "Page not found" });
      return;
    }
    assertCompanyAccess(req, page.companyId);
    const chunks = await reindexPage(db, pageId);
    res.json({ pageId, chunks });
  });

  // Reindex all playbooks for a company (admin only — bulk rebuild)
  router.post("/companies/:companyId/knowledge/reindex-all", async (req, res) => {
    const companyId = req.params.companyId as string;
    assertCompanyAccess(req, companyId);
    const result = await reindexAllPlaybooks(db, companyId);
    res.json(result);
  });

  // Manual playbook audit: judge whether an agent's output followed
  // the relevant playbook discipline. Returns null if audit can't run
  // (no playbook chunks, model unreachable, etc.). See playbook-audit.ts.
  router.post("/companies/:companyId/knowledge/audit", async (req, res) => {
    const companyId = req.params.companyId as string;
    assertCompanyAccess(req, companyId);
    const body = req.body as {
      agentId?: string;
      agentName?: string;
      agentRole?: string;
      agentDepartment?: string;
      taskSummary?: string;
      agentOutput?: string;
    };
    const required = ["agentId", "agentName", "agentRole", "taskSummary", "agentOutput"] as const;
    for (const k of required) {
      if (!body[k] || typeof body[k] !== "string") {
        res.status(400).json({ error: `${k} is required` });
        return;
      }
    }
    const verdict = await auditAgentRun(db, {
      companyId,
      agentId: body.agentId!,
      agentName: body.agentName!,
      agentRole: body.agentRole!,
      agentDepartment: body.agentDepartment ?? null,
      taskSummary: body.taskSummary!,
      agentOutput: body.agentOutput!,
    });
    if (!verdict) {
      res.status(503).json({ error: "audit unavailable", reason: "no chunks or model unreachable" });
      return;
    }
    res.json(verdict);
  });

  return router;
}
