import {
  Atom,
  Bot,
  Brain,
  Bug,
  CircuitBoard,
  Code,
  Cog,
  Cpu,
  Crown,
  Database,
  Eye,
  FileCode,
  Fingerprint,
  Flame,
  Gem,
  GitBranch,
  Globe,
  Hammer,
  Heart,
  Hexagon,
  Lightbulb,
  Lock,
  Mail,
  MessageSquare,
  Microscope,
  Package,
  Pentagon,
  Puzzle,
  Radar,
  Rocket,
  Search,
  Shield,
  Sparkles,
  Star,
  Swords,
  Target,
  Telescope,
  Terminal,
  Wand2,
  Wrench,
  Zap,
  Stethoscope,
  Dna,
  Palette,
  Megaphone,
  Users,
  Headset,
  Briefcase,
  Scale,
  Scroll,
  TrendingUp,
  Calendar,
  Wallet,
  Banknote,
  SwatchBook,
  Wallpaper,
  HatGlasses,
  IdCardLanyard,
  ChartNoAxesCombined,
  Cctv,
  Handshake,
  Presentation,
  Send,
  TabletSmartphone,
  FileCodeCorner,
  Server,
  ShieldUser,
  SignpostBig,
  Library,
  BadgeDollarSign,
  BanknoteArrowDown,
  BanknoteArrowUp,
  CircleDollarSign,
  PiggyBank,
  Receipt,
  ChessKnight,
  ChessKing,
  Goal,
  FlaskConical,
  Sprout,
  LayoutTemplate,
  Sigma,
  Activity,
  HeartPulse,
  Drama,
  Film,
  Binoculars,
  TestTubeDiagonal,
  Handbag,
  Rss,
  DraftingCompass,
  type LucideIcon,
} from "lucide-react";
import { AGENT_ICON_NAMES, type AgentIconName } from "@paperclipai/shared";

export const AGENT_ICONS: Record<AgentIconName, LucideIcon> = {
  bot: Bot,
  cpu: Cpu,
  brain: Brain,
  zap: Zap,
  rocket: Rocket,
  code: Code,
  terminal: Terminal,
  shield: Shield,
  eye: Eye,
  search: Search,
  wrench: Wrench,
  hammer: Hammer,
  lightbulb: Lightbulb,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  flame: Flame,
  bug: Bug,
  cog: Cog,
  database: Database,
  globe: Globe,
  lock: Lock,
  mail: Mail,
  "message-square": MessageSquare,
  "file-code": FileCode,
  "git-branch": GitBranch,
  package: Package,
  puzzle: Puzzle,
  target: Target,
  wand: Wand2,
  atom: Atom,
  "circuit-board": CircuitBoard,
  radar: Radar,
  swords: Swords,
  telescope: Telescope,
  microscope: Microscope,
  crown: Crown,
  gem: Gem,
  hexagon: Hexagon,
  pentagon: Pentagon,
  fingerprint: Fingerprint,
  stethoscope: Stethoscope,
  dna: Dna,
  palette: Palette,
  megaphone: Megaphone,
  users: Users,
  headset: Headset,
  briefcase: Briefcase,
  scale: Scale,
  scroll: Scroll,
  "trending-up": TrendingUp,
  calendar: Calendar,
  wallet: Wallet,
  banknote: Banknote,
  "swatch-book": SwatchBook,
  wallpaper: Wallpaper,
  "hat-glasses": HatGlasses,
  "id-card-lanyard": IdCardLanyard,
  "chart-no-axes-combined": ChartNoAxesCombined,
  cctv: Cctv,
  handshake: Handshake,
  presentation: Presentation,
  send: Send,
  "tablet-smartphone": TabletSmartphone,
  "file-code-corner": FileCodeCorner,
  server: Server,
  "shield-user": ShieldUser,
  "signpost-big": SignpostBig,
  library: Library,
  "badge-dollar-sign": BadgeDollarSign,
  "banknote-arrow-down": BanknoteArrowDown,
  "banknote-arrow-up": BanknoteArrowUp,
  "circle-dollar-sign": CircleDollarSign,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  "chess-knight": ChessKnight,
  "chess-king": ChessKing,
  goal: Goal,
  "flask-conical": FlaskConical,
  sprout: Sprout,
  "layout-template": LayoutTemplate,
  sigma: Sigma,
  activity: Activity,
  "heart-pulse": HeartPulse,
  drama: Drama,
  film: Film,
  binoculars: Binoculars,
  "test-tube-diagonal": TestTubeDiagonal,
  handbag: Handbag,
  rss: Rss,
  "drafting-compass": DraftingCompass,
};

const DEFAULT_ICON: AgentIconName = "bot";

export function getAgentIcon(iconName: string | null | undefined): LucideIcon {
  if (iconName && AGENT_ICON_NAMES.includes(iconName as AgentIconName)) {
    return AGENT_ICONS[iconName as AgentIconName];
  }
  return AGENT_ICONS[DEFAULT_ICON];
}
