import {
  Atom,
  Bot,
  Brain,
  Bug,
  CircuitBoard,
  Code,
  Cog,
  Cpu,
  Crown,
  Database,
  DollarSign,
  Eye,
  FileCode,
  Fingerprint,
  Flame,
  Gem,
  GitBranch,
  Globe,
  Hammer,
  Heart,
  Hexagon,
  Lightbulb,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  Microscope,
  Package,
  Palette,
  PenLine,
  Pentagon,
  Puzzle,
  Radar,
  Rocket,
  Scale,
  Search,
  Server,
  Shield,
  Star,
  Swords,
  Target,
  Telescope,
  Terminal,
  Users,
  Wand2,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { AGENT_ICON_NAMES, type AgentIconName } from "@ironworksai/shared";

export const AGENT_ICONS: Record<AgentIconName, LucideIcon> = {
  bot: Bot,
  cpu: Cpu,
  brain: Brain,
  zap: Zap,
  rocket: Rocket,
  code: Code,
  terminal: Terminal,
  shield: Shield,
  eye: Eye,
  search: Search,
  wrench: Wrench,
  hammer: Hammer,
  lightbulb: Lightbulb,
  sparkles: Wand2,
  star: Star,
  heart: Heart,
  flame: Flame,
  bug: Bug,
  cog: Cog,
  database: Database,
  globe: Globe,
  lock: Lock,
  mail: Mail,
  "message-square": MessageSquare,
  "file-code": FileCode,
  "git-branch": GitBranch,
  package: Package,
  puzzle: Puzzle,
  target: Target,
  wand: Wand2,
  atom: Atom,
  "circuit-board": CircuitBoard,
  radar: Radar,
  swords: Swords,
  telescope: Telescope,
  microscope: Microscope,
  crown: Crown,
  gem: Gem,
  hexagon: Hexagon,
  pentagon: Pentagon,
  fingerprint: Fingerprint,
  megaphone: Megaphone,
  "dollar-sign": DollarSign,
  users: Users,
  scale: Scale,
  "pen-line": PenLine,
  server: Server,
  palette: Palette,
};

const DEFAULT_ICON: AgentIconName = "bot";

export function getAgentIcon(iconName: string | null | undefined): LucideIcon {
  if (iconName && AGENT_ICON_NAMES.includes(iconName as AgentIconName)) {
    return AGENT_ICONS[iconName as AgentIconName];
  }
  return AGENT_ICONS[DEFAULT_ICON];
}
