export interface CronPresetOption {
  id: string;
  label: string;
  expression: string;
}

export const cronPresetOptions: CronPresetOption[] = [
  { id: "every-minute", label: "every minute", expression: "* * * * *" },
  { id: "every-1-minute", label: "every 1 minute", expression: "* * * * *" },
  { id: "every-2-minutes", label: "every 2 minutes", expression: "*/2 * * * *" },
  { id: "every-even-minute", label: "every even minute", expression: "*/2 * * * *" },
  { id: "every-uneven-minute", label: "every uneven minute", expression: "1-59/2 * * * *" },
  { id: "every-3-minutes", label: "every 3 minutes", expression: "*/3 * * * *" },
  { id: "every-4-minutes", label: "every 4 minutes", expression: "*/4 * * * *" },
  { id: "every-5-minutes", label: "every 5 minutes", expression: "*/5 * * * *" },
  { id: "every-five-minutes", label: "every five minutes", expression: "*/5 * * * *" },
  { id: "every-6-minutes", label: "every 6 minutes", expression: "*/6 * * * *" },
  { id: "every-10-minutes", label: "every 10 minutes", expression: "*/10 * * * *" },
  { id: "every-15-minutes", label: "every 15 minutes", expression: "*/15 * * * *" },
  { id: "every-fifteen-minutes", label: "every fifteen minutes", expression: "*/15 * * * *" },
  { id: "every-ten-minutes", label: "every ten minutes", expression: "*/10 * * * *" },
  { id: "every-quarter-hour", label: "every quarter hour", expression: "*/15 * * * *" },
  { id: "every-20-minutes", label: "every 20 minutes", expression: "*/20 * * * *" },
  { id: "every-30-minutes", label: "every 30 minutes", expression: "*/30 * * * *" },
  { id: "every-hour-at-30", label: "every hour at 30 minutes", expression: "30 * * * *" },
  { id: "every-half-hour", label: "every half hour", expression: "*/30 * * * *" },
  { id: "every-60-minutes", label: "every 60 minutes", expression: "0 * * * *" },
  { id: "every-hour", label: "every hour", expression: "0 * * * *" },
  { id: "every-1-hour", label: "every 1 hour", expression: "0 * * * *" },
  { id: "every-2-hours", label: "every 2 hours", expression: "0 */2 * * *" },
  { id: "every-two-hours", label: "every two hours", expression: "0 */2 * * *" },
  { id: "every-even-hour", label: "every even hour", expression: "0 */2 * * *" },
  { id: "every-other-hour", label: "every other hour", expression: "0 */2 * * *" },
  { id: "every-3-hours", label: "every 3 hours", expression: "0 */3 * * *" },
  { id: "every-three-hours", label: "every three hours", expression: "0 */3 * * *" },
  { id: "every-4-hours", label: "every 4 hours", expression: "0 */4 * * *" },
  { id: "every-6-hours", label: "every 6 hours", expression: "0 */6 * * *" },
  { id: "every-six-hours", label: "every six hours", expression: "0 */6 * * *" },
  { id: "every-8-hours", label: "every 8 hours", expression: "0 */8 * * *" },
  { id: "every-12-hours", label: "every 12 hours", expression: "0 */12 * * *" },
  { id: "hours-range", label: "hours range", expression: "0 9-17 * * *" },
  { id: "between-certain-hours", label: "between certain hours", expression: "*/15 9-17 * * *" },

  { id: "every-day", label: "every day", expression: "0 0 * * *" },
  { id: "daily", label: "daily", expression: "0 0 * * *" },
  { id: "once-a-day", label: "once a day", expression: "0 0 * * *" },
  { id: "every-night", label: "every night", expression: "0 22 * * *" },
  { id: "every-day-1am", label: "every day at 1am", expression: "0 1 * * *" },
  { id: "every-day-2am", label: "every day at 2am", expression: "0 2 * * *" },
  { id: "every-day-8am", label: "every day 8am", expression: "0 8 * * *" },
  { id: "every-morning", label: "every morning", expression: "0 8 * * *" },
  { id: "every-midnight", label: "every midnight", expression: "0 0 * * *" },
  { id: "every-day-midnight", label: "every day at midnight", expression: "0 0 * * *" },
  { id: "every-night-midnight", label: "every night at midnight", expression: "0 0 * * *" },
  { id: "every-sunday", label: "every sunday", expression: "0 0 * * 0" },
  { id: "every-monday", label: "every monday", expression: "0 0 * * 1" },
  { id: "every-tuesday", label: "every tuesday", expression: "0 0 * * 2" },
  { id: "every-wednesday", label: "every wednesday", expression: "0 0 * * 3" },
  { id: "every-thursday", label: "every thursday", expression: "0 0 * * 4" },
  { id: "every-friday", label: "every friday", expression: "0 0 * * 5" },
  { id: "every-friday-midnight", label: "every friday at midnight", expression: "0 0 * * 5" },
  { id: "every-saturday", label: "every saturday", expression: "0 0 * * 6" },
  { id: "every-weekday", label: "every weekday", expression: "0 9 * * 1-5" },
  { id: "weekdays-only", label: "weekdays only", expression: "0 9 * * 1-5" },
  { id: "monday-to-friday", label: "monday to friday", expression: "0 9 * * 1-5" },
  { id: "every-weekend", label: "every weekend", expression: "0 9 * * 0,6" },
  { id: "weekends-only", label: "weekends only", expression: "0 9 * * 0,6" },
  { id: "every-7-days", label: "every 7 days", expression: "0 0 */7 * *" },
  { id: "every-week", label: "every week", expression: "0 0 * * 0" },
  { id: "weekly", label: "weekly", expression: "0 0 * * 0" },
  { id: "once-a-week", label: "once a week", expression: "0 0 * * 0" },
  { id: "every-month", label: "every month", expression: "0 0 1 * *" },
  { id: "monthly", label: "monthly", expression: "0 0 1 * *" },
  { id: "once-a-month", label: "once a month", expression: "0 0 1 * *" },
  { id: "every-other-month", label: "every other month", expression: "0 0 1 */2 *" },
  { id: "every-quarter", label: "every quarter", expression: "0 0 1 */3 *" },
  { id: "every-6-months", label: "every 6 months", expression: "0 0 1 */6 *" },
  { id: "every-year", label: "every year", expression: "0 0 1 1 *" },
];

