/**
 * @paperclipai/pricing — vendored model pricing catalog + lookup service.
 *
 * The catalog is generated by `src/refresh.ts` (run via `pnpm --filter @paperclipai/pricing refresh`)
 * by merging models.dev and LiteLLM and is committed at `data/catalog.json` for reproducibility.
 *
 * Runtime callers (heartbeat fallback path) use `priceUsd()` here. Adapter `costUsd`
 * wins when present; the pricing service is the safety net.
 */

import catalogJson from '../data/catalog.json' with { type: 'json' };
import { lookupKey } from './normalize.js';

export type PricingSource = 'models.dev' | 'litellm' | 'merged';

export interface CatalogEntry {
  /** USD per million input tokens at the base tier. */
  input_per_mtok: number;
  /** USD per million cache-read tokens. Falls back to `input_per_mtok` if upstream omits it. */
  cached_input_per_mtok: number;
  /** USD per million cache-create tokens (Anthropic surfaces this separately). */
  cache_write_per_mtok?: number;
  /** USD per million output tokens at the base tier. */
  output_per_mtok: number;
  /** USD per million reasoning tokens (Claude extended thinking). */
  reasoning_per_mtok?: number;
  /** Token boundary above which over-threshold pricing applies (e.g. 200000 for Gemini long-context). */
  tier_threshold_tokens?: number;
  /** USD per million input tokens once `tier_threshold_tokens` is exceeded. */
  over_threshold_input_per_mtok?: number;
  /** USD per million output tokens once `tier_threshold_tokens` is exceeded. */
  over_threshold_output_per_mtok?: number;
  /** Region-prefixed aliases that should resolve to this base entry (e.g. `us.anthropic.claude-opus-4-5`). */
  region_aliases?: string[];
  /** Which upstream produced this row. `merged` means both sources agreed/overlapped. */
  source: PricingSource;
}

export type Catalog = Record<string, CatalogEntry>;

/**
 * The vendored, committed pricing snapshot. Lane C consumers should import this
 * (rather than calling out to the network at runtime).
 */
export const catalog: Catalog = catalogJson as Catalog;

// ---------------------------------------------------------------------------
// Lookup API
// ---------------------------------------------------------------------------

/**
 * BillingType values that are USD-denominated and therefore safe to price via
 * the catalog. Anything else (`subscription_*`, `fixed`, etc.) returns null so
 * the caller can write `cost_cents = NULL` rather than a misleading number.
 *
 * Mirrors `BILLING_TYPES` in `@paperclipai/shared/constants` but kept as a
 * local literal to avoid a workspace dependency just for this constant.
 */
const BILLING_TYPE_ALLOWLIST: ReadonlySet<string> = new Set([
  'metered_api',
  'credits',
  'unknown',
]);

export interface PriceUsdInput {
  provider: string | null;
  model: string | null;
  inputTokens: number;
  outputTokens: number;
  /** Cache-read tokens (Anthropic, OpenAI cached input). Priced at the cached rate. */
  cachedInputTokens?: number;
  /**
   * Reasoning/thinking tokens (Claude extended thinking). Priced at
   * `reasoning_per_mtok` only when the catalog entry has that field; otherwise
   * the caller is expected to have already merged reasoning into output tokens.
   * See the opencode-local note in `doc/pricing.md`.
   */
  reasoningTokens?: number;
  /**
   * Adapter-reported billing type. When set and not in the allowlist
   * (`metered_api`, `credits`, `unknown`), the lookup is skipped entirely and
   * we return null — pricing the catalog rate for a `subscription_included`
   * run would be misleading.
   */
  billingType?: string | null;
}

/**
 * Compute the USD cost of a heartbeat usage report from the vendored catalog.
 *
 * Returns `number | null`:
 *   - `0` when all token counts are zero (genuine no-op run).
 *   - a positive number when the catalog has an entry for the model.
 *   - `null` when the lookup fails or `billingType` is outside the allowlist.
 *
 * The caller (heartbeat) is responsible for converting USD → cents.
 *
 * Tiering: when `entry.tier_threshold_tokens` is set and `inputTokens` exceeds
 * it, the *excess* portion is priced at `over_threshold_input_per_mtok` and the
 * portion at-or-below the threshold stays on the base rate. Output tokens
 * follow the same rule against the input tier threshold (LiteLLM publishes a
 * single threshold per model, not per axis).
 *
 * Cache-write tokens are not used in this PR — no adapter currently reports
 * cache-write separately. The catalog field stays populated for a follow-up.
 */
export function priceUsd(input: PriceUsdInput): number | null {
  const { provider, model, inputTokens, outputTokens } = input;
  const cachedInputTokens = input.cachedInputTokens ?? 0;
  const reasoningTokens = input.reasoningTokens ?? 0;
  const billingType = input.billingType;

  // billingType allowlist — if the adapter explicitly tagged a non-USD billing
  // mode, do not pretend we know the cost. `undefined`/`null` is treated as
  // unknown (allowed) so legacy adapters that don't tag anything still flow.
  if (billingType != null && billingType !== '' && !BILLING_TYPE_ALLOWLIST.has(billingType)) {
    return null;
  }

  // No catalog entry without a key.
  const key = lookupKey(provider, model);
  if (!key) return null;

  const entry = catalog[key];
  if (!entry) return null;

  // Genuine zero-usage run — preserve the distinction between "free" and "unpriced".
  if (
    inputTokens === 0 &&
    outputTokens === 0 &&
    cachedInputTokens === 0 &&
    reasoningTokens === 0
  ) {
    return 0;
  }

  // ---- Input ----
  // Cache-reads are billed at the cached rate; the remainder of input tokens at
  // the input rate. Tiering is applied only to non-cached input tokens.
  const billedInputTokens = Math.max(0, inputTokens - cachedInputTokens);
  let inputCost = 0;
  if (
    entry.tier_threshold_tokens != null &&
    typeof entry.over_threshold_input_per_mtok === 'number' &&
    billedInputTokens > entry.tier_threshold_tokens
  ) {
    const baseTokens = entry.tier_threshold_tokens;
    const overTokens = billedInputTokens - baseTokens;
    inputCost =
      perMtok(baseTokens, entry.input_per_mtok) +
      perMtok(overTokens, entry.over_threshold_input_per_mtok);
  } else {
    inputCost = perMtok(billedInputTokens, entry.input_per_mtok);
  }

  // Cache-read tokens never tier — they're billed at the (typically deeply
  // discounted) cached rate regardless of context length.
  const cachedCost = perMtok(cachedInputTokens, entry.cached_input_per_mtok);

  // ---- Output ----
  // Output tier uses the same threshold as input (LiteLLM publishes one
  // threshold per model). Tier off `inputTokens` since the long-context
  // surcharge applies when the *prompt* is long, not when the *response* is.
  let outputCost = 0;
  if (
    entry.tier_threshold_tokens != null &&
    typeof entry.over_threshold_output_per_mtok === 'number' &&
    inputTokens > entry.tier_threshold_tokens
  ) {
    outputCost = perMtok(outputTokens, entry.over_threshold_output_per_mtok);
  } else {
    outputCost = perMtok(outputTokens, entry.output_per_mtok);
  }

  // ---- Reasoning ----
  // Only price reasoning tokens separately when the catalog has a dedicated
  // rate AND the caller actually reports reasoning tokens. Otherwise the
  // caller is assumed to have folded reasoning into outputTokens already
  // (opencode-local does this) and we must not double-charge.
  let reasoningCost = 0;
  if (
    typeof entry.reasoning_per_mtok === 'number' &&
    reasoningTokens > 0
  ) {
    reasoningCost = perMtok(reasoningTokens, entry.reasoning_per_mtok);
  }

  return inputCost + cachedCost + outputCost + reasoningCost;
}

function perMtok(tokens: number, perMillion: number): number {
  if (!Number.isFinite(tokens) || tokens <= 0) return 0;
  if (!Number.isFinite(perMillion) || perMillion <= 0) return 0;
  return (tokens / 1_000_000) * perMillion;
}
