/**
 * @paperclipai/pricing — vendored model pricing catalog.
 *
 * Lane B exposes only types + the snapshot. Lane C will fill in `priceUsd()` here.
 *
 * The catalog is generated by `src/refresh.ts` (run via `pnpm --filter @paperclipai/pricing refresh`)
 * by merging models.dev and LiteLLM and is committed at `data/catalog.json` for reproducibility.
 */

import catalogJson from '../data/catalog.json' with { type: 'json' };

export type PricingSource = 'models.dev' | 'litellm' | 'merged';

export interface CatalogEntry {
  /** USD per million input tokens at the base tier. */
  input_per_mtok: number;
  /** USD per million cache-read tokens. Falls back to `input_per_mtok` if upstream omits it. */
  cached_input_per_mtok: number;
  /** USD per million cache-create tokens (Anthropic surfaces this separately). */
  cache_write_per_mtok?: number;
  /** USD per million output tokens at the base tier. */
  output_per_mtok: number;
  /** USD per million reasoning tokens (Claude extended thinking). */
  reasoning_per_mtok?: number;
  /** Token boundary above which over-threshold pricing applies (e.g. 200000 for Gemini long-context). */
  tier_threshold_tokens?: number;
  /** USD per million input tokens once `tier_threshold_tokens` is exceeded. */
  over_threshold_input_per_mtok?: number;
  /** USD per million output tokens once `tier_threshold_tokens` is exceeded. */
  over_threshold_output_per_mtok?: number;
  /** Region-prefixed aliases that should resolve to this base entry (e.g. `us.anthropic.claude-opus-4-5`). */
  region_aliases?: string[];
  /** Which upstream produced this row. `merged` means both sources agreed/overlapped. */
  source: PricingSource;
}

export type Catalog = Record<string, CatalogEntry>;

/**
 * The vendored, committed pricing snapshot. Lane C consumers should import this
 * (rather than calling out to the network at runtime).
 */
export const catalog: Catalog = catalogJson as Catalog;
