/** Built-in UI copy only. Both the app slug and exact upstream text must match. */
export const APP_DEFINITION_COPY: Record<string, Record<string, string>> = {
  "cognee": {
    "Add/process knowledge and manage authorized datasets. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.cogneeKey",
    "Build and recall shared graph memory from documents and conversations.": "oct6Metadata.copy068",
    "Cognee Cloud and a local runtime": "oct6Metadata.copy069",
    "Use your Cognee Cloud tenant API URL and key. Paperclip's runtime host needs uv installed to run the official Cognee MCP client. Public deployments require a trusted MCP runtime host.": "oct6Metadata.copy070",
    "Open Cognee API keys": "oct6Metadata.copy071",
    "Connect your Cloud tenant through the official Cognee MCP client.": "oct6Metadata.copy072",
    "Copy the API Base URL and create an API key on Cognee's API Keys page. Use a Cloud workspace with an active subscription. Paperclip uses its bundled Cloud client; no extra runtime installation is required.": "oct6Metadata.copy073",
    "Connect Cognee Cloud": "oct6Metadata.copy074",
    "API Base URL": "oct6Metadata.copy075",
    "Copy API Base URL from Cognee's API Keys page.": "oct6Metadata.copy077",
    "Cognee API key": "oct6Metadata.copy078",
    "Paste your Cognee API key": "oct6Metadata.copy079"
  },
  "browser-use-cloud": {
    "Create/stop browser sessions and run browser tasks under the API key. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.browserKey",
    "Delegate browser tasks and watch them live in Paperclip.": "oct5Metadata.browserDescription",
    "Use credentials from your provider account.": "oct5Metadata.providerCredentials",
    "Create an API key in [Browser Use settings](https://cloud.browser-use.com/settings) and paste it below. Your agents can browse websites while you watch and interact from the task's Browser tab.": "oct5Metadata.browserGuidance",
    "API key": "localizationApps.metadata7"
  },
  "github-code-review-bot": {
    "Have an agent review pull requests and respond to GitHub mentions.": "oct5Apps.copy060",
    "Chat with an agent": "communityPhoton.metadataMethod",
    "Let people in GitHub start and continue work with one Paperclip agent.": "oct5Metadata.githubAgentChat",
    "GitHub App ID": "chatUi.chatEndpointSetup.githubAppID",
    "Private key (PEM)": "chatUi.chatEndpointSetup.privateKeyPEM",
    "Generate the webhook secret in Paperclip, then create one private GitHub App with active SSL-verified webhooks, Issues and Pull requests read/write permission, and the selectable issue_comment and pull_request_review_comment events. GitHub sends installation and installation_repositories automatically. Install the App only on repositories where people may mention the agent.": "oct5Metadata.githubBotGuidance",
    "GitHub Code Review Bot": "oct5Apps.copy059"
  },
  "neon": {
    "A Neon account. The hosted server grants broad project and database management, so use a development project and review write actions before connecting production data.": "oct5MetadataAddendum.neonAccountWarning",
    "Neon recommends its hosted server for development and testing. Review write and destructive actions before execution.": "oct5MetadataAddendum.neonDevelopmentWarning",
    "Optional. Restrict this connection to one project. Copy the project ID from Neon Console → Project settings → General.": "oct5MetadataAddendum.neonProjectHelp",
    "Enable this to limit SQL to SELECT queries and schema inspection.": "oct5MetadataAddendum.neonReadOnlyHelp",
    "Project, branch, compute, snapshot, SQL and schema changes within the key’s reach. A project-scoped key limits access to one project with Editor rights; personal and organization keys reach every project they can access. Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.neonKey",
    "Manage Postgres projects and branches, run SQL, and inspect schemas in Neon.": "oct5Metadata.neonDescription",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Neon in the browser. Open Advanced to pin one project or enable read-only mode. Write tools start enabled and remain governed by Paperclip's action policies.": "oct5Metadata.neonOAuthGuidance",
    "Sign in with Neon": "oct5Metadata.neonSignIn",
    "Pin to project ID": "localizationApps.metadata247",
    "Optional Neon project ID": "oct5Metadata.neonProjectPlaceholder",
    "Read-only mode": "localizationApps.metadata250",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Use a customer-created Neon API key. Prefer a project-scoped key for one development project; personal and organization keys reach every project they can access. Write tools start enabled and remain governed by Paperclip's action policies.": "oct5Metadata.neonApiGuidance",
    "Use an API key": "localizationApps.metadata24",
    "Neon API key": "oct5Metadata.neonApiKey",
    "napi_... or neon_project_key_...": "oct6Metadata.copy292"
  },
  "fireflies": {
    "Use an API key for an account with write access to the meetings your agents need to share, rename, move or turn into soundbites. Paperclip cannot increase the key’s permissions.": "oct5MetadataAddendum.firefliesKey",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Use an API key": "localizationApps.metadata24",
    "Search meeting transcripts, read summaries and action items, and connect meeting-ready routines.": "oct6Metadata.copy125",
    "Sign in to Fireflies to use meeting transcripts, summaries, and action items. Configure optional summary-ready webhooks separately in a routine's Triggers tab.": "oct6Metadata.copy126",
    "Sign in with Fireflies": "oct6Metadata.copy127",
    "A Fireflies account with access to the meetings you want to use. API keys are available in Settings → Developer Settings.": "oct6Metadata.copy128",
    "Use your Fireflies API key instead of browser sign-in.": "oct6Metadata.copy129",
    "Open Fireflies Settings → Developer Settings, copy your API key, and paste it below. This key accesses your meeting data; routine webhooks use a separate signing secret.": "oct6Metadata.copy130",
    "Fireflies API key": "oct6Metadata.copy131",
    "Paste your Fireflies API key": "oct6Metadata.copy132"
  },
  "honcho": {
    "Create peers/sessions and save memory under the API key project. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.honchoKey",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Use an API key": "localizationApps.metadata24",
    "Remember conversations and retrieve context about peers.": "oct6Metadata.copy234",
    "Open the Honcho dashboard, create an API key for the account agents should use, and paste it below.": "oct6Metadata.copy235",
    "Honcho API key": "oct6Metadata.copy236",
    "Paste your Honcho API key": "oct6Metadata.copy237",
    "An API key from the Honcho dashboard. Memory is stored in your Honcho account; select workspace and peer identifiers when calling tools.": "oct6Metadata.copy238",
    "Honcho workspace": "oct6Metadata.copy239",
    "Workspace ID": "workspaces.fields.id"
  },
  "youcom": {
    "None: search, contents and research tools (usage may be billed). A read-only key is sufficient.": "oct5MetadataAddendum.youKey",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Use an API key": "localizationApps.metadata24",
    "Connect You.com's provider-hosted MCP server.": "oct6Metadata.copy432",
    "Connect You.com in the browser. A You.com account for browser sign-in, or a You.com API key from you.com/platform for higher rate limits; a keyless free profile is also available.": "oct6Metadata.copy433",
    "Sign in with You.com": "oct6Metadata.copy434",
    "A You.com account for browser sign-in, or a You.com API key from you.com/platform for higher rate limits; a keyless free profile is also available.": "oct6Metadata.copy435",
    "Use a customer-created You.com key. A You.com account for browser sign-in, or a You.com API key from you.com/platform for higher rate limits; a keyless free profile is also available.": "oct6Metadata.copy436",
    "You.com API key": "oct6Metadata.copy437",
    "Paste your You.com API key": "oct6Metadata.copy438",
    "Connect without an account for limited, rate-capped web search.": "oct6Metadata.copy439",
    "Use the keyless free profile. You.com limits the free profile to a reduced read-only tool set.": "oct6Metadata.copy440",
    "Use the free profile": "oct6Metadata.copy441",
    "The free profile is keyless and exposes a reduced read-only tool set with You.com rate limits.": "oct6Metadata.copy442"
  },
  "imessage-photon": {
    "Message a Paperclip agent from Apple Messages using Photon Cloud. Pro supports DMs; dedicated lines also support groups.": "communityPhoton.metadataDescription",
    "Chat with an agent": "communityPhoton.metadataMethod",
    "Let people in iMessage Photon start and continue work with one Paperclip agent.": "communityPhoton.metadataWhenToUse",
    "Project secret": "communityPhoton.projectSecret",
    "Photon project secret": "communityPhoton.metadataSecretPlaceholder",
    "Connect a Photon Cloud project. Pro shared lines support DMs after sender enrollment in Photon and identity linking in Paperclip. Dedicated lines also support individually enabled groups.": "communityPhoton.metadataGuidance"
  },
  "agentmail": {
    "Give agents email inboxes and handle each conversation as a task.": "sep12Metadata.agentmailDescription",
    "Email with an agent": "sep12Metadata.agentmailMethod",
    "Assign an inbox to an agent and manage email conversations in tasks.": "sep12Metadata.agentmailWhenToUse",
    "AgentMail API key": "sep12Metadata.agentmailApiKey",
    "Connect an AgentMail API key, then create or select an inbox for your agent. WebSocket receiving works without a public URL.": "sep12Metadata.agentmailGuidance"
  },
  "airtable": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Airtable's provider-hosted MCP server.": "localizationApps.metadata0",
    "Sign in with Airtable": "localizationApps.metadata3",
    "Connect Airtable in the browser. An Airtable account; enterprise administrators may need to allowlist the client.": "oct6Metadata.copy004",
    "An Airtable account; enterprise administrators may need to allowlist the client.": "oct6Metadata.copy005"
  },
  "anthropic": {
    "Use Anthropic APIs with a restricted key.": "localizationApps.metadata4",
    "API key": "localizationApps.metadata7",
    "Claude subscription": "sep13AiMetadata.claudeSubscription",
    "Claude API key": "sep13AiMetadata.claudeApiKey",
    "Authenticate an agent with this account.": "sep13AiMetadata.whenToUse",
    "Use your personal account or an explicitly shared company account.": "sep13AiMetadata.guidance",
    "Enter API key": "sep13AiMetadata.apiKeyPlaceholder"
  },
  "openai": {
    "Connect OpenAI accounts for your agents.": "sep13AiMetadata.openaiDescription",
    "OpenAI subscription": "sep13AiMetadata.openaiSubscription",
    "OpenAI API key": "sep13AiMetadata.openaiApiKey",
    "Authenticate an agent with this account.": "sep13AiMetadata.whenToUse",
    "Use your personal account or an explicitly shared company account.": "sep13AiMetadata.guidance",
    "API key": "localizationApps.metadata7",
    "Enter API key": "sep13AiMetadata.apiKeyPlaceholder"
  },
  "openrouter": {
    "Connect OpenRouter accounts for your agents.": "sep13AiMetadata.openrouterDescription",
    "OpenRouter API key": "sep13AiMetadata.openrouterApiKey",
    "Authenticate an agent with this account.": "sep13AiMetadata.whenToUse",
    "Use your personal account or an explicitly shared company account.": "sep13AiMetadata.guidance",
    "API key": "localizationApps.metadata7",
    "Enter API key": "sep13AiMetadata.apiKeyPlaceholder"
  },
  "xai": {
    "Connect Grok accounts for your agents.": "sep13AiMetadata.grokDescription",
    "Grok subscription": "sep13AiMetadata.grokSubscription",
    "Grok API key": "sep13AiMetadata.grokApiKey",
    "Authenticate an agent with this account.": "sep13AiMetadata.whenToUse",
    "Use your personal account or an explicitly shared company account.": "sep13AiMetadata.guidance",
    "API key": "localizationApps.metadata7",
    "Enter API key": "sep13AiMetadata.apiKeyPlaceholder"
  },
  "api-key-generic": {
    "Actions depend on the operator-supplied API and key; grant read/write on the required resources at the provider. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.genericKey",
    "Use credentials from your provider account.": "oct5Metadata.providerCredentials",
    "API key": "localizationApps.metadata7",
    "Connect an API using a key from your provider.": "localizationApps.metadata9",
    "Paste the API key": "localizationApps.metadata11",
    "API key app": "oct6Metadata.copy008",
    "Create a restricted API key and paste it here.": "oct6Metadata.copy009"
  },
  "asana": {
    "Connect your Asana account with Paperclip's app.": "oct5Metadata.asanaAccount",
    "Sign in to Asana with Paperclip. Asana gives this connection access to the workspaces available to your account.": "oct5Metadata.asanaGuidance",
    "Sign in with Asana": "oct5Metadata.asanaSignIn",
    "Create an MCP app in Asana, then add the callback URL below under OAuth. Under Manage distribution, select your workspace and save. API apps do not work with Asana MCP.": "oct5Metadata.asanaOwnApp",
    "Connect Asana's provider-hosted MCP server.": "localizationApps.metadata12",
    "Use your own OAuth app": "localizationApps.metadata15",
    "Register an OAuth app with Asana, then enter its client ID and secret.": "oct6Metadata.copy017"
  },
  "box": {
    "Use your own OAuth app": "localizationApps.metadata15",
    "Connect Box's provider-hosted MCP server.": "localizationApps.metadata27",
    "Register an OAuth app with Box, then enter its client ID and secret.": "oct6Metadata.copy033",
    "Connect Box in the browser. A Box administrator creates the OAuth integration and enables AI access.": "oct6Metadata.copy034",
    "A Box administrator creates the OAuth integration and enables AI access.": "oct6Metadata.copy035"
  },
  "xero": {
    "Use your own OAuth app": "localizationApps.metadata15",
    "Connect Xero's provider-hosted MCP server.": "localizationApps.metadata347",
    "Register an OAuth app with Xero, then enter its client ID and secret.": "oct6Metadata.copy428",
    "Connect Xero in the browser. Create a Xero OAuth app and confirm the applicable AI and data-use terms before connecting.": "oct6Metadata.copy429",
    "Create a Xero OAuth app and confirm the applicable AI and data-use terms before connecting.": "oct6Metadata.copy430"
  },
  "beehiiv": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect beehiiv's provider-hosted MCP server.": "localizationApps.metadata16",
    "Sign in with beehiiv": "localizationApps.metadata18",
    "Connect beehiiv in the browser. A beehiiv account; the subscription plan controls available write capabilities.": "oct6Metadata.copy026",
    "A beehiiv account; the subscription plan controls available write capabilities.": "oct6Metadata.copy027"
  },
  "bitly": {
    "Create/manage links in authorized groups. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.bitlyKey",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Connect Bitly's provider-hosted MCP server.": "localizationApps.metadata19",
    "Sign in with Bitly": "localizationApps.metadata21",
    "Use an API key": "localizationApps.metadata24",
    "Bitly API key": "localizationApps.metadata25",
    "Paste your Bitly API token": "localizationApps.metadata26",
    "Connect Bitly in the browser. A Bitly account with either browser authorization or an API token.": "oct6Metadata.copy029",
    "A Bitly account with either browser authorization or an API token.": "oct6Metadata.copy030",
    "Use a customer-created Bitly key. A Bitly account with either browser authorization or an API token.": "oct6Metadata.copy031"
  },
  "cloudflare": {
    "Cloudflare API actions selected at provider consent or on the API token. Identity scopes alone do not grant account writes. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.cloudflareKey",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Use an API key": "localizationApps.metadata24",
    "Connect Cloudflare's provider-hosted MCP server.": "localizationApps.metadata42",
    "Sign in with Cloudflare": "localizationApps.metadata44",
    "Cloudflare API key": "localizationApps.metadata46",
    "Paste your Cloudflare API token": "localizationApps.metadata47",
    "Connect Cloudflare in the browser. A Cloudflare account with access to the resources being connected.": "oct6Metadata.copy056",
    "A Cloudflare account with access to the resources being connected.": "oct6Metadata.copy057",
    "Use a customer-created Cloudflare key. A Cloudflare account with access to the resources being connected.": "oct6Metadata.copy058"
  },
  "coda": {
    "Modify documents/tables permitted by the account. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.codaKey",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Use an API key": "localizationApps.metadata24",
    "Connect Coda's provider-hosted MCP server.": "localizationApps.metadata51",
    "Sign in with Coda": "localizationApps.metadata53",
    "Coda API key": "localizationApps.metadata55",
    "Paste your Coda API token": "localizationApps.metadata56",
    "Connect Coda in the browser. A Coda account; the hosted MCP service is currently beta.": "oct6Metadata.copy063",
    "A Coda account; the hosted MCP service is currently beta.": "oct6Metadata.copy064",
    "This provider's hosted MCP server is currently beta or preview.": "oct6Metadata.copy065",
    "Use a customer-created Coda key. A Coda account; the hosted MCP service is currently beta.": "oct6Metadata.copy066"
  },
  "kernel": {
    "Launch/manage browsers, profiles, apps and browser automation. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.kernelKey",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Use an API key": "localizationApps.metadata24",
    "Connect Kernel's provider-hosted MCP server.": "localizationApps.metadata183",
    "Sign in with Kernel": "localizationApps.metadata185",
    "Kernel API key": "localizationApps.metadata187",
    "Paste your Kernel API key": "localizationApps.metadata188",
    "Connect Kernel in the browser. A Kernel account with either browser authorization or an API key.": "oct6Metadata.copy249",
    "A Kernel account with either browser authorization or an API key.": "oct6Metadata.copy250",
    "Use a customer-created Kernel key. A Kernel account with either browser authorization or an API key.": "oct6Metadata.copy251"
  },
  "mem0": {
    "Add/update/delete memories under the API key account. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.mem0Key",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Use an API key": "localizationApps.metadata24",
    "Connect Mem0's provider-hosted MCP server.": "localizationApps.metadata200",
    "Mem0 API key": "localizationApps.metadata202",
    "Remember preferences, conversations, events, and agent state.": "oct6Metadata.copy267",
    "Open the Mem0 dashboard, create an API key for the account agents should use, and paste it below.": "oct6Metadata.copy268",
    "Paste your Mem0 API key": "oct6Metadata.copy269",
    "A Mem0 API key; the live server currently requires the slash-normalized endpoint.": "oct6Metadata.copy270"
  },
  "oreilly": {
    "None: content discovery and retrieval. A read-only key is sufficient.": "oct5MetadataAddendum.oreillyKey",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Use an API key": "localizationApps.metadata24",
    "Connect O'Reilly's provider-hosted MCP server.": "localizationApps.metadata221",
    "Sign in with O'Reilly": "localizationApps.metadata223",
    "O'Reilly API key": "localizationApps.metadata225",
    "Paste your O'Reilly API token": "localizationApps.metadata226",
    "Connect O'Reilly in the browser. An O'Reilly Learning subscription with MCP or API access.": "oct6Metadata.copy305",
    "An O'Reilly Learning subscription with MCP or API access.": "oct6Metadata.copy306",
    "Use a customer-created O'Reilly key. An O'Reilly Learning subscription with MCP or API access.": "oct6Metadata.copy307"
  },
  "razorpay": {
    "Provider-authorized payment/account tools; financial policy gates remain. Live verification outstanding. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.razorpayKey",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Use an API key": "localizationApps.metadata24",
    "Connect Razorpay's provider-hosted MCP server.": "localizationApps.metadata278",
    "Sign in with Razorpay": "localizationApps.metadata280",
    "Razorpay API key": "localizationApps.metadata282",
    "Paste the base64-encoded key ID and secret": "localizationApps.metadata283",
    "Connect Razorpay in the browser. A Razorpay account; financial or destructive actions always require explicit approval.": "oct6Metadata.copy339",
    "A Razorpay account; financial or destructive actions always require explicit approval.": "oct6Metadata.copy340",
    "Financial or destructive actions must be explicitly approved before execution.": "oct6Metadata.copy039",
    "Use a customer-created Razorpay key. A Razorpay account; financial or destructive actions always require explicit approval.": "oct6Metadata.copy341"
  },
  "sanity": {
    "Edit content permitted by project role; global is MCP authorization, not a bypass of project ACLs. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.sanityKey",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Use an API key": "localizationApps.metadata24",
    "Connect Sanity's provider-hosted MCP server.": "localizationApps.metadata287",
    "Sign in with Sanity": "localizationApps.metadata289",
    "Sanity API key": "localizationApps.metadata291",
    "Connect Sanity in the browser. A Sanity account with access to the relevant projects and datasets.": "oct6Metadata.copy349",
    "A Sanity account with access to the relevant projects and datasets.": "oct6Metadata.copy350",
    "Use a customer-created Sanity key. A Sanity account with access to the relevant projects and datasets.": "oct6Metadata.copy351"
  },
  "similarweb": {
    "None: analytics retrieval; subscription entitlements apply. A read-only key is sufficient.": "oct5MetadataAddendum.similarwebKey",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Use an API key": "localizationApps.metadata24",
    "Connect Similarweb's provider-hosted MCP server.": "localizationApps.metadata306",
    "Similarweb API key": "localizationApps.metadata308",
    "Paste your Similarweb API key": "localizationApps.metadata309",
    "Use a customer-created Similarweb key. A Similarweb subscription with API access and an API key.": "oct6Metadata.copy372",
    "A Similarweb subscription with API access and an API key.": "oct6Metadata.copy374"
  },
  "stripe": {
    "Account- and sandbox-specific writes selected during Stripe consent; financial approvals and restricted-key permissions remain. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.stripeKey",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Use an API key": "localizationApps.metadata24",
    "Connect Stripe's provider-hosted MCP server.": "localizationApps.metadata312",
    "Sign in with Stripe": "localizationApps.metadata314",
    "Stripe API key": "localizationApps.metadata316",
    "Connect Stripe in the browser. A Stripe account; the server is public preview and payment actions require explicit approval.": "oct6Metadata.copy383",
    "A Stripe account; the server is public preview and payment actions require explicit approval.": "oct6Metadata.copy384",
    "Financial or destructive actions must be explicitly approved before execution.": "oct6Metadata.copy039",
    "Use a customer-created Stripe key. A Stripe account; the server is public preview and payment actions require explicit approval.": "oct6Metadata.copy385"
  },
  "supabase": {
    "Project/database/environment/storage changes and Edge Function deployment. Project selection and optional read-only configuration remain authoritative. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.supabaseKey",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Use an API key": "localizationApps.metadata24",
    "Read-only mode": "localizationApps.metadata250",
    "Feature groups": "localizationApps.metadata252",
    "Connect Supabase's provider-hosted MCP server.": "localizationApps.metadata318",
    "Sign in with Supabase": "localizationApps.metadata320",
    "Project reference": "localizationApps.metadata321",
    "Scope the connection to one development project.": "localizationApps.metadata323",
    "Enable this to prevent the connection from changing the database.": "localizationApps.metadata324",
    "Optional comma-separated feature groups.": "localizationApps.metadata326",
    "Supabase API key": "localizationApps.metadata328",
    "Connect Supabase in the browser and scope the connection to one development project. Write tools start enabled and remain governed by Paperclip's action policies.": "oct6Metadata.copy388",
    "A Supabase account; use a development project and review write actions before connecting production data.": "oct6Metadata.copy389",
    "Do not connect production data unless you have reviewed Supabase's MCP security guidance.": "oct6Metadata.copy390",
    "Use a customer-created Supabase key scoped to one development project. Write tools start enabled and remain governed by Paperclip's action policies.": "oct6Metadata.copy395"
  },
  "brex": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Brex's provider-hosted MCP server.": "localizationApps.metadata30",
    "Sign in with Brex": "localizationApps.metadata32",
    "Connect Brex in the browser. Brex early access and an administrator enabling the integration; financial actions require explicit approval.": "oct6Metadata.copy037",
    "Brex early access and an administrator enabling the integration; financial actions require explicit approval.": "oct6Metadata.copy038",
    "Financial or destructive actions must be explicitly approved before execution.": "oct6Metadata.copy039"
  },
  "candid": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Candid's provider-hosted MCP server.": "localizationApps.metadata33",
    "Sign in with Candid": "localizationApps.metadata35",
    "Connect Candid in the browser. A Candid account with access to the MCP connector.": "oct6Metadata.copy044",
    "A Candid account with access to the MCP connector.": "oct6Metadata.copy045"
  },
  "clickhouse": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect ClickHouse's provider-hosted MCP server.": "localizationApps.metadata36",
    "Sign in with ClickHouse": "localizationApps.metadata38",
    "ClickHouse Cloud service ID": "localizationApps.metadata39",
    "Copy the service ID from ClickStack → Team Settings → API & Agents.": "localizationApps.metadata41",
    "Connect ClickHouse in the browser. A ClickHouse Cloud ClickStack service and its service ID.": "oct6Metadata.copy051",
    "A ClickHouse Cloud ClickStack service and its service ID.": "oct6Metadata.copy052"
  },
  "cloudinary": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Cloudinary's provider-hosted MCP server.": "localizationApps.metadata48",
    "Sign in with Cloudinary": "localizationApps.metadata50",
    "Connect Cloudinary in the browser. A Cloudinary account; authorization is limited by the signed-in user's roles.": "oct6Metadata.copy060",
    "A Cloudinary account; authorization is limited by the signed-in user's roles.": "oct6Metadata.copy061"
  },
  "composio": {
    "Connect Composio so Paperclip can discover and manage the toolkits in your project.": "localizationApps.metadata57",
    "Composio project API key": "localizationApps.metadata60",
    "Paste the Composio API key": "localizationApps.metadata61",
    "Discover and use connected apps through Composio Connect.": "oct6Metadata.copy082",
    "Use the provider-hosted connection for the quickest setup.": "oct6Metadata.copy013",
    "Sign in to Composio Connect, or paste an externally configured MCP session URL and headers.": "oct6Metadata.copy083"
  },
  "context7": {
    "Look up current documentation for software libraries.": "localizationApps.metadata62",
    "Use the provider-hosted connection for the quickest setup.": "oct6Metadata.copy013",
    "Connect Context7 to give agents current library documentation.": "oct6Metadata.copy086"
  },
  "egnyte": {
    "Connect Egnyte's provider-hosted MCP server.": "localizationApps.metadata65",
    "Sign in with Egnyte": "localizationApps.metadata67",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Egnyte in the browser. An eligible Egnyte plan and administrator approval for external LLM access.": "oct6Metadata.copy099",
    "An eligible Egnyte plan and administrator approval for external LLM access.": "oct6Metadata.copy100"
  },
  "embat": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Embat's provider-hosted MCP server.": "localizationApps.metadata68",
    "Sign in with Embat": "localizationApps.metadata70",
    "Connect Embat in the browser. An Embat account; pilot the connection because provider setup documentation is sparse.": "oct6Metadata.copy102",
    "An Embat account; pilot the connection because provider setup documentation is sparse.": "oct6Metadata.copy103"
  },
  "github": {
    "Repository contents, issues, pull requests and other granted toolsets; selected repos and installation/PAT permissions apply. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.githubKey",
    "Give agents access to GitHub repositories, issues, and pull requests.": "oct5Metadata.githubDescription",
    "Connect GitHub": "localizationProjectRepositories.connectGithub",
    "Read code and pull requests, and coordinate repository work.": "localizationApps.metadata71",
    "Connect with GitHub": "localizationApps.metadata72",
    "Personal access token (advanced)": "localizationApps.metadata75",
    "GitHub token": "localizationApps.metadata77",
    "Connect your GitHub account for durable MCP, shell Git, gh, and repository access.": "oct6Metadata.copy137",
    "Authorize Paperclip, then choose selected repositories in GitHub. You can edit repository access later from GitHub's installation settings.": "oct6Metadata.copy138",
    "Shell Git and gh receive this identity for the run and are not constrained by per-tool Ask-first controls.": "oct6Metadata.copy139",
    "Use the provider-hosted connection for the quickest setup.": "oct6Metadata.copy013",
    "Create a fine-grained token limited to the repositories agents should use.": "oct6Metadata.copy140"
  },
  "gmail": {
    "Search and read Gmail messages and create drafts without enabling mail sending.": "localizationApps.metadata79",
    "Connect with Paperclip": "localizationApps.metadata81",
    "Read only": "localizationApps.metadata82",
    "Search and read messages, threads, drafts, and labels.": "localizationApps.metadata83",
    "Use your own Google OAuth app": "localizationApps.metadata86",
    "Read & create drafts": "localizationApps.metadata89",
    "Read Gmail and create drafts for review in Gmail.": "localizationApps.metadata90",
    "Google Developer Preview access required": "oct6Metadata.copy143",
    "Google must register both the Workspace email used to authorize Paperclip and the Google Cloud project that owns the OAuth client. Registration is limited to those emails and projects; it does not enable unrelated Paperclip customers.": "oct6Metadata.copy144",
    "Apply with the Workspace email that will sign in and the Google Cloud project that owns the OAuth client.": "oct6Metadata.copy145",
    "Wait for the Google Group notification and then Google's final project-registration email, usually within a couple of days.": "oct6Metadata.copy146",
    "Add every additional tester email or Cloud project through Google's member request forms before connecting.": "oct6Metadata.copy147",
    "Apply or verify Developer Preview enrollment": "oct6Metadata.copy148",
    "Use Paperclip-managed Google OAuth for read-only Gmail access.": "oct6Metadata.copy149",
    "Connect Gmail with read-only access. Sending, deleting, moving, and relabeling mail are not enabled.": "oct6Metadata.copy150",
    "Google Workspace MCP servers are in Developer Preview.": "oct6Metadata.copy151",
    "Use a customer-owned Google OAuth client for read-only Gmail access.": "oct6Metadata.copy152",
    "Enable the Gmail and Gmail MCP APIs in your Google Cloud project, then register Paperclip's callback URI.": "oct6Metadata.copy153",
    "Use Paperclip-managed Google OAuth to read Gmail and create drafts.": "oct6Metadata.copy154",
    "Connect Gmail to search and read mail and create drafts. Sending mail is permanently disabled.": "oct6Metadata.copy155",
    "Draft creation requires approval. Sending mail is not enabled.": "oct6Metadata.copy156",
    "Use a customer-owned Google OAuth client to read Gmail and create drafts.": "oct6Metadata.copy157"
  },
  "google-calendar": {
    "Connect with Paperclip": "localizationApps.metadata81",
    "Read only": "localizationApps.metadata82",
    "Use your own Google OAuth app": "localizationApps.metadata86",
    "Read calendars and manage Google Calendar events.": "localizationApps.metadata94",
    "Read calendars, events, and availability.": "localizationApps.metadata95",
    "Read & manage": "localizationApps.metadata100",
    "Create, update, respond to, and delete events.": "localizationApps.metadata101",
    "Google Developer Preview access required": "oct6Metadata.copy143",
    "Google must register both the Workspace email used to authorize Paperclip and the Google Cloud project that owns the OAuth client. Registration is limited to those emails and projects; it does not enable unrelated Paperclip customers.": "oct6Metadata.copy144",
    "Apply with the Workspace email that will sign in and the Google Cloud project that owns the OAuth client.": "oct6Metadata.copy145",
    "Wait for the Google Group notification and then Google's final project-registration email, usually within a couple of days.": "oct6Metadata.copy146",
    "Add every additional tester email or Cloud project through Google's member request forms before connecting.": "oct6Metadata.copy147",
    "Apply or verify Developer Preview enrollment": "oct6Metadata.copy148",
    "Use Paperclip-managed OAuth for read-only Calendar access.": "oct6Metadata.copy159",
    "Connect Google Calendar to read schedules and availability.": "oct6Metadata.copy160",
    "Google Workspace MCP servers are in Developer Preview.": "oct6Metadata.copy151",
    "Use a customer-owned OAuth client for read-only Calendar access.": "oct6Metadata.copy161",
    "Enable the Calendar and Calendar MCP APIs, then register Paperclip's callback URI.": "oct6Metadata.copy162",
    "Use Paperclip-managed OAuth to read and manage Calendar events.": "oct6Metadata.copy163",
    "Connect Google Calendar to read and manage events.": "oct6Metadata.copy164",
    "All event mutations require approval.": "oct6Metadata.copy165",
    "Use a customer-owned OAuth client to read and manage Calendar events.": "oct6Metadata.copy166"
  },
  "google-chat": {
    "Connect with Paperclip": "localizationApps.metadata81",
    "Read only": "localizationApps.metadata82",
    "Use your own Google OAuth app": "localizationApps.metadata86",
    "Search and read Google Chat conversations and send messages.": "localizationApps.metadata105",
    "Search conversations and read messages.": "localizationApps.metadata106",
    "Read & send": "localizationApps.metadata111",
    "Read Chat and send messages.": "localizationApps.metadata112",
    "Google Developer Preview access required": "oct6Metadata.copy143",
    "Google must register both the Workspace email used to authorize Paperclip and the Google Cloud project that owns the OAuth client. Registration is limited to those emails and projects; it does not enable unrelated Paperclip customers.": "oct6Metadata.copy144",
    "Apply with the Workspace email that will sign in and the Google Cloud project that owns the OAuth client.": "oct6Metadata.copy145",
    "Wait for the Google Group notification and then Google's final project-registration email, usually within a couple of days.": "oct6Metadata.copy146",
    "Add every additional tester email or Cloud project through Google's member request forms before connecting.": "oct6Metadata.copy147",
    "Apply or verify Developer Preview enrollment": "oct6Metadata.copy148",
    "Use Paperclip-managed OAuth for read-only Chat access.": "oct6Metadata.copy168",
    "Connect Google Chat to search conversations and read messages. Read/unread filtering and membership listing are not supported.": "oct6Metadata.copy169",
    "Google Workspace MCP servers are in Developer Preview.": "oct6Metadata.copy151",
    "Use a customer-owned OAuth client for read-only Chat access.": "oct6Metadata.copy170",
    "Enable the Chat and Chat MCP APIs, configure a Chat app, then register Paperclip's callback URI. Read/unread filtering and membership listing are not supported.": "oct6Metadata.copy171",
    "A Google Chat app must be configured in the Cloud project.": "oct6Metadata.copy172",
    "Use Paperclip-managed OAuth to read Chat and send messages.": "oct6Metadata.copy173",
    "Connect Google Chat to read conversations and send approved messages. Read/unread filtering and membership listing are not supported.": "oct6Metadata.copy174",
    "Sending messages requires approval.": "oct6Metadata.copy175",
    "Use a customer-owned OAuth client to read Chat and send messages.": "oct6Metadata.copy176"
  },
  "google-docs": {
    "Connect with Paperclip": "localizationApps.metadata81",
    "Read only": "localizationApps.metadata82",
    "Use your own Google OAuth app": "localizationApps.metadata86",
    "Read and update Google Docs documents.": "localizationApps.metadata116",
    "Read document text and structure.": "localizationApps.metadata117",
    "Read & edit": "localizationApps.metadata122",
    "Read and update documents.": "localizationApps.metadata123",
    "Google Developer Preview access required": "oct6Metadata.copy143",
    "Google must register both the Workspace email used to authorize Paperclip and the Google Cloud project that owns the OAuth client. Registration is limited to those emails and projects; it does not enable unrelated Paperclip customers.": "oct6Metadata.copy144",
    "Apply with the Workspace email that will sign in and the Google Cloud project that owns the OAuth client.": "oct6Metadata.copy145",
    "Wait for the Google Group notification and then Google's final project-registration email, usually within a couple of days.": "oct6Metadata.copy146",
    "Add every additional tester email or Cloud project through Google's member request forms before connecting.": "oct6Metadata.copy147",
    "Apply or verify Developer Preview enrollment": "oct6Metadata.copy148",
    "Use Paperclip-managed OAuth for read-only Docs access.": "oct6Metadata.copy178",
    "Connect Google Docs to read documents.": "oct6Metadata.copy179",
    "Google Workspace MCP servers are in Developer Preview.": "oct6Metadata.copy151",
    "Use a customer-owned OAuth client for read-only Docs access.": "oct6Metadata.copy180",
    "Enable the Drive, Docs, and Docs MCP APIs, then register Paperclip's callback URI.": "oct6Metadata.copy181",
    "Use Paperclip-managed OAuth to read and update Docs.": "oct6Metadata.copy182",
    "Connect Google Docs to read and update documents.": "oct6Metadata.copy183",
    "Document updates require approval.": "oct6Metadata.copy184",
    "Use a customer-owned OAuth client to read and update Docs.": "oct6Metadata.copy185"
  },
  "google-drive": {
    "Connect with Paperclip": "localizationApps.metadata81",
    "Read only": "localizationApps.metadata82",
    "Use your own Google OAuth app": "localizationApps.metadata86",
    "Search, read, create, and copy files in Google Drive.": "localizationApps.metadata127",
    "Search and read files and metadata.": "localizationApps.metadata128",
    "Read & create": "localizationApps.metadata133",
    "Read files and create or copy files.": "localizationApps.metadata134",
    "Google Developer Preview access required": "oct6Metadata.copy143",
    "Google must register both the Workspace email used to authorize Paperclip and the Google Cloud project that owns the OAuth client. Registration is limited to those emails and projects; it does not enable unrelated Paperclip customers.": "oct6Metadata.copy144",
    "Apply with the Workspace email that will sign in and the Google Cloud project that owns the OAuth client.": "oct6Metadata.copy145",
    "Wait for the Google Group notification and then Google's final project-registration email, usually within a couple of days.": "oct6Metadata.copy146",
    "Add every additional tester email or Cloud project through Google's member request forms before connecting.": "oct6Metadata.copy147",
    "Apply or verify Developer Preview enrollment": "oct6Metadata.copy148",
    "Use Paperclip-managed OAuth for read-only Drive access.": "oct6Metadata.copy187",
    "Connect Google Drive to search and read files. Google's Developer Preview Program must register the signed-in Workspace account and Google Cloud project before tools can run.": "oct6Metadata.copy188",
    "Before connecting, enroll the signed-in Workspace account and Google Cloud project in Google's Developer Preview Program and wait for the registration confirmation.": "oct6Metadata.copy189",
    "Use a customer-owned OAuth client for read-only Drive access.": "oct6Metadata.copy190",
    "Enroll the Workspace account and Google Cloud project in Google's Developer Preview Program, enable the Drive and Drive MCP APIs, then register Paperclip's callback URI.": "oct6Metadata.copy191",
    "Use Paperclip-managed OAuth for Drive read and create access.": "oct6Metadata.copy192",
    "Connect Google Drive to read files and create or copy app-accessible files. Google's Developer Preview Program must register the signed-in Workspace account and Google Cloud project before tools can run.": "oct6Metadata.copy193",
    "File creation and copying require approval.": "oct6Metadata.copy194",
    "Use a customer-owned OAuth client for Drive read and create access.": "oct6Metadata.copy195"
  },
  "google-people": {
    "Connect with Paperclip": "localizationApps.metadata81",
    "Use your own Google OAuth app": "localizationApps.metadata86",
    "Search contacts and directory profiles with the Google People API.": "localizationApps.metadata138",
    "Read contacts": "localizationApps.metadata139",
    "Search contacts, directory people, and your profile.": "localizationApps.metadata140",
    "Google Developer Preview access required": "oct6Metadata.copy143",
    "Google must register both the Workspace email used to authorize Paperclip and the Google Cloud project that owns the OAuth client. Registration is limited to those emails and projects; it does not enable unrelated Paperclip customers.": "oct6Metadata.copy144",
    "Apply with the Workspace email that will sign in and the Google Cloud project that owns the OAuth client.": "oct6Metadata.copy145",
    "Wait for the Google Group notification and then Google's final project-registration email, usually within a couple of days.": "oct6Metadata.copy146",
    "Add every additional tester email or Cloud project through Google's member request forms before connecting.": "oct6Metadata.copy147",
    "Apply or verify Developer Preview enrollment": "oct6Metadata.copy148",
    "Use Paperclip-managed OAuth for Google People access.": "oct6Metadata.copy197",
    "Connect Google People to search contacts and directory profiles.": "oct6Metadata.copy198",
    "Google Workspace MCP servers are in Developer Preview.": "oct6Metadata.copy151",
    "Use a customer-owned OAuth client for Google People access.": "oct6Metadata.copy199",
    "Enable the People and People MCP APIs, then register Paperclip's callback URI.": "oct6Metadata.copy200",
    "Directory search availability depends on your Workspace account.": "oct6Metadata.copy201"
  },
  "google-sheets": {
    "Connect with Paperclip": "localizationApps.metadata81",
    "Read only": "localizationApps.metadata82",
    "Use your own Google OAuth app": "localizationApps.metadata86",
    "Read & edit": "localizationApps.metadata122",
    "Read and update Google Sheets spreadsheets.": "localizationApps.metadata145",
    "Read spreadsheet values and structure.": "localizationApps.metadata146",
    "Read and update spreadsheet values, formulas, and dimensions.": "localizationApps.metadata151",
    "Use the Paperclip robot account": "localizationApps.metadata155",
    "Share selected sheets": "localizationApps.metadata156",
    "Share only named spreadsheets with the Paperclip robot account.": "localizationApps.metadata157",
    "Google Developer Preview access required": "oct6Metadata.copy143",
    "Google must register both the Workspace email used to authorize Paperclip and the Google Cloud project that owns the OAuth client. Registration is limited to those emails and projects; it does not enable unrelated Paperclip customers.": "oct6Metadata.copy144",
    "Apply with the Workspace email that will sign in and the Google Cloud project that owns the OAuth client.": "oct6Metadata.copy145",
    "Wait for the Google Group notification and then Google's final project-registration email, usually within a couple of days.": "oct6Metadata.copy146",
    "Add every additional tester email or Cloud project through Google's member request forms before connecting.": "oct6Metadata.copy147",
    "Apply or verify Developer Preview enrollment": "oct6Metadata.copy148",
    "Use Paperclip-managed OAuth for read-only Sheets access.": "oct6Metadata.copy203",
    "Connect Google Sheets to read spreadsheets.": "oct6Metadata.copy204",
    "Google Workspace MCP servers are in Developer Preview.": "oct6Metadata.copy151",
    "Use a customer-owned OAuth client for read-only Sheets access.": "oct6Metadata.copy205",
    "Enable the Drive, Sheets, and Sheets MCP APIs, then register Paperclip's callback URI.": "oct6Metadata.copy206",
    "Use Paperclip-managed OAuth to read and update Sheets.": "oct6Metadata.copy207",
    "Connect Google Sheets to read and update spreadsheets.": "oct6Metadata.copy208",
    "Spreadsheet updates require approval.": "oct6Metadata.copy209",
    "Use a customer-owned OAuth client to read and update Sheets.": "oct6Metadata.copy210",
    "Share selected spreadsheets with the Paperclip robot account instead of connecting a Google identity.": "oct6Metadata.copy211",
    "Share each spreadsheet with the Paperclip robot email, then paste the sheet links.": "oct6Metadata.copy212"
  },
  "google-slides": {
    "Connect with Paperclip": "localizationApps.metadata81",
    "Read only": "localizationApps.metadata82",
    "Use your own Google OAuth app": "localizationApps.metadata86",
    "Read & edit": "localizationApps.metadata122",
    "Read and update Google Slides presentations.": "localizationApps.metadata160",
    "Read presentation slides and content.": "localizationApps.metadata161",
    "Read and update presentations.": "localizationApps.metadata166",
    "Google Developer Preview access required": "oct6Metadata.copy143",
    "Google must register both the Workspace email used to authorize Paperclip and the Google Cloud project that owns the OAuth client. Registration is limited to those emails and projects; it does not enable unrelated Paperclip customers.": "oct6Metadata.copy144",
    "Apply with the Workspace email that will sign in and the Google Cloud project that owns the OAuth client.": "oct6Metadata.copy145",
    "Wait for the Google Group notification and then Google's final project-registration email, usually within a couple of days.": "oct6Metadata.copy146",
    "Add every additional tester email or Cloud project through Google's member request forms before connecting.": "oct6Metadata.copy147",
    "Apply or verify Developer Preview enrollment": "oct6Metadata.copy148",
    "Use Paperclip-managed OAuth for read-only Slides access.": "oct6Metadata.copy214",
    "Connect Google Slides to read presentations.": "oct6Metadata.copy215",
    "Google Workspace MCP servers are in Developer Preview.": "oct6Metadata.copy151",
    "Use a customer-owned OAuth client for read-only Slides access.": "oct6Metadata.copy216",
    "Enable the Drive, Slides, and Slides MCP APIs, then register Paperclip's callback URI.": "oct6Metadata.copy217",
    "Use Paperclip-managed OAuth to read and update Slides.": "oct6Metadata.copy218",
    "Connect Google Slides to read and update presentations.": "oct6Metadata.copy219",
    "Presentation updates require approval.": "oct6Metadata.copy220",
    "Use a customer-owned OAuth client to read and update Slides.": "oct6Metadata.copy221"
  },
  "google-workspace-search": {
    "Connect with Paperclip": "localizationApps.metadata81",
    "Use your own Google OAuth app": "localizationApps.metadata86",
    "Search Gmail, Drive, Calendar, and Chat through one read-only Google Workspace search tool.": "localizationApps.metadata170",
    "Search Workspace": "localizationApps.metadata171",
    "Search Gmail, Drive, Calendar, and Chat without write access.": "localizationApps.metadata172",
    "Google Developer Preview access required": "oct6Metadata.copy143",
    "Google must register both the Workspace email used to authorize Paperclip and the Google Cloud project that owns the OAuth client. Registration is limited to those emails and projects; it does not enable unrelated Paperclip customers.": "oct6Metadata.copy144",
    "Apply with the Workspace email that will sign in and the Google Cloud project that owns the OAuth client.": "oct6Metadata.copy145",
    "Wait for the Google Group notification and then Google's final project-registration email, usually within a couple of days.": "oct6Metadata.copy146",
    "Add every additional tester email or Cloud project through Google's member request forms before connecting.": "oct6Metadata.copy147",
    "Apply or verify Developer Preview enrollment": "oct6Metadata.copy148",
    "Use Paperclip-managed OAuth for cross-product Workspace search.": "oct6Metadata.copy223",
    "Connect Google Workspace Search for one read-only search tool spanning Gmail, Drive, Calendar, and Chat.": "oct6Metadata.copy224",
    "This requests read access to all four supported search corpora.": "oct6Metadata.copy225",
    "Google Workspace MCP servers are in Developer Preview.": "oct6Metadata.copy151",
    "Use a customer-owned OAuth client for cross-product Workspace search.": "oct6Metadata.copy226",
    "Enable the Gmail, Drive, Calendar, Chat, and Workspace MCP APIs, then register Paperclip's callback URI.": "oct6Metadata.copy227"
  },
  "hugging-face": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Hugging Face's provider-hosted MCP server.": "localizationApps.metadata177",
    "Sign in with Hugging Face": "localizationApps.metadata179",
    "Connect Hugging Face in the browser. A Hugging Face account.": "oct6Metadata.copy242",
    "A Hugging Face account.": "oct6Metadata.copy243"
  },
  "jira": {
    "Connect Jira's provider-hosted MCP server.": "localizationApps.metadata180",
    "Sign in with Jira": "localizationApps.metadata182",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Jira in the browser. An active Jira or Confluence site; tenant policy may require an administrator to approve the client.": "oct6Metadata.copy246",
    "An active Jira or Confluence site; tenant policy may require an administrator to approve the client.": "oct6Metadata.copy247"
  },
  "linear": {
    "Connect Linear for issues and projects. Paperclip registers its own OAuth client with Linear's MCP server, so no developer-console setup is needed.": "oct5Metadata.linearGuidance",
    "Create, update, and read Linear issues.": "localizationApps.metadata189",
    "Use the provider-hosted connection for the quickest setup.": "oct6Metadata.copy013",
    "Authorization": "localizationFinalAuditExtras.authorization"
  },
  "local-falcon": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Local Falcon's provider-hosted MCP server.": "localizationApps.metadata191",
    "Sign in with Local Falcon": "localizationApps.metadata193",
    "Connect Local Falcon in the browser. A Local Falcon account with MCP access.": "oct6Metadata.copy255",
    "A Local Falcon account with MCP access.": "oct6Metadata.copy256"
  },
  "make": {
    "Connect Make's provider-hosted MCP server.": "localizationApps.metadata194",
    "Sign in with Make": "localizationApps.metadata196",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Make in the browser. A Make account and access to the scenarios exposed to MCP.": "oct6Metadata.copy261",
    "A Make account and access to the scenarios exposed to MCP.": "oct6Metadata.copy262"
  },
  "manufact": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Manufact's provider-hosted MCP server.": "localizationApps.metadata197",
    "Sign in with Manufact": "localizationApps.metadata199",
    "Connect Manufact in the browser. A Manufact account with MCP access.": "oct6Metadata.copy264",
    "A Manufact account with MCP access.": "oct6Metadata.copy265"
  },
  "miro": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Miro's provider-hosted MCP server.": "localizationApps.metadata204",
    "Sign in with Miro": "localizationApps.metadata206",
    "Connect Miro in the browser. A Miro account; enterprise administrators may restrict third-party MCP clients.": "oct6Metadata.copy284",
    "A Miro account; enterprise administrators may restrict third-party MCP clients.": "oct6Metadata.copy285"
  },
  "mixpanel": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Mixpanel's provider-hosted MCP server.": "localizationApps.metadata207",
    "Sign in with Mixpanel": "localizationApps.metadata209",
    "Connect Mixpanel in the browser. A Mixpanel account; the hosted MCP server is currently beta.": "oct6Metadata.copy287",
    "A Mixpanel account; the hosted MCP server is currently beta.": "oct6Metadata.copy288",
    "This provider's hosted MCP server is currently beta or preview.": "oct6Metadata.copy065"
  },
  "netlify": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Netlify's provider-hosted MCP server.": "localizationApps.metadata210",
    "Sign in with Netlify": "localizationApps.metadata212",
    "Connect Netlify in the browser. A Netlify account with access to the relevant team and sites.": "oct6Metadata.copy294",
    "A Netlify account with access to the relevant team and sites.": "oct6Metadata.copy295"
  },
  "notion": {
    "Read and update pages in your Notion workspace.": "localizationApps.metadata213",
    "Use the provider-hosted connection for the quickest setup.": "oct6Metadata.copy013",
    "Connect Notion for workspace content. Share only the pages and databases agents should use.": "oct6Metadata.copy297",
    "Authorization": "localizationFinalAuditExtras.authorization"
  },
  "oauth-generic": {
    "Connect a provider using your own OAuth client.": "localizationApps.metadata215",
    "Client ID": "localizationApps.metadata217",
    "Paste the client ID": "localizationApps.metadata218",
    "Client secret": "localizationApps.metadata219",
    "Paste the client secret": "localizationApps.metadata220",
    "OAuth app": "oct6Metadata.copy298",
    "Use credentials from your provider account.": "oct5Metadata.providerCredentials",
    "Register an OAuth client with the provider and add Paperclip's redirect URI.": "oct6Metadata.copy300"
  },
  "pagerduty": {
    "Incident and on-call changes require a full-access API key and role access. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.pagerdutyKey",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Connect PagerDuty's provider-hosted MCP server.": "localizationApps.metadata227",
    "US service region": "localizationApps.metadata229",
    "PagerDuty API key": "localizationApps.metadata230",
    "Paste your PagerDuty user API token": "localizationApps.metadata231",
    "EU service region": "localizationApps.metadata232",
    "Use a customer-created PagerDuty key. A PagerDuty API token; choose the regional endpoint that hosts the account.": "oct6Metadata.copy309",
    "A PagerDuty API token; choose the regional endpoint that hosts the account.": "oct6Metadata.copy310"
  },
  "planetscale": {
    "Read and write": "oct5Metadata.readWrite",
    "Query and change the databases you authorize in PlanetScale.": "oct5Metadata.planetscaleWrite",
    "Read only": "localizationApps.metadata82",
    "Inspect database performance with the insights-only server.": "oct5Metadata.planetscaleRead",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect PlanetScale's provider-hosted MCP server.": "localizationApps.metadata233",
    "Database access": "localizationApps.metadata235",
    "Project or database": "localizationApps.metadata236",
    "Optional project or database name": "localizationApps.metadata237",
    "Records the intended database boundary; final access is selected during PlanetScale authorization.": "localizationApps.metadata238",
    "Branch": "localizationApps.metadata239",
    "Optional branch name": "localizationApps.metadata240",
    "Records the intended branch boundary; final access is selected during PlanetScale authorization.": "localizationApps.metadata241",
    "Insights only": "localizationApps.metadata243",
    "Connect PlanetScale in the browser. A PlanetScale account; database and branch access are chosen during authorization.": "oct6Metadata.copy312",
    "A PlanetScale account; database and branch access are chosen during authorization.": "oct6Metadata.copy313",
    "Use query insights and schema recommendations without query execution tools.": "oct6Metadata.copy314"
  },
  "posthog": {
    "Analytics objects, feature flags, experiments, error triage and other enabled product actions. readonly/feature/tool filters remain enforced. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.posthogKey",
    "Analyze product usage, errors, feature flags, and experiments with PostHog's hosted MCP server.": "localizationApps.metadata244",
    "Pin to project ID": "localizationApps.metadata247",
    "Optional numeric project ID": "localizationApps.metadata248",
    "Optional. Pin this connection to one project and remove PostHog's project-switching tool.": "localizationApps.metadata249",
    "Read-only mode": "localizationApps.metadata250",
    "Turn on to hide tools that can change PostHog data.": "localizationApps.metadata251",
    "Feature groups": "localizationApps.metadata252",
    "Optional comma-separated feature groups": "localizationApps.metadata253",
    "Leave blank to expose every feature group, or enter a comma-separated list to narrow access.": "localizationApps.metadata254",
    "Individual tools": "localizationApps.metadata255",
    "Optional comma-separated tool names": "localizationApps.metadata256",
    "Leave blank to expose all tools. Exact names here are combined with any feature groups.": "localizationApps.metadata257",
    "Tool response mode": "localizationApps.metadata258",
    "Paperclip uses individual tools so every action can be governed. CLI mode remains unavailable until nested execution is governed.": "localizationApps.metadata259",
    "Sign in with PostHog": "localizationApps.metadata260",
    "Use a personal API key": "localizationApps.metadata262",
    "PostHog personal API key": "localizationApps.metadata263",
    "Sign in with PostHog in the browser. Recommended for hosted PostHog accounts.": "oct6Metadata.copy316",
    "Connect with PostHog's recommended defaults. Project pinning, read-only access, and catalog filters are optional advanced controls.": "oct6Metadata.copy317",
    "Authorization": "localizationFinalAuditExtras.authorization",
    "Use a PostHog personal API key when browser sign-in is not suitable.": "oct6Metadata.copy322"
  },
  "postman": {
    "Collection/workspace/API actions supported by the selected minimal/code/full endpoint and account role. Create a key with read and write permissions for these actions; Paperclip cannot increase an existing key’s permissions.": "oct5MetadataAddendum.postmanKey",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Use a restricted customer-owned key when browser sign-in is not suitable.": "oct5Metadata.restrictedKey",
    "Connect Postman's provider-hosted MCP server.": "localizationApps.metadata265",
    "US · Browser sign-in": "localizationApps.metadata267",
    "Minimal": "localizationApps.metadata268",
    "Essential workspace, collection, and environment tools with the smallest tool catalog.": "localizationApps.metadata269",
    "Code": "localizationApps.metadata270",
    "Tools for generating client code from API definitions.": "localizationApps.metadata271",
    "Full": "localizationApps.metadata272",
    "All Postman API tools, including write-capable collaboration and advanced features.": "localizationApps.metadata273",
    "EU · API key": "localizationApps.metadata275",
    "Postman API key": "localizationApps.metadata276",
    "Connect Postman in the browser. A Postman account; OAuth is available for US endpoints and API keys are required for EU endpoints.": "oct6Metadata.copy325",
    "A Postman account; OAuth is available for US endpoints and API keys are required for EU endpoints.": "oct6Metadata.copy326",
    "Use a customer-created Postman key. A Postman account; OAuth is available for US endpoints and API keys are required for EU endpoints.": "oct6Metadata.copy327"
  },
  "resend": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Resend's provider-hosted MCP server.": "localizationApps.metadata284",
    "Sign in with Resend": "localizationApps.metadata286",
    "Connect Resend in the browser. A Resend account with access to the relevant domains.": "oct6Metadata.copy343",
    "A Resend account with access to the relevant domains.": "oct6Metadata.copy344"
  },
  "sentry": {
    "Investigate errors, releases, and production issues.": "localizationApps.metadata293",
    "Use the provider-hosted connection for the quickest setup.": "oct6Metadata.copy013",
    "Connect the Sentry organization and projects agents need for incident work.": "oct6Metadata.copy354"
  },
  "shopify": {
    "Search a store's products and policies, and manage shopping carts.": "localizationApps.metadata295",
    "Shopify UCP commerce": "localizationApps.metadata298",
    "Store domain": "localizationApps.metadata299",
    "Enter the permanent myshopify.com domain without https://. Custom storefront domains are not the MCP endpoint.": "localizationApps.metadata301",
    "Storefront policies and compatibility tools": "localizationApps.metadata304",
    "Recommended for Shopify's current UCP catalog, cart, and checkout tools.": "oct6Metadata.copy356",
    "Connect Shopify's current UCP server for shopper-facing catalog and commerce tools. Paperclip supplies the required agent profile automatically.": "oct6Metadata.copy357",
    "This is Shopify's shopper-facing UCP server, not Admin API access. It does not manage merchant products or customers.": "oct6Metadata.copy359",
    "The storefront must be public. A private or password-protected storefront returns HTTP 401 even when the merchant is signed in to Shopify Admin.": "oct6Metadata.copy360",
    "Paperclip currently uses Shopify's documented hosted agent-profile fixture while Paperclip's production UCP profile is being established.": "oct6Metadata.copy361",
    "Use Shopify's compatibility server when agents need storefront policy and FAQ search.": "oct6Metadata.copy362",
    "Connect Shopify's official Storefront MCP server for shopper-facing catalog, policy, and cart tools.": "oct6Metadata.copy363",
    "This is Shopify's Storefront MCP, not Admin API access. It does not manage merchant products, orders, or customers.": "oct6Metadata.copy364",
    "Launch the storefront before connecting": "oct6Metadata.copy365",
    "Shopify's Storefront MCP is a public, no-auth endpoint. Paperclip cannot use the merchant's Shopify Admin session to bypass a private storefront.": "oct6Metadata.copy366",
    "Select a Shopify plan; Shopify keeps trial storefronts private until a plan is selected.": "oct6Metadata.copy367",
    "In Shopify Admin, open Online Store → Preferences and set Storefront visibility to Public (remove password protection).": "oct6Metadata.copy368",
    "Use the permanent <store>.myshopify.com domain in Paperclip, even if the store also has a custom domain.": "oct6Metadata.copy369",
    "Open Shopify Admin": "oct6Metadata.copy370"
  },
  "slack": {
    "Use this connection as an agent tool": "chatUi.chatEndpointSetup.useThisConnectionAsAnAgentTool",
    "Chat with an agent": "communityPhoton.metadataMethod",
    "Bot User OAuth Token": "chatUi.chatEndpointSetup.botUserOAuthToken",
    "Signing Secret": "chatUi.chatEndpointSetup.signingSecret",
    "Search channels and coordinate team communication.": "localizationApps.metadata310",
    "Give agents Slack tools or let people start and continue Paperclip work from Slack.": "oct6Metadata.copy376",
    "Use the provider-hosted connection for the quickest setup.": "oct6Metadata.copy013",
    "Connect a Slack workspace and limit access to the channels agents need.": "oct6Metadata.copy377",
    "Let people in Slack start and continue work with one Paperclip agent.": "oct6Metadata.copy378",
    "Paste the Slack App signing secret": "oct6Metadata.copy380",
    "Create and install one Slack App for this agent. Paperclip receives verified Events API requests and interactive callbacks, acknowledges with reactions, responds in direct messages, and starts one Paperclip task per new mentioned channel thread.": "oct6Metadata.copy381"
  },
  "ticket-tailor": {
    "Connect Ticket Tailor's provider-hosted MCP server.": "localizationApps.metadata330",
    "Sign in with Ticket Tailor": "localizationApps.metadata332",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Ticket Tailor in the browser. A Ticket Tailor account; the provider may request an API key during its hosted authorization prompt.": "oct6Metadata.copy408",
    "A Ticket Tailor account; the provider may request an API key during its hosted authorization prompt.": "oct6Metadata.copy409"
  },
  "ticktick": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect TickTick's provider-hosted MCP server.": "localizationApps.metadata333",
    "Sign in with TickTick": "localizationApps.metadata335",
    "Connect TickTick in the browser. A TickTick account with MCP access.": "oct6Metadata.copy411",
    "A TickTick account with MCP access.": "oct6Metadata.copy412"
  },
  "todoist": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Todoist's provider-hosted MCP server.": "localizationApps.metadata336",
    "Sign in with Todoist": "localizationApps.metadata338",
    "Connect Todoist in the browser. A Todoist account.": "oct6Metadata.copy414",
    "A Todoist account.": "oct6Metadata.copy415"
  },
  "vercel": {
    "Inspect projects, deployments, and runtime logs.": "localizationApps.metadata339",
    "Use the provider-hosted connection for the quickest setup.": "oct6Metadata.copy013",
    "Connect the Vercel team and projects agents should operate.": "oct6Metadata.copy417",
    "Vercel currently reviews and approves MCP clients.": "oct6Metadata.copy418"
  },
  "webflow": {
    "Connect Webflow's provider-hosted MCP server.": "localizationApps.metadata341",
    "Sign in with Webflow": "localizationApps.metadata343",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Webflow in the browser. A Webflow account; workspace and site roles constrain accessible sites.": "oct6Metadata.copy420",
    "A Webflow account; workspace and site roles constrain accessible sites.": "oct6Metadata.copy421"
  },
  "wix": {
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Connect Wix's provider-hosted MCP server.": "localizationApps.metadata344",
    "Sign in with Wix": "localizationApps.metadata346",
    "Connect Wix in the browser. A Wix account with access to the relevant sites.": "oct6Metadata.copy423",
    "A Wix account with access to the relevant sites.": "oct6Metadata.copy424"
  },
  "zapier": {
    "Reach thousands of apps through your Zapier account.": "localizationApps.metadata350",
    "Paste generated MCP URL": "localizationApps.metadata353",
    "Use the complete provider-generated MCP URL from Zapier.": "oct6Metadata.copy444",
    "Create a Zapier MCP server, then paste the complete generated connection URL. The token remains embedded in that URL.": "oct6Metadata.copy445"
  },
  "arcade": {
    "Use the tools exposed by your Arcade MCP connection.": "oct6Metadata.copy012",
    "Use the provider-hosted connection for the quickest setup.": "oct6Metadata.copy013",
    "Paste your Arcade MCP URL. Sign in if required, or add a token or headers under Advanced authentication.": "oct6Metadata.copy014",
    "Connect MCP server": "oct6Metadata.copy015"
  },
  "bedrock": {
    "Use Claude through Amazon Bedrock with a Bedrock API key and AWS region.": "oct6Metadata.copy019",
    "Amazon Bedrock API key": "oct6Metadata.copy020",
    "Use your personal account or an explicitly shared company account.": "sep13AiMetadata.guidance",
    "API key": "localizationApps.metadata7",
    "Enter API key": "sep13AiMetadata.apiKeyPlaceholder"
  },
  "chat-completions-api": {
    "Connect any compatible harness to a Chat Completions-compatible provider or gateway.": "oct6Metadata.copy047",
    "Chat Completions API API key": "oct6Metadata.copy048",
    "Use your personal account or an explicitly shared company account.": "sep13AiMetadata.guidance",
    "API key": "localizationApps.metadata7",
    "Enter API key": "sep13AiMetadata.apiKeyPlaceholder"
  },
  "discord": {
    "Let people start and continue Paperclip work with an agent from Discord.": "oct6Metadata.copy088",
    "Chat with an agent": "communityPhoton.metadataMethod",
    "Let people in Discord start and continue work with one Paperclip agent.": "oct6Metadata.copy090",
    "Bot token": "chatUi.chatEndpointSetup.botToken",
    "Paste the Discord bot token": "oct6Metadata.copy092",
    "Application ID": "chatUi.chatEndpointSetup.applicationID",
    "Server ID": "chatUi.chatEndpointSetup.serverID",
    "Create one dedicated Discord application and bot, enable the Message Content intent, install it in one server with the documented bot permissions, then connect its bot token, Application ID, and server ID. Paperclip starts one Discord thread per root bot mention and keeps the linked Paperclip task authoritative.": "oct6Metadata.copy096"
  },
  "enterpret": {
    "Ask questions about your customer feedback and pull verbatim quotes with citations.": "oct6Metadata.copy105",
    "Recommended. Use an organization auth token from Settings → Enterpret MCP. This is the primary, store-ready connection method.": "oct6Metadata.copy106",
    "Generate an auth token in Enterpret under Settings, Enterpret MCP, then paste it below. One token belongs to one Enterpret organization. This is the recommended connection method.": "oct6Metadata.copy107",
    "Use an auth token": "oct6Metadata.copy108",
    "Enterpret auth token": "oct6Metadata.copy109",
    "Paste the token from Settings, Enterpret MCP": "oct6Metadata.copy110",
    "An organization auth token can read that organization's customer feedback. Use a token from Settings > Enterpret MCP and check its displayed expiry there.": "oct6Metadata.copy111",
    "Check your auth token's expiry in Enterpret Settings > Enterpret MCP and replace it before it lapses.": "oct6Metadata.copy112",
    "This connection reads customer feedback, including verbatim quotes with speaker attribution.": "oct6Metadata.copy113",
    "run_graph_query starts as Ask first. Cypher is not established as read-only even when Enterpret advertises readOnlyHint.": "oct6Metadata.copy114",
    "Use browser sign-in when each person should query feedback under their own Enterpret account.": "oct6Metadata.copy115",
    "Sign in to Enterpret in the browser to query the official read-only MCP. Each person connects with their own Enterpret account, and Enterpret attributes their queries individually.": "oct6Metadata.copy116",
    "Sign in with Enterpret": "oct6Metadata.copy117",
    "The official Enterpret MCP is read-only. Enterpret previously reported broader OAuth scopes, including mcp:write and email, than Paperclip requested. Enterpret is correcting this scope reporting; it does not establish access to the separate beta Agent MCP.": "oct6Metadata.copy118",
    "After revocation, Enterpret may cache token validity for up to 24 hours. Disconnect this connection to stop Paperclip access immediately. Enterpret is reducing this delay.": "oct6Metadata.copy119",
    "You need an Enterpret account with access to your organization's feedback.": "oct6Metadata.copy120"
  },
  "executor": {
    "Use the tools exposed by your Executor MCP connection.": "oct6Metadata.copy122",
    "Use the provider-hosted connection for the quickest setup.": "oct6Metadata.copy013",
    "Paste your Executor MCP URL. Sign in if required, or add a token or headers under Advanced authentication.": "oct6Metadata.copy123",
    "Connect MCP server": "oct6Metadata.copy015"
  },
  "google": {
    "Connect Google Gemini accounts for your agents.": "oct6Metadata.copy229",
    "Google Gemini API key": "oct6Metadata.copy230",
    "Authenticate an agent with this account.": "sep13AiMetadata.whenToUse",
    "Use your personal account or an explicitly shared company account.": "sep13AiMetadata.guidance",
    "API key": "localizationApps.metadata7",
    "Enter API key": "sep13AiMetadata.apiKeyPlaceholder"
  },
  "local": {
    "Local endpoint": "oct6Metadata.copy257",
    "Use a local model server in the agent’s execution environment.": "oct6Metadata.copy258",
    "Local endpoint API key": "oct6Metadata.copy259",
    "Use your personal account or an explicitly shared company account.": "sep13AiMetadata.guidance",
    "API key": "localizationApps.metadata7",
    "Enter API key": "sep13AiMetadata.apiKeyPlaceholder"
  },
  "messages-api": {
    "Connect any compatible harness to an Anthropic Messages-compatible provider or gateway.": "oct6Metadata.copy272",
    "Messages API API key": "oct6Metadata.copy273",
    "Use your personal account or an explicitly shared company account.": "sep13AiMetadata.guidance",
    "API key": "localizationApps.metadata7",
    "Enter API key": "sep13AiMetadata.apiKeyPlaceholder"
  },
  "microsoft-teams": {
    "Let people start and continue Paperclip work with an agent from Microsoft Teams.": "oct6Metadata.copy275",
    "Chat with an agent": "communityPhoton.metadataMethod",
    "Let people in Microsoft Teams start and continue work with one Paperclip agent.": "oct6Metadata.copy276",
    "Application / Client ID": "chatUi.chatEndpointSetup.applicationClientID",
    "Directory / Tenant ID": "chatUi.chatEndpointSetup.directoryTenantID",
    "Client secret": "localizationConnections.clientSecret117",
    "Paste the client-secret value": "oct6Metadata.copy281",
    "Use a Microsoft 365 work or school organization where you can register an Entra app, create a single-tenant Azure Bot, and upload or install a Teams app. Personal or free Teams accounts at teams.live.com cannot complete this setup. Enable personal, team, and groupChat bot scopes and the ChannelMessage.Read.Group and ChatMessage.Read.Chat resource-specific application permissions. Those RSC grants let an installed app receive every message in a team or group chat without an @mention, so explain that access to installers. One team install covers its standard channels; private and shared channels require a separate installation and are not supported by this release.": "oct6Metadata.copy282"
  },
  "railway": {
    "Inspect services and logs, deploy applications, and run commands in your Railway containers.": "oct6Metadata.copy330",
    "Authorize your Railway account in the browser.": "oct6Metadata.copy331",
    "Sign in to Railway and select the workspaces your agents may use. Paperclip adds direct service, deployment, and bounded log tools when Railway accepts the connection for API access. Container commands require the separate SSH setup on the connection. Project tokens are not supported by Railway's hosted connection.": "oct6Metadata.copy332",
    "Connect Railway": "oct6Metadata.copy333",
    "Railway enforces the workspaces selected at consent. Selected actions start Allowed; choose Ask first for operations you want to approve.": "oct6Metadata.copy334",
    "Logs and container commands can expose application data and secrets. Grant access only to agents trusted with the selected services.": "oct6Metadata.copy335",
    "The general Railway agent and committing staged changes are unavailable because their internal changes cannot be individually reviewed in Paperclip.": "oct6Metadata.copy336",
    "Live Railway qualification is pending. If Railway rejects API access, reconnect with the required permissions; Paperclip never falls back to another credential.": "oct6Metadata.copy337"
  },
  "responses-api": {
    "Connect any compatible harness to an OpenAI Responses-compatible provider or gateway, including Emissary.": "oct6Metadata.copy346",
    "Responses API API key": "oct6Metadata.copy347",
    "Use your personal account or an explicitly shared company account.": "sep13AiMetadata.guidance",
    "API key": "localizationApps.metadata7",
    "Enter API key": "sep13AiMetadata.apiKeyPlaceholder"
  },
  "supermemory": {
    "Search and save shared memories, documents, and profiles.": "oct6Metadata.copy398",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Sign in to Supermemory, then choose a workspace, read or write access, and optional tags. Use a separate space for unrelated work.": "oct6Metadata.copy399",
    "Sign in with Supermemory": "oct6Metadata.copy400",
    "Sign in to Supermemory and select the spaces this connection may access. The hosted MCP uses OAuth, not a developer API key.": "oct6Metadata.copy401"
  },
  "telegram": {
    "Let people start and continue Paperclip work with an agent from Telegram.": "oct6Metadata.copy403",
    "Chat with an agent": "communityPhoton.metadataMethod",
    "Let people in Telegram start and continue work with one Paperclip agent.": "oct6Metadata.copy404",
    "Bot token": "chatUi.chatEndpointSetup.botToken",
    "Create one dedicated bot with BotFather, then connect its token to the public Paperclip webhook endpoint.": "oct6Metadata.copy406"
  },
  "zep": {
    "Retrieve temporal graph memory and authorized business context.": "oct6Metadata.copy447",
    "Use browser sign-in for the provider-hosted MCP server.": "oct5Metadata.providerBrowserSignIn",
    "Sign in with the work identity configured for your Zep project's Memory MCP server. Zep restricts access to that identity's memory and authorized shared graphs.": "oct6Metadata.copy448",
    "Sign in with Zep": "oct6Metadata.copy449",
    "A Zep project with Memory MCP enabled, available MCP seats, and Google Workspace or enterprise OIDC configured by its administrator. Project API keys do not authenticate Memory MCP.": "oct6Metadata.copy450"
  }
};
