import { vi } from "vitest";

const serverModuleMocks = [
  "@paperclipai/db",
  "@paperclipai/shared",
  "@paperclipai/adapter-utils",
  "drizzle-orm",
  "../errors.js",
  "../errors.ts",
  "../middleware/index.js",
  "../middleware/index.ts",
  "../middleware/logger.js",
  "../middleware/logger.ts",
  "../middleware/validate.js",
  "../middleware/validate.ts",
  "../routes/access.js",
  "../routes/access.ts",
  "../routes/activity.js",
  "../routes/activity.ts",
  "../routes/adapters.js",
  "../routes/adapters.ts",
  "../routes/agents.js",
  "../routes/agents.ts",
  "../routes/companies.js",
  "../routes/companies.ts",
  "../routes/company-rollouts.js",
  "../routes/company-rollouts.ts",
  "../routes/instance-settings.js",
  "../routes/instance-settings.ts",
  "../routes/issues.js",
  "../routes/issues.ts",
  "../routes/project-quick-links.js",
  "../routes/project-quick-links.ts",
  "../routes/projects.js",
  "../routes/projects.ts",
  "../routes/routines.js",
  "../routes/routines.ts",
  "../routes/sidebar-preferences.js",
  "../routes/sidebar-preferences.ts",
  "../services/index.js",
  "../services/index.ts",
  "../services/issue-assignment-wakeup.js",
  "../services/issue-assignment-wakeup.ts",
  "../services/issue-execution-policy.js",
  "../services/issue-execution-policy.ts",
  "../services/issues-checkout-wakeup.js",
  "../services/issues-checkout-wakeup.ts",
  "../services/project-quick-link-preview.js",
  "../services/project-quick-link-preview.ts",
  "../services/project-quick-links.js",
  "../services/project-quick-links.ts",
  "../routes/workspace-command-authz.js",
  "../routes/workspace-command-authz.ts",
  "../utils/attachment-types.js",
  "../utils/attachment-types.ts",
] as const;

vi.resetModules();
for (const moduleId of serverModuleMocks) {
  vi.doUnmock(moduleId);
}
