import { MarkdownBody } from "../components/MarkdownBody";
import { ScrollArea } from "@/components/ui/scroll-area";
import { FileText } from "lucide-react";

const TERMS_OF_SERVICE = `
# Terms of Service

**Version:** v0.2
**Effective Date:** April 1, 2026
**Last Updated:** April 3, 2026

These Terms of Service ("Terms") govern your access to and use of IronWorks, an AI workforce orchestration platform ("Service") operated by Steel Motion LLC ("Steel Motion," "we," "us," "our"). By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.

## 1. Service Description

IronWorks is a platform that enables businesses to deploy, manage, and orchestrate AI agents for business operations. The Service provides tools for agent management, task automation, project tracking, approval workflows, and related functionality.

Steel Motion provides the platform infrastructure only. You are responsible for configuring your AI agents and providing the necessary third-party API keys to power them.

## 2. Account Terms

### 2.1 Account Registration
To use the Service, you must create an account. You agree to provide accurate, current, and complete information during registration.

### 2.2 One Account Per Person
Each individual user must maintain only one account. Shared accounts are not permitted. Organizations may have multiple individual user accounts under a single company workspace.

### 2.3 Account Security
You are responsible for safeguarding your account credentials and for all activity that occurs under your account. You must notify us immediately at legal@steelmotionllc.com if you become aware of any unauthorized use of your account.

### 2.4 Age Requirement
You must be at least 18 years of age to use the Service. By using the Service, you represent and warrant that you meet this requirement.

## 3. Billing and Payment

### 3.1 Subscription Plans
The Service is offered on a subscription basis. Plan details, pricing, and feature availability are described on our pricing page and may be updated from time to time.

### 3.2 Payment Processing
All payments are processed securely through Stripe. By subscribing, you authorize Steel Motion to charge your payment method on file for recurring subscription fees.

### 3.3 Auto-Renewal
Subscriptions automatically renew at the end of each billing period unless you cancel before the renewal date. You will be charged the then-current rate for your plan at each renewal.

### 3.4 Refunds
Subscription fees are non-refundable except where required by applicable law. If you cancel mid-cycle, you retain access through the end of the current billing period.

### 3.5 Taxes
You are responsible for all applicable taxes. Subscription fees are exclusive of taxes unless otherwise stated.

## 4. Bring Your Own Key (BYOK)

### 4.1 Third-Party API Keys
The Service operates on a "Bring Your Own Key" (BYOK) model. You must provide your own API keys for third-party AI model providers (such as Anthropic, OpenAI, Google, and others) to power your AI agents.

### 4.2 Third-Party Charges
Steel Motion is not responsible for any charges, fees, or costs incurred from your use of third-party AI model providers. Your use of third-party services is governed by their respective terms of service and pricing.

### 4.3 Key Security
Your API keys are encrypted at rest using AES-256 encryption. Steel Motion does not access, read, or use your API keys for any purpose other than executing API calls on your behalf as directed by your agent configurations.

### 4.4 Platform Fee
Steel Motion charges a platform fee only for the use of IronWorks infrastructure, tooling, and orchestration capabilities. The platform fee is separate from and does not include any third-party provider costs.

## 5. AI Agent Disclaimers

### 5.1 Software Platform Only
IronWorks is a software platform that enables users to create, configure, and manage AI agents. Steel Motion provides the platform infrastructure and tooling only. Steel Motion does not provide legal, financial, medical, tax, engineering, compliance, or any other form of professional advice or services.

### 5.2 No Professional Advice
The AI agents available through IronWorks - including agents with titles or roles such as "Legal Counsel," "CFO," "CTO," "HR Director," or any other professional designation - are software tools, not licensed professionals. The use of professional titles for AI agents is solely for organizational purposes within the platform and does not create any professional-client relationship between you and Steel Motion. All AI agent outputs, recommendations, analyses, documents, and work products are generated by third-party large language models and are provided strictly for informational and assistive purposes. They do not constitute professional advice of any kind.

### 5.3 AI Outputs Are Not Reliable
AI agents are powered by probabilistic machine learning models that can and do produce errors, omissions, inaccuracies, hallucinations, and misleading content. AI-generated outputs may appear authoritative or confident while being factually incorrect. Steel Motion makes no representations or warranties regarding the accuracy, completeness, reliability, currentness, or suitability of any AI-generated output for any purpose.

### 5.4 User Responsibility for AI Outputs
YOU ARE SOLELY RESPONSIBLE FOR:

- Reviewing, verifying, and validating all AI agent outputs before relying on or acting upon them
- Making all final decisions based on your own judgment, expertise, and consultation with qualified human professionals
- Ensuring your use of AI agents and their outputs complies with all applicable laws, regulations, industry standards, and professional requirements
- All consequences, damages, losses, or liabilities resulting from actions taken or decisions made based on AI agent outputs
- Ensuring appropriate human oversight and review of all AI agent activity, particularly for high-stakes or regulated activities
- Determining the suitability of AI agent outputs for your specific use case and regulatory obligations

### 5.5 No Reliance
You agree that you will not rely on AI agent outputs as the sole basis for any decision, action, regulatory filing, legal determination, financial transaction, medical decision, or any other activity where errors could result in harm, loss, or liability. You must independently verify all AI-generated information before use.

### 5.6 Third-Party LLM Providers
AI agents operate using third-party large language model providers (such as Anthropic, OpenAI, Google, and others) through API keys that you provide. Steel Motion does not control, audit, or guarantee the behavior, accuracy, availability, or safety of these third-party models. Your use of third-party LLM providers is subject to those providers' own terms of service, acceptable use policies, and privacy policies. You are responsible for ensuring your use of these providers complies with their terms and all applicable law.

## 6. Data Ownership

### 6.1 Your Data
You retain all ownership rights to data you upload, create, or generate through the Service ("Your Data"). Steel Motion does not claim ownership of Your Data.

### 6.2 Data Processing Role
Steel Motion acts as a data processor on your behalf. You are the data controller. We process Your Data only as necessary to provide the Service and as described in our [Privacy Policy](/privacy) and [Data Processing Agreement](/dpa).

### 6.3 Data Portability
You may export Your Data at any time through the export functionality provided in the Service.

## 7. Intellectual Property

### 7.1 Agent Output
You retain all intellectual property rights in any content, work product, or output created by your AI agents through the Service ("Agent Output"). Steel Motion claims no ownership of Agent Output. However, you acknowledge that AI-generated content may not be eligible for intellectual property protection in all jurisdictions, and Steel Motion makes no representation regarding the protectability of Agent Output.

### 7.2 Service IP
Steel Motion retains all rights, title, and interest in and to the Service, including all software, designs, documentation, and related intellectual property. These Terms do not grant you any rights to Steel Motion's intellectual property except the limited right to use the Service as described herein.

### 7.3 Feedback
If you provide feedback, suggestions, or ideas about the Service, you grant Steel Motion a non-exclusive, royalty-free, perpetual, irrevocable license to use that feedback for any purpose without obligation to you.

## 8. Acceptable Use

Your use of the Service is subject to our [Acceptable Use Policy](/aup). Violation of the AUP may result in immediate suspension or termination of your account.

## 9. Warranties Disclaimer

THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY. STEEL MOTION DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ANY WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE.

STEEL MOTION DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE. WE DO NOT GUARANTEE THE ACCURACY, RELIABILITY, OR COMPLETENESS OF ANY AI-GENERATED OUTPUT. AI AGENT OUTPUTS ARE GENERATED BY THIRD-PARTY MACHINE LEARNING MODELS AND MAY CONTAIN ERRORS, OMISSIONS, INACCURACIES, HALLUCINATIONS, OR MISLEADING INFORMATION. YOU USE ALL AI-GENERATED OUTPUTS AT YOUR OWN RISK.

STEEL MOTION DOES NOT WARRANT THAT AI AGENTS WILL PERFORM AS EXPECTED, PRODUCE CORRECT RESULTS, OR COMPLY WITH ANY SPECIFIC REGULATORY, LEGAL, OR PROFESSIONAL STANDARDS. THE INCLUSION OF SPECIALIZED AGENT ROLES (SUCH AS "LEGAL COUNSEL," "CFO," "CTO," OR SIMILAR TITLES) DOES NOT INDICATE THAT THE SERVICE PROVIDES PROFESSIONAL SERVICES OR ADVICE OF ANY KIND.

## 10. Limitation of Liability

### 10.1 Liability Cap
TO THE MAXIMUM EXTENT PERMITTED BY LAW, STEEL MOTION'S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE TOTAL AMOUNT OF FEES PAID BY YOU TO STEEL MOTION IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR ONE HUNDRED DOLLARS ($100.00), WHICHEVER IS GREATER.

### 10.2 Exclusion of Damages
IN NO EVENT SHALL STEEL MOTION BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, BUSINESS OPPORTUNITIES, OR GOODWILL, REGARDLESS OF THE CAUSE OF ACTION OR THE THEORY OF LIABILITY, EVEN IF STEEL MOTION HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

### 10.3 AI-Specific Liability Exclusions
WITHOUT LIMITING THE FOREGOING, STEEL MOTION SHALL NOT BE LIABLE FOR ANY DAMAGES, LOSSES, OR LIABILITIES ARISING FROM: (A) THE ACCURACY, COMPLETENESS, OR RELIABILITY OF ANY AI-GENERATED OUTPUT; (B) DECISIONS MADE OR ACTIONS TAKEN BASED ON AI AGENT OUTPUTS; (C) REGULATORY PENALTIES, FINES, OR LEGAL CONSEQUENCES RESULTING FROM RELIANCE ON AI-GENERATED CONTENT; (D) THIRD-PARTY CLAIMS ARISING FROM YOUR USE OF AI AGENT OUTPUTS; OR (E) ANY FAILURE OF AI AGENTS TO MEET YOUR EXPECTATIONS OR REQUIREMENTS.

### 10.4 Third-Party Services
Steel Motion is not liable for any damages, costs, or losses arising from your use of third-party services, including AI model providers whose API keys you use with the Service. This includes but is not limited to charges incurred on your API keys, data processed by third-party providers, and any actions taken by third-party models.

### 10.5 Risk Allocation
The limitations of liability and exclusions of damages in this section reflect a fair and reasonable allocation of risk between the parties. This allocation is an essential element of the basis of the bargain between you and Steel Motion. The Service would not be provided without these limitations.

## 11. Indemnification

You agree to indemnify and hold harmless Steel Motion, its officers, directors, employees, and agents from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising from: (a) your use of the Service; (b) your violation of these Terms or the AUP; (c) content created or generated by your AI agents; (d) your violation of any third party's rights; (e) any third-party claim arising from actions taken or decisions made based on AI agent outputs; or (f) your failure to comply with applicable laws or regulations in connection with your use of AI agents or their outputs.

## 12. Termination

### 12.1 Termination by You
You may terminate your account at any time by providing 30 days' written notice to legal@steelmotionllc.com. You retain access through the end of the notice period.

### 12.2 Termination by Steel Motion
Steel Motion may terminate your account with 30 days' written notice. In the event of an AUP violation, Steel Motion reserves the right to suspend or terminate your account immediately without notice.

### 12.3 Effect of Termination
Upon termination, your right to use the Service ceases immediately (or at the end of the notice period, as applicable). You may export Your Data prior to termination. After termination, Your Data will be deleted in accordance with our [Privacy Policy](/privacy).

### 12.4 Survival
Sections relating to AI agent disclaimers, intellectual property, limitation of liability, indemnification, and governing law survive termination of these Terms.

## 13. Modifications to Terms

Steel Motion may modify these Terms at any time. We will provide at least 30 days' notice of material changes by email or through the Service. Your continued use of the Service after the effective date of any modification constitutes acceptance of the updated Terms.

## 14. Governing Law and Dispute Resolution

### 14.1 Governing Law
These Terms are governed by and construed in accordance with the laws of the State of Texas, United States, without regard to its conflict of law principles.

### 14.2 Dispute Resolution
Any disputes arising from these Terms or the Service shall first be attempted to be resolved through good-faith negotiation. If negotiation fails, disputes shall be resolved in the state or federal courts located in the State of Texas.

## 15. General Provisions

### 15.1 Entire Agreement
These Terms, together with the Privacy Policy, Acceptable Use Policy, Data Processing Agreement, and Service Level Agreement, constitute the entire agreement between you and Steel Motion regarding the Service.

### 15.2 Severability
If any provision of these Terms is held to be unenforceable, the remaining provisions continue in full force and effect.

### 15.3 Waiver
Failure to enforce any provision of these Terms does not constitute a waiver of that provision.

### 15.4 Assignment
You may not assign your rights under these Terms without Steel Motion's prior written consent. Steel Motion may assign its rights without restriction.

## 16. Contact

For questions about these Terms, contact us at:

- **Email:** legal@steelmotionllc.com
- **Company:** Steel Motion LLC
- **Website:** ironworksapp.ai

---

*These Terms of Service apply to the IronWorks platform operated by Steel Motion LLC.*
`;

export function TermsOfService() {
  return (
    <div className="min-h-[100dvh] bg-background">
      <ScrollArea className="h-[100dvh]">
        <div className="max-w-2xl mx-auto px-6 py-12">
          <div className="flex items-center gap-2 mb-6">
            <FileText className="h-5 w-5 text-muted-foreground" />
            <span className="text-sm text-muted-foreground">IronWorks by Steel Motion LLC</span>
          </div>
          <MarkdownBody>{TERMS_OF_SERVICE}</MarkdownBody>
          <div className="mt-12 pt-6 border-t border-border text-xs text-muted-foreground">
            <p>Steel Motion LLC. All rights reserved.</p>
          </div>
        </div>
      </ScrollArea>
    </div>
  );
}
