/**
 * Build a self-contained POSIX shell script that Claude Code's native
 * `hooks.PreToolUse` handler invokes before every `Bash` tool call. The script
 * does its own JSON parsing via `awk`/`sed` so it has no node dependency at
 * runtime — Claude Code shells out to whatever `command` string the
 * `settings.json` hook entry points at, and we want a portable, easy-to-audit
 * handler that lives in the agent's `CLAUDE_CONFIG_DIR` snapshot.
 *
 * The script's behavior matches the gates in `pre-merge-gate.ts`:
 * 1. Allow everything that is NOT a `gh pr merge <PR>` invocation (exit 0).
 * 2. For `gh pr merge <PR>`, fetch the matching Paperclip ticket + active runs
 *    + last comment via the Paperclip API and feed them through the same gate
 *    logic that the TypeScript module encodes.
 * 3. On any gate failure, print the Claude Code JSON shape that signals a deny
 *    and (best-effort) post a `gh pr comment` so the PR timeline records the
 *    abort with the ticket reference.
 *
 * The script is built as string concatenation (NOT a JS template literal) so
 * the bash-side `${...}` substitutions don't get parsed as JS expressions.
 */

export const HOOK_RELATIVE_PATH = ".paperclip-hooks/pre-merge-gate.sh";

export interface PreMergeHookScriptInput {
  /**
   * Absolute path of the script as it will be written inside the seeded
   * `CLAUDE_CONFIG_DIR`. Used by the caller to populate the `command` field of
   * the `settings.json` hook entry.
   */
  scriptPath: string;
}

export function buildPreMergeHookScript(input: PreMergeHookScriptInput): string {
  const scriptPath = input.scriptPath;
  const lines: string[] = [];

  lines.push("#!/usr/bin/env bash");
  lines.push("# Auto-generated by @paperclipai/adapter-claude-local pre-merge gate (Control 3, MGC-2350).");
  lines.push("# Do not edit by hand — regenerate via buildPreMergeHookScript.");
  lines.push("set -u");
  lines.push("");
  lines.push('HOOK_SCRIPT=' + JSON.stringify(scriptPath));
  lines.push("");
  lines.push("read_payload() {");
  lines.push("  awk 'BEGIN{RS=\"\"; ORS=\"\\\\n\"} {print}' || true");
  lines.push("}");
  lines.push("");
  lines.push("parse_command() {");
  lines.push("  printf '%s' \"$1\" | sed -n 's/.*\"command\"[[:space:]]*:[[:space:]]*\"\\([^\"]*\\)\".*/\\1/p' | head -n1");
  lines.push("}");
  lines.push("");
  lines.push('# Match EVERY "gh pr merge <NUMBER>" token across shell wrappers');
  lines.push('# (&&, ;, ||, cd, env). Flags may appear BEFORE or AFTER the PR number');
  lines.push('# (--squash, --delete-branch, --merge, --rebase, --admin, --auto). The');
  lines.push('# extractor splits the command on shell chaining operators and, for');
  lines.push('# every segment that starts with `gh pr merge`, returns the first');
  lines.push('# all-digit token following the subcommand. A compound command like');
  lines.push('# `gh pr merge 459 --squash && gh pr merge 460 --delete-branch` MUST');
  lines.push('# surface BOTH PR numbers so the gate can require every one of them to');
  lines.push('# pass. If any segment has no numeric PR after `gh pr merge`, the');
  lines.push('# extractor returns nothing so the hook falls back to deny-by-default');
  lines.push('# (we never let an unresolvable target through).');
  lines.push("extract_pr_numbers() {");
  lines.push("  local cmd=\"$1\"");
  lines.push("  local segment tail num found=\"\"");
  lines.push("  # Split on shell chaining operators. POSIX shells tolerate empty segments.");
  lines.push("  # shellcheck disable=SC2206");
  lines.push("  local segments");
  lines.push("  IFS=$'&\\n;|'");
  lines.push("  segments=($cmd)");
  lines.push("  unset IFS");
  lines.push("  for segment in \"${segments[@]}\"; do");
  lines.push("    # Drop trailing redirections (`2>&1 > /tmp/x`, `> log`, etc.).");
  lines.push("    segment=\"${segment%%>*}\"");
  lines.push("    # Only consider segments that contain `gh pr merge` followed by");
  lines.push("    # whitespace — `gh-pr-merge` and `ghapr-merge` are filtered.");
  lines.push("    case \"$segment\" in");
  lines.push("      *\"gh pr merge \"*) ;;");
  lines.push("      *) continue ;;");
  lines.push("    esac");
  lines.push("    # Tail after the LAST occurrence of `gh pr merge ` in the segment.");
  lines.push("    tail=\"${segment##*gh pr merge }\"");
  lines.push("    # First standalone numeric token in the tail. The pattern matches");
  lines.push("    # digits bounded by non-identifier characters so URLs like");
  lines.push("    # `pull/460` only match when `460` is its own token (it is not —");
  lines.push("    # the preceding `/` is a separator but the match needs the digit");
  lines.push("    # to be a full token, which `/460` is NOT; we require whitespace or");
  lines.push("    # start-of-string on BOTH sides). To preserve the strict rule from");
  lines.push("    # the TS parser (no URL forms), we additionally reject tails where");
  lines.push("    # the first all-digit token is part of a URL path or branch name.");
  lines.push("    num=$(printf '%s' \"$tail\" | grep -oE '(^|[^A-Za-z0-9_/-])[0-9]+($|[^A-Za-z0-9_/-])' | head -n1 | tr -dc '0-9')");
  lines.push("    if [ -z \"$num\" ]; then");
  lines.push("      # A `gh pr merge` segment with no numeric PR: deny the whole");
  lines.push("      # compound command so callers can't sneak in unmerged PRs.");
  lines.push("      printf '%s' \"\"");
  lines.push("      return 0");
  lines.push("    fi");
  lines.push("    found=\"$found $num\"");
  lines.push("  done");
  lines.push("  printf '%s' \"$found\"");
  lines.push("}");
  lines.push("");
  lines.push("deny() {");
  lines.push("  local reason=\"$1\"");
  lines.push("  local ticket=\"$2\"");
  lines.push("  local pr_for_comment=\"${3:-}\"");
  lines.push("  local safe_reason");
  lines.push("  safe_reason=$(printf '%s' \"$reason\" | sed 's/\"/\\\\\"/g')");
  lines.push("  cat <<JSON");
  lines.push('{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"' + "${safe_reason}" + '"}}');
  lines.push("JSON");
  lines.push("  printf '[paperclip-pre-merge-gate] DENIED %s ticket=%s pr=%s\\\\n' \"$reason\" \"$ticket\" \"$pr_for_comment\" 1>&2");
  lines.push("  if [ -n \"${ticket:-}\" ] && [ -n \"${pr_for_comment:-}\" ]; then");
  lines.push("    gh pr comment \"$pr_for_comment\" --body \"Merge aborted: pre-merge gate check failed — ${ticket}. Reason: ${reason}.\" 1>&2 2>/tmp/pre-merge-gate-err || true");
  lines.push("  fi");
  lines.push("  exit 0  # Claude Code interprets the JSON, not the exit code.");
  lines.push("}");
  lines.push("");
  lines.push("allow() {");
  lines.push("  exit 0");
  lines.push("}");
  lines.push("");
  lines.push("PAYLOAD=$(cat || true)");
  lines.push("COMMAND=$(parse_command \"$PAYLOAD\")");
  lines.push("");
  lines.push("if [ -z \"${COMMAND:-}\" ]; then");
  lines.push("  allow");
  lines.push("fi");
  lines.push("");
  lines.push("# Extract every PR targeted by `gh pr merge` in this command (newline");
  lines.push('# becomes a single space; the loop below walks each one).');
  lines.push("PR_NUMBERS=$(extract_pr_numbers \"$COMMAND\" | tr '\\\\n' ' ')");
  lines.push("");
  lines.push("if [ -z \"${PR_NUMBERS// /}\" ]; then");
  lines.push("  allow");
  lines.push("fi");
  lines.push("");
  lines.push("API_URL=\"${PAPERCLIP_API_URL:-}\"");
  lines.push("API_KEY=\"${PAPERCLIP_API_KEY:-}\"");
  lines.push("AGENT_ID=\"${PAPERCLIP_AGENT_ID:-}\"");
  lines.push("COMPANY_ID=\"${PAPERCLIP_COMPANY_ID:-}\"");
  lines.push("# PAPERCLIP_RUN_ID is set by the harness on every agent invocation. The");
  lines.push("# gate uses it to filter the current run out of the concurrent-run race");
  lines.push('# check so a legitimate merge initiated by THIS run is not denied as a');
  lines.push("# self-conflict.");
  lines.push("RUN_ID=\"${PAPERCLIP_RUN_ID:-}\"");
  lines.push("");
  lines.push("if [ -z \"$API_URL\" ] || [ -z \"$API_KEY\" ]; then");
  lines.push("  printf '[paperclip-pre-merge-gate] missing PAPERCLIP_API_URL/PAPERCLIP_API_KEY; fail-open (allow)\\\\n' 1>&2");
  lines.push("  allow");
  lines.push("fi");
  lines.push("");
  lines.push("API_BASE=\"${API_URL%/}\"");
  lines.push("API_BASE=\"${API_BASE%/api}\"");
  lines.push("");
  lines.push("# Evaluate every PR targeted by the command independently. If ANY PR");
  lines.push("# fails a gate, deny the whole compound command — partial approval is");
  lines.push('# never sufficient for `gh pr merge`.');
  lines.push("for PR_NUMBER in $PR_NUMBERS; do");
  lines.push("  if [ -z \"$PR_NUMBER\" ]; then");
  lines.push("    continue");
  lines.push("  fi");
  lines.push("");
  lines.push("  # Gate #1: find the ticket for this PR.");
  lines.push("  TICKET_JSON=$(curl -fsS --max-time 5 -H \"Authorization: Bearer $API_KEY\" -H \"Accept: application/json\" \"$API_BASE/api/issues?search=PR%23$PR_NUMBER&limit=20\" 2>/tmp/pre-merge-gate-curl || true)");
  lines.push("");
  lines.push("  if [ -z \"${TICKET_JSON:-}\" ]; then");
  lines.push("    deny \"Gate #1 lookup failed (API unreachable or empty result) for PR #${PR_NUMBER}.\" \"<unknown>\" \"$PR_NUMBER\"");
  lines.push("  fi");
  lines.push("");
  lines.push("  TICKET_LINE=$(printf '%s' \"$TICKET_JSON\" | python3 -c \"");
  lines.push("import json,sys");
  lines.push("data=json.load(sys.stdin)");
  lines.push("if not isinstance(data, list):");
  lines.push("    sys.exit(1)");
  lines.push("for issue in data:");
  lines.push("    hay='\\\\n'.join([str(issue.get('title','')), str(issue.get('description',''))])");
  lines.push("    needle_a='PR #'+str(${PR_NUMBER})");
  lines.push("    needle_b='PR#'+str(${PR_NUMBER})");
  lines.push("    if needle_a in hay or needle_b in hay:");
  lines.push("        print(json.dumps({");
  lines.push("            'identifier': issue.get('identifier',''),");
  lines.push("            'status': issue.get('status',''),");
  lines.push("            'assigneeAgentId': issue.get('assigneeAgentId'),");
  lines.push("            'blocked': bool(issue.get('blocked'))");
  lines.push("        }))");
  lines.push("        sys.exit(0)");
  lines.push("sys.exit(1)");
  lines.push("\" 2>/tmp/pre-merge-gate-py || true)");
  lines.push("");
  lines.push("  if [ -z \"${TICKET_LINE:-}\" ]; then");
  lines.push("    deny \"Gate #1 failed: no Paperclip ticket references PR #${PR_NUMBER}.\" \"<unknown>\" \"$PR_NUMBER\"");
  lines.push("  fi");
  lines.push("");
  lines.push("  TICKET_ID=$(printf '%s' \"$TICKET_LINE\" | python3 -c \"import json,sys;print(json.load(sys.stdin)['identifier'])\" 2>/dev/null || true)");
  lines.push("  TICKET_STATUS=$(printf '%s' \"$TICKET_LINE\" | python3 -c \"import json,sys;print(json.load(sys.stdin)['status'])\" 2>/dev/null || true)");
  lines.push("  TICKET_ASSIGNEE=$(printf '%s' \"$TICKET_LINE\" | python3 -c \"import json,sys;print(json.load(sys.stdin).get('assigneeAgentId') or '')\" 2>/dev/null || true)");
  lines.push("  TICKET_BLOCKED=$(printf '%s' \"$TICKET_LINE\" | python3 -c \"import json,sys;print('1' if json.load(sys.stdin).get('blocked') else '0')\" 2>/dev/null || echo \"0\")");
  lines.push("");
  lines.push("  if [ \"$TICKET_STATUS\" != \"in_review\" ]; then");
  lines.push("    deny \"Gate #1 failed: ticket $TICKET_ID status is '$TICKET_STATUS', expected 'in_review'.\" \"$TICKET_ID\" \"$PR_NUMBER\"");
  lines.push("  fi");
  lines.push("");
  lines.push("  if [ \"$TICKET_ASSIGNEE\" != \"cto\" ]; then");
  lines.push("    deny \"Gate #1 failed: ticket $TICKET_ID assignee is '$TICKET_ASSIGNEE', expected 'cto'.\" \"$TICKET_ID\" \"$PR_NUMBER\"");
  lines.push("  fi");
  lines.push("");
  lines.push("  if [ \"$TICKET_BLOCKED\" = \"1\" ]; then");
  lines.push("    deny \"Gate #1 failed: ticket $TICKET_ID is blocked.\" \"$TICKET_ID\" \"$PR_NUMBER\"");
  lines.push("  fi");
  lines.push("");
  lines.push("  # Gate #2: concurrent runs of the same agent. The current run is");
  lines.push("  # filtered out by RUN_ID so the calling process does not block itself.");
  lines.push("  if [ -n \"${AGENT_ID:-}\" ] && [ -n \"${COMPANY_ID:-}\" ]; then");
  lines.push("    RUNS_JSON=$(curl -fsS --max-time 5 -H \"Authorization: Bearer $API_KEY\" -H \"Accept: application/json\" \"$API_BASE/api/companies/$COMPANY_ID/heartbeat-runs?agentId=$AGENT_ID&limit=50&summary=true\" 2>/dev/null || true)");
  lines.push("    if [ -n \"${RUNS_JSON:-}\" ]; then");
  lines.push("      RACE=$(printf '%s' \"$RUNS_JSON\" | python3 -c \"");
  lines.push("import json,sys");
  lines.push("data=json.load(sys.stdin)");
  lines.push("if not isinstance(data, list):");
  lines.push("    sys.exit(1)");
  lines.push("needle_a='PR #'+str(${PR_NUMBER})");
  lines.push("needle_b='PR#'+str(${PR_NUMBER})");
  lines.push("current_run='${RUN_ID}'");
  lines.push("for run in data:");
  lines.push("    state = (run.get('status') or '')");
  lines.push("    if state not in ('queued', 'running'):");
  lines.push("        continue");
  lines.push("    run_id = (run.get('id') or '')");
  lines.push("    if current_run and run_id == current_run:");
  lines.push("        continue");
  lines.push("    nxt = (run.get('nextAction') or '')");
  lines.push("    if needle_a in nxt or needle_b in nxt:");
  lines.push("        print(json.dumps({'id': run_id, 'state': state}))");
  lines.push("        sys.exit(0)");
  lines.push("sys.exit(1)");
  lines.push("\" 2>/dev/null || true)");
  lines.push("      if [ -n \"${RACE:-}\" ]; then");
  lines.push("        RACE_ID=$(printf '%s' \"$RACE\" | python3 -c \"import json,sys;print(json.load(sys.stdin).get('id',''))\" 2>/dev/null || true)");
  lines.push("        deny \"Gate #2 failed: another active run of agent $AGENT_ID (id=$RACE_ID) is already acting on PR #${PR_NUMBER}.\" \"$TICKET_ID\" \"$PR_NUMBER\"");
  lines.push("      fi");
  lines.push("    fi");
  lines.push("  fi");
  lines.push("");
  lines.push("# Gate #3: hold signals in the last ticket comment.");
  lines.push("  COMMENTS_JSON=$(curl -fsS --max-time 5 -H \"Authorization: Bearer $API_KEY\" -H \"Accept: application/json\" \"$API_BASE/api/issues/$TICKET_ID/comments?limit=1\" 2>/dev/null || true)");
  lines.push("  if [ -n \"${COMMENTS_JSON:-}\" ]; then");
  lines.push("    HOLD=$(printf '%s' \"$COMMENTS_JSON\" | python3 -c \"");
  lines.push("import json,sys");
  lines.push("data=json.load(sys.stdin)");
  lines.push("if not isinstance(data, list) or not data:");
  lines.push("    sys.exit(0)");
  lines.push("body=(data[0].get('body') or '').lower()");
  lines.push("if 'no procedo al merge' in body or 'bloqueo pre-merge' in body:");
  lines.push("    print('hold')");
  lines.push("\" 2>/dev/null || true)");
  lines.push("    if [ \"$HOLD\" = \"hold\" ]; then");
  lines.push("      deny \"Gate #3 failed: ticket $TICKET_ID last comment contains 'NO procedo al merge' or 'BLOQUEO pre-merge'.\" \"$TICKET_ID\" \"$PR_NUMBER\"");
  lines.push("    fi");
  lines.push("  fi");
  lines.push("done");
  lines.push("");
  lines.push("allow");

  return lines.join("\n") + "\n";
}