/**
 * Pure-function core for the claude-local pre-merge gate hook (Control 3,
 * post-mortem MGC-2348). This module is intentionally free of side effects so
 * it can be unit-tested without I/O. The shell hook script generated by
 * `pre-merge-gate-script.ts` reads the same primitives from the Paperclip API
 * and feeds them through `evaluatePreMergeGates`.
 */

export interface PreMergeGateInput {
  /** The PR number extracted from the `gh pr merge` command. */
  prNumber: number;
  /** Resolved state of the Paperclip ticket attached to the PR (null when no ticket can be found). */
  ticket: PaperclipTicketSnapshot | null;
  /** All active (non-completed) Paperclip runs for the same agent at evaluation time. */
  activeRuns: PaperclipRunSnapshot[];
  /** Last comment body on the ticket, lower-cased for substring checks. null when the ticket has no comments. */
  lastCommentBody: string | null;
}

export interface PaperclipTicketSnapshot {
  identifier: string;
  status: string;
  assigneeAgentId: string | null;
  blocked: boolean;
}

export interface PaperclipRunSnapshot {
  id: string;
  livenessState: string;
  nextAction: string | null;
}

export type GateResult =
  | { allow: true }
  | { allow: false; reason: string; ticketIdentifier: string | null };

const ASSIGNEE_CTO = "cto";

/**
 * Match the subset of `gh pr merge <PR>` invocations the agent is expected to
 * issue. The agent may prefix the command with `npx`, `cd ... &&`, redirections
 * or other shell constructs, but the `gh pr merge <NUMBER>` token pair must
 * appear verbatim with a positive integer PR number.
 */
export function parseGhPrMergeCommand(command: string): number | null {
  if (typeof command !== "string") return null;
  // Strip leading wrappers and trailing redirections so `cd foo && gh pr merge 460 --squash --delete-branch > /tmp/x` matches.
  const segments = command.split(/&&|;|\|\|/);
  for (const segment of segments) {
    const cleaned = segment.replace(/\s+>\s*.*$/g, "").trim();
    const match = cleaned.match(/^gh\s+pr\s+merge\s+(\d+)\b/);
    if (match) {
      const n = Number(match[1]);
      if (Number.isInteger(n) && n > 0) return n;
    }
  }
  return null;
}

/**
 * Apply the three pre-merge gates described in MGC-2348 §5 Control 3 and
 * approved by CEO in MGC-2350:
 *
 *   1. The Paperclip ticket for the PR must be in `in_review` with
 *      `assigneeAgentId === "cto"` and not blocked.
 *   2. No other run of the same agent may currently be active with a
 *      `nextAction` referencing the same PR number (race condition).
 *   3. The latest ticket comment must not contain a hold signal such as
 *      "NO procedo al merge" or "BLOQUEO pre-merge".
 */
export function evaluatePreMergeGates(input: PreMergeGateInput): GateResult {
  // Gate #1 — ticket state.
  if (!input.ticket) {
    return {
      allow: false,
      reason: "Gate #1 failed: no Paperclip ticket could be resolved for PR #" + input.prNumber + ".",
      ticketIdentifier: null,
    };
  }
  const t = input.ticket;
  if (t.status !== "in_review") {
    return {
      allow: false,
      reason: "Gate #1 failed: ticket " + t.identifier + " status is '" + t.status + "', expected 'in_review'.",
      ticketIdentifier: t.identifier,
    };
  }
  if (t.assigneeAgentId !== ASSIGNEE_CTO) {
    return {
      allow: false,
      reason: "Gate #1 failed: ticket " + t.identifier + " assignee is '" + (t.assigneeAgentId ?? "<none>") + "', expected 'cto'.",
      ticketIdentifier: t.identifier,
    };
  }
  if (t.blocked) {
    return {
      allow: false,
      reason: "Gate #1 failed: ticket " + t.identifier + " is blocked.",
      ticketIdentifier: t.identifier,
    };
  }

  // Gate #2 — concurrent run race.
  for (const run of input.activeRuns) {
    if (run.livenessState === "completed") continue;
    if (!run.nextAction) continue;
    if (run.nextAction.includes("PR #" + input.prNumber) || run.nextAction.includes("PR#" + input.prNumber)) {
      return {
        allow: false,
        reason:
          "Gate #2 failed: another run of the cto agent (id=" + run.id + ", state=" + run.livenessState +
          ") is already acting on PR #" + input.prNumber + ".",
        ticketIdentifier: t.identifier,
      };
    }
  }

  // Gate #3 — last comment hold signal.
  if (input.lastCommentBody) {
    const body = input.lastCommentBody;
    if (body.includes("no procedo al merge") || body.includes("bloqueo pre-merge")) {
      return {
        allow: false,
        reason:
          "Gate #3 failed: ticket " + t.identifier +
          " last comment contains a hold signal ('NO procedo al merge' / 'BLOQUEO pre-merge').",
        ticketIdentifier: t.identifier,
      };
    }
  }

  return { allow: true };
}

/**
 * Search the local Paperclip API for the ticket that owns the given PR. The
 * caller passes the result straight into `evaluatePreMergeGates`. This helper
 * is intentionally tiny (only the three fields the gate needs) so the shell
 * hook script can JSON-encode it without dragging the rest of the ticket
 * payload into the process environment.
 */
export async function fetchTicketForPr(
  apiUrl: string,
  apiKey: string,
  prNumber: number,
  signal?: AbortSignal,
): Promise<PaperclipTicketSnapshot | null> {
  const url = `${apiUrl.replace(/\/+$/, "")}/api/issues?search=${encodeURIComponent("PR #" + prNumber)}&limit=20`;
  const res = await fetch(url, {
    headers: {
      Authorization: `Bearer ${apiKey}`,
      Accept: "application/json",
    },
    signal,
  });
  if (!res.ok) return null;
  const body = (await res.json()) as Array<Record<string, unknown>>;
  for (const issue of body) {
    const title = typeof issue.title === "string" ? issue.title : "";
    const desc = typeof issue.description === "string" ? issue.description : "";
    const haystack = `${title}\n${desc}`;
    if (haystack.includes("PR #" + prNumber) || haystack.includes("PR#" + prNumber)) {
      return {
        identifier: typeof issue.identifier === "string" ? issue.identifier : "",
        status: typeof issue.status === "string" ? issue.status : "",
        assigneeAgentId: typeof issue.assigneeAgentId === "string" ? issue.assigneeAgentId : null,
        blocked: Boolean(issue.blocked),
      };
    }
  }
  return null;
}

/** Fetch the latest comment body for a ticket identifier (e.g. MGC-1234). */
export async function fetchLastCommentBody(
  apiUrl: string,
  apiKey: string,
  issueIdentifier: string,
  signal?: AbortSignal,
): Promise<string | null> {
  const url = `${apiUrl.replace(/\/+$/, "")}/api/issues/${encodeURIComponent(issueIdentifier)}/comments?limit=1`;
  const res = await fetch(url, {
    headers: {
      Authorization: `Bearer ${apiKey}`,
      Accept: "application/json",
    },
    signal,
  });
  if (!res.ok) return null;
  const body = (await res.json()) as Array<{ body?: unknown }> | unknown;
  if (!Array.isArray(body) || body.length === 0) return null;
  const first = body[0];
  return typeof first.body === "string" ? first.body.toLowerCase() : null;
}

/** List all non-completed runs for a given agent. */
export async function fetchActiveAgentRuns(
  apiUrl: string,
  apiKey: string,
  agentId: string,
  signal?: AbortSignal,
): Promise<PaperclipRunSnapshot[]> {
  const url = `${apiUrl.replace(/\/+$/, "")}/api/agents/${encodeURIComponent(agentId)}/runs?livenessState=active&limit=50`;
  const res = await fetch(url, {
    headers: {
      Authorization: `Bearer ${apiKey}`,
      Accept: "application/json",
    },
    signal,
  });
  if (!res.ok) return [];
  const body = (await res.json()) as Array<Record<string, unknown>>;
  const out: PaperclipRunSnapshot[] = [];
  for (const run of body) {
    out.push({
      id: typeof run.id === "string" ? run.id : "",
      livenessState: typeof run.livenessState === "string" ? run.livenessState : "",
      nextAction: typeof run.nextAction === "string" ? run.nextAction : null,
    });
  }
  return out;
}