/**
 * Build a self-contained POSIX shell script that Claude Code's native
 * `hooks.PreToolUse` handler invokes before every `Bash` tool call. The script
 * does its own JSON parsing via `awk`/`sed` so it has no node dependency at
 * runtime — Claude Code shells out to whatever `command` string the
 * `settings.json` hook entry points at, and we want a portable, easy-to-audit
 * handler that lives in the agent's `CLAUDE_CONFIG_DIR` snapshot.
 *
 * The script's behavior matches the gates in `pre-merge-gate.ts`:
 * 1. Allow everything that is NOT a `gh pr merge <PR>` invocation (exit 0).
 * 2. For `gh pr merge <PR>`, fetch the matching Paperclip ticket + active runs
 *    + last comment via the Paperclip API and feed them through the same gate
 *    logic that the TypeScript module encodes.
 * 3. On any gate failure, print the Claude Code JSON shape that signals a deny
 *    and (best-effort) post a `gh pr comment` so the PR timeline records the
 *    abort with the ticket reference.
 *
 * The script is built as string concatenation (NOT a JS template literal) so
 * the bash-side `${...}` substitutions don't get parsed as JS expressions.
 */

export const HOOK_RELATIVE_PATH = ".paperclip-hooks/pre-merge-gate.sh";

export interface PreMergeHookScriptInput {
  /**
   * Absolute path of the script as it will be written inside the seeded
   * `CLAUDE_CONFIG_DIR`. Used by the caller to populate the `command` field of
   * the `settings.json` hook entry.
   */
  scriptPath: string;
}

export function buildPreMergeHookScript(input: PreMergeHookScriptInput): string {
  const scriptPath = input.scriptPath;
  const lines: string[] = [];

  lines.push("#!/usr/bin/env bash");
  lines.push("# Auto-generated by @paperclipai/adapter-claude-local pre-merge gate (Control 3, MGC-2350).");
  lines.push("# Do not edit by hand — regenerate via buildPreMergeHookScript.");
  lines.push("set -u");
  lines.push("");
  lines.push('HOOK_SCRIPT=' + JSON.stringify(scriptPath));
  lines.push("");
  lines.push("read_payload() {");
  lines.push("  awk 'BEGIN{RS=\"\"; ORS=\"\\\\n\"} {print}' || true");
  lines.push("}");
  lines.push("");
  lines.push("parse_command() {");
  lines.push("  printf '%s' \"$1\" | sed -n 's/.*\"command\"[[:space:]]*:[[:space:]]*\"\\\\([^\"]*\\\\)\".*/\\\\1/p' | head -n1");
  lines.push("}");
  lines.push("");
  lines.push('# Match "gh pr merge <NUMBER>" tokens across shell wrappers (&&, ;, ||, cd, env).');
  lines.push("extract_pr_number() {");
  lines.push("  printf '%s' \"$1\" | grep -oE '(^|[^A-Za-z0-9_])gh[[:space:]]+pr[[:space:]]+merge[[:space:]]+[0-9]+' | head -n1 | grep -oE '[0-9]+$'");
  lines.push("}");
  lines.push("");
  lines.push("deny() {");
  lines.push("  local reason=\"$1\"");
  lines.push("  local ticket=\"$2\"");
  lines.push("  local safe_reason");
  lines.push("  safe_reason=$(printf '%s' \"$reason\" | sed 's/\"/\\\\\"/g')");
  lines.push("  cat <<JSON");
  lines.push('{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"' + "${safe_reason}" + '"}}');
  lines.push("JSON");
  lines.push("  printf '[paperclip-pre-merge-gate] DENIED %s ticket=%s\\\\n' \"$reason\" \"$ticket\" 1>&2");
  lines.push("  if [ -n \"${ticket:-}\" ] && [ -n \"${PR_NUMBER:-}\" ]; then");
  lines.push("    gh pr comment \"$PR_NUMBER\" --body \"Merge aborted: pre-merge gate check failed — ${ticket}. Reason: ${reason}.\" 1>&2 2>/tmp/pre-merge-gate-err || true");
  lines.push("  fi");
  lines.push("  exit 0  # Claude Code interprets the JSON, not the exit code.");
  lines.push("}");
  lines.push("");
  lines.push("allow() {");
  lines.push("  exit 0");
  lines.push("}");
  lines.push("");
  lines.push("PAYLOAD=$(cat || true)");
  lines.push("COMMAND=$(parse_command \"$PAYLOAD\")");
  lines.push("");
  lines.push("if [ -z \"${COMMAND:-}\" ]; then");
  lines.push("  allow");
  lines.push("fi");
  lines.push("");
  lines.push("PR_NUMBER=$(extract_pr_number \"$COMMAND\")");
  lines.push("");
  lines.push("if [ -z \"${PR_NUMBER:-}\" ]; then");
  lines.push("  allow");
  lines.push("fi");
  lines.push("");
  lines.push("API_URL=\"${PAPERCLIP_API_URL:-}\"");
  lines.push("API_KEY=\"${PAPERCLIP_API_KEY:-}\"");
  lines.push("AGENT_ID=\"${PAPERCLIP_AGENT_ID:-}\"");
  lines.push("");
  lines.push("if [ -z \"$API_URL\" ] || [ -z \"$API_KEY\" ]; then");
  lines.push("  printf '[paperclip-pre-merge-gate] missing PAPERCLIP_API_URL/PAPERCLIP_API_KEY; fail-open (allow)\\\\n' 1>&2");
  lines.push("  allow");
  lines.push("fi");
  lines.push("");
  lines.push("API_BASE=\"${API_URL%/}\"");
  lines.push("API_BASE=\"${API_BASE%/api}\"");
  lines.push("");
  lines.push("# Gate #1: find the ticket for this PR.");
  lines.push("TICKET_JSON=$(curl -fsS --max-time 5 -H \"Authorization: Bearer $API_KEY\" -H \"Accept: application/json\" \"$API_BASE/api/issues?search=PR%23$PR_NUMBER&limit=20\" 2>/tmp/pre-merge-gate-curl || true)");
  lines.push("");
  lines.push("if [ -z \"${TICKET_JSON:-}\" ]; then");
  lines.push("  deny \"Gate #1 lookup failed (API unreachable or empty result)\" \"<unknown>\"");
  lines.push("fi");
  lines.push("");
  lines.push("TICKET_LINE=$(printf '%s' \"$TICKET_JSON\" | python3 -c \"");
  lines.push("import json,sys");
  lines.push("data=json.load(sys.stdin)");
  lines.push("for issue in data:");
  lines.push("    hay='\\\\n'.join([str(issue.get('title','')), str(issue.get('description',''))])");
  lines.push("    needle_a='PR #'+str(${PR_NUMBER})");
  lines.push("    needle_b='PR#'+str(${PR_NUMBER})");
  lines.push("    if needle_a in hay or needle_b in hay:");
  lines.push("        print(json.dumps({");
  lines.push("            'identifier': issue.get('identifier',''),");
  lines.push("            'status': issue.get('status',''),");
  lines.push("            'assigneeAgentId': issue.get('assigneeAgentId'),");
  lines.push("            'blocked': bool(issue.get('blocked'))");
  lines.push("        }))");
  lines.push("        sys.exit(0)");
  lines.push("sys.exit(1)");
  lines.push("\" 2>/tmp/pre-merge-gate-py || true)");
  lines.push("");
  lines.push("if [ -z \"${TICKET_LINE:-}\" ]; then");
  lines.push("  deny \"Gate #1 failed: no Paperclip ticket references PR #${PR_NUMBER}.\" \"<unknown>\"");
  lines.push("fi");
  lines.push("");
  lines.push("TICKET_ID=$(printf '%s' \"$TICKET_LINE\" | python3 -c \"import json,sys;print(json.load(sys.stdin)['identifier'])\" 2>/dev/null || true)");
  lines.push("TICKET_STATUS=$(printf '%s' \"$TICKET_LINE\" | python3 -c \"import json,sys;print(json.load(sys.stdin)['status'])\" 2>/dev/null || true)");
  lines.push("TICKET_ASSIGNEE=$(printf '%s' \"$TICKET_LINE\" | python3 -c \"import json,sys;print(json.load(sys.stdin).get('assigneeAgentId') or '')\" 2>/dev/null || true)");
  lines.push("TICKET_BLOCKED=$(printf '%s' \"$TICKET_LINE\" | python3 -c \"import json,sys;print('1' if json.load(sys.stdin).get('blocked') else '0')\" 2>/dev/null || echo \"0\")");
  lines.push("");
  lines.push("if [ \"$TICKET_STATUS\" != \"in_review\" ]; then");
  lines.push("  deny \"Gate #1 failed: ticket $TICKET_ID status is '$TICKET_STATUS', expected 'in_review'.\" \"$TICKET_ID\"");
  lines.push("fi");
  lines.push("");
  lines.push("if [ \"$TICKET_ASSIGNEE\" != \"cto\" ]; then");
  lines.push("  deny \"Gate #1 failed: ticket $TICKET_ID assignee is '$TICKET_ASSIGNEE', expected 'cto'.\" \"$TICKET_ID\"");
  lines.push("fi");
  lines.push("");
  lines.push("if [ \"$TICKET_BLOCKED\" = \"1\" ]; then");
  lines.push("  deny \"Gate #1 failed: ticket $TICKET_ID is blocked.\" \"$TICKET_ID\"");
  lines.push("fi");
  lines.push("");
  lines.push("# Gate #2: concurrent runs of the same agent.");
  lines.push("if [ -n \"${AGENT_ID:-}\" ]; then");
  lines.push("  RUNS_JSON=$(curl -fsS --max-time 5 -H \"Authorization: Bearer $API_KEY\" -H \"Accept: application/json\" \"$API_BASE/api/agents/$AGENT_ID/runs?livenessState=active&limit=50\" 2>/dev/null || true)");
  lines.push("  if [ -n \"${RUNS_JSON:-}\" ]; then");
  lines.push("    RACE=$(printf '%s' \"$RUNS_JSON\" | python3 -c \"");
  lines.push("import json,sys");
  lines.push("data=json.load(sys.stdin)");
  lines.push("needle_a='PR #'+str(${PR_NUMBER})");
  lines.push("needle_b='PR#'+str(${PR_NUMBER})");
  lines.push("for run in data:");
  lines.push("    if run.get('livenessState') == 'completed':");
  lines.push("        continue");
  lines.push("    nxt = (run.get('nextAction') or '')");
  lines.push("    if needle_a in nxt or needle_b in nxt:");
  lines.push("        print(json.dumps({'id': run.get('id',''), 'state': run.get('livenessState','')}))");
  lines.push("        sys.exit(0)");
  lines.push("sys.exit(1)");
  lines.push("\" 2>/dev/null || true)");
  lines.push("    if [ -n \"${RACE:-}\" ]; then");
  lines.push("      deny \"Gate #2 failed: another active run of agent $AGENT_ID is already acting on PR #${PR_NUMBER}.\" \"$TICKET_ID\"");
  lines.push("    fi");
  lines.push("  fi");
  lines.push("fi");
  lines.push("");
  lines.push("# Gate #3: hold signals in the last ticket comment.");
  lines.push("COMMENTS_JSON=$(curl -fsS --max-time 5 -H \"Authorization: Bearer $API_KEY\" -H \"Accept: application/json\" \"$API_BASE/api/issues/$TICKET_ID/comments?limit=1\" 2>/dev/null || true)");
  lines.push("if [ -n \"${COMMENTS_JSON:-}\" ]; then");
  lines.push("  HOLD=$(printf '%s' \"$COMMENTS_JSON\" | python3 -c \"");
  lines.push("import json,sys");
  lines.push("data=json.load(sys.stdin)");
  lines.push("if not isinstance(data, list) or not data:");
  lines.push("    sys.exit(0)");
  lines.push("body=(data[0].get('body') or '').lower()");
  lines.push("if 'no procedo al merge' in body or 'bloqueo pre-merge' in body:");
  lines.push("    print('hold')");
  lines.push("\" 2>/dev/null || true)");
  lines.push("  if [ \"$HOLD\" = \"hold\" ]; then");
  lines.push("    deny \"Gate #3 failed: ticket $TICKET_ID last comment contains 'NO procedo al merge' or 'BLOQUEO pre-merge'.\" \"$TICKET_ID\"");
  lines.push("  fi");
  lines.push("fi");
  lines.push("");
  lines.push("allow");

  return lines.join("\n") + "\n";
}