import type { AdapterModel } from "@paperclipai/adapter-utils";

const OPENCLAW_MODEL_IDS = [
  "anthropic/claude-3-5-haiku-20241022",
  "anthropic/claude-3-5-sonnet-20241022",
  "anthropic/claude-haiku-4-20250414",
  "anthropic/claude-sonnet-4-20250514",
  "codex/gpt-5.2",
  "codex/gpt-5.3-codex",
  "codex/gpt-5.4",
  "codex/gpt-5.4-mini",
  "codex/gpt-5.5",
  "ollama/cogito-2.1:671b-cloud",
  "ollama/deepseek-v3.1:671b-cloud",
  "ollama/deepseek-v3.2:cloud",
  "ollama/deepseek-v4-flash:cloud",
  "ollama/deepseek-v4-pro:cloud",
  "ollama/devstral-2:123b-cloud",
  "ollama/devstral-small-2:24b-cloud",
  "ollama/gemini-3-flash-preview:cloud",
  "ollama/gemma3:12b-cloud",
  "ollama/gemma3:27b-cloud",
  "ollama/gemma3:4b-cloud",
  "ollama/gemma4:31b-cloud",
  "ollama/glm-4.6:cloud",
  "ollama/glm-4.7:cloud",
  "ollama/glm-5:cloud",
  "ollama/glm-5.1:cloud",
  "ollama/gpt-oss:120b-cloud",
  "ollama/gpt-oss:20b-cloud",
  "ollama/jaahas/qwen3.5-uncensored:latest",
  "ollama/kimi-k2-thinking:cloud",
  "ollama/kimi-k2:1t-cloud",
  "ollama/kimi-k2.5:cloud",
  "ollama/kimi-k2.6:cloud",
  "ollama/llama3.2:3b",
  "ollama/minimax-m2:cloud",
  "ollama/minimax-m2.1:cloud",
  "ollama/minimax-m2.5:cloud",
  "ollama/minimax-m2.7:cloud",
  "ollama/ministral-3:14b-cloud",
  "ollama/ministral-3:3b-cloud",
  "ollama/ministral-3:8b-cloud",
  "ollama/mistral-large-3:675b-cloud",
  "ollama/nemotron-3-nano:30b-cloud",
  "ollama/nemotron-3-super:cloud",
  "ollama/qwen3-coder-next:cloud",
  "ollama/qwen3-coder:480b-cloud",
  "ollama/qwen3-next:80b-cloud",
  "ollama/qwen3-vl:235b-cloud",
  "ollama/qwen3-vl:235b-instruct-cloud",
  "ollama/qwen3.5:397b-cloud",
  "ollama/qwen3.5:cloud",
  "ollama/rnj-1:8b-cloud",
  "ollama/x/z-image-turbo:latest",
] as const;

export const models: AdapterModel[] = OPENCLAW_MODEL_IDS.map((id) => ({
  id,
  label: id,
}));