import {
  type AnyPgColumn,
  pgTable,
  uuid,
  text,
  integer,
  timestamp,
  jsonb,
  index,
} from "drizzle-orm/pg-core";
import { companies } from "./companies.js";
import { projects } from "./projects.js";

export const agents = pgTable(
  "agents",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    name: text("name").notNull(),
    role: text("role").notNull().default("general"),
    title: text("title"),
    icon: text("icon"),
    status: text("status").notNull().default("idle"),
    reportsTo: uuid("reports_to").references((): AnyPgColumn => agents.id),
    capabilities: text("capabilities"),
    adapterType: text("adapter_type").notNull().default("process"),
    adapterConfig: jsonb("adapter_config").$type<Record<string, unknown>>().notNull().default({}),
    runtimeConfig: jsonb("runtime_config").$type<Record<string, unknown>>().notNull().default({}),
    budgetMonthlyCents: integer("budget_monthly_cents").notNull().default(0),
    spentMonthlyCents: integer("spent_monthly_cents").notNull().default(0),
    pauseReason: text("pause_reason"),
    pausedAt: timestamp("paused_at", { withTimezone: true }),
    permissions: jsonb("permissions").$type<Record<string, unknown>>().notNull().default({}),
    lastHeartbeatAt: timestamp("last_heartbeat_at", { withTimezone: true }),
    metadata: jsonb("metadata").$type<Record<string, unknown>>(),
    employmentType: text("employment_type").notNull().default("full_time"),
    hiredAt: timestamp("hired_at", { withTimezone: true }).defaultNow(),
    hiredByUserId: text("hired_by_user_id"),
    hiredByAgentId: uuid("hired_by_agent_id").references((): AnyPgColumn => agents.id, { onDelete: "set null" }),
    contractEndAt: timestamp("contract_end_at", { withTimezone: true }),
    contractEndCondition: text("contract_end_condition"),
    contractProjectId: uuid("contract_project_id").references((): AnyPgColumn => projects.id, { onDelete: "set null" }),
    contractBudgetCents: integer("contract_budget_cents"),
    contractSpentCents: integer("contract_spent_cents").notNull().default(0),
    terminatedAt: timestamp("terminated_at", { withTimezone: true }),
    terminationReason: text("termination_reason"),
    department: text("department"),
    onboardingContextIds: jsonb("onboarding_context_ids").$type<string[]>().notNull().default([]),
    performanceScore: integer("performance_score"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyStatusIdx: index("agents_company_status_idx").on(table.companyId, table.status),
    companyReportsToIdx: index("agents_company_reports_to_idx").on(table.companyId, table.reportsTo),
    companyEmploymentTypeIdx: index("agents_company_employment_type_idx").on(table.companyId, table.employmentType),
    companyDepartmentIdx: index("agents_company_department_idx").on(table.companyId, table.department),
  }),
);
