import { pgTable, text, timestamp, uuid, jsonb } from "drizzle-orm/pg-core";

export const crewbriefWeightBalance = pgTable("crewbrief_weight_balance", {
  id: uuid("id").primaryKey().defaultRandom(),
  documentId: uuid("document_id").notNull(),
  tripId: text("trip_id").notNull(),
  documentDate: text("document_date"),
  aircraftRegistration: text("aircraft_registration"),
  aircraftType: text("aircraft_type"),
  basicEmptyWeight: text("basic_empty_weight"),
  basicEmptyWeightCg: text("basic_empty_weight_cg"),
  basicEmptyWeightMoment: text("basic_empty_weight_moment"),
  operatingEmptyWeight: text("operating_empty_weight"),
  operatingEmptyWeightCg: text("operating_empty_weight_cg"),
  operatingEmptyWeightMoment: text("operating_empty_weight_moment"),
  maxRampWeight: text("max_ramp_weight"),
  maxTakeoffWeight: text("max_takeoff_weight"),
  maxLandingWeight: text("max_landing_weight"),
  maxZeroFuelWeight: text("max_zero_fuel_weight"),
  zeroFuelWeight: text("zero_fuel_weight"),
  zeroFuelWeightCg: text("zero_fuel_weight_cg"),
  zeroFuelWeightMoment: text("zero_fuel_weight_moment"),
  rampWeight: text("ramp_weight"),
  takeoffWeight: text("takeoff_weight"),
  takeoffWeightCg: text("takeoff_weight_cg"),
  takeoffWeightMoment: text("takeoff_weight_moment"),
  landingWeight: text("landing_weight"),
  landingWeightCg: text("landing_weight_cg"),
  landingWeightMoment: text("landing_weight_moment"),
  fuelUnit: text("fuel_unit"),
  fuelRamp: text("fuel_ramp"),
  fuelTrip: text("fuel_trip"),
  fuelContingency: text("fuel_contingency"),
  fuelAlternate: text("fuel_alternate"),
  fuelFinalReserve: text("fuel_final_reserve"),
  fuelTaxi: text("fuel_taxi"),
  payload: text("payload"),
  passengerCount: text("passenger_count"),
  passengerWeight: text("passenger_weight"),
  cargoWeight: text("cargo_weight"),
  baggageWeight: text("baggage_weight"),
  crewCount: text("crew_count"),
  crewWeight: text("crew_weight"),
  stations: jsonb("stations"),
  rawExtraction: jsonb("raw_extraction"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
