import fs from "node:fs";
import { randomBytes } from "node:crypto";
import { parse as parseEnvFileContents } from "dotenv";
import { updateEnvFileContents, writeEnvFileAtomicallyIfChanged } from "@paperclipai/shared/env-file";
import { resolvePaperclipEnvPath } from "./paths.js";

const JWT_SECRET_ENV_KEY = "PAPERCLIP_AGENT_JWT_SECRET";

export type EnsureLocalAgentJwtSecretOutcome =
  /** A secret was already live in the process environment. */
  | { status: "present"; source: "process_env" }
  /** A secret existed in the env file but the process had not loaded it. */
  | { status: "loaded"; source: "env_file"; envFilePath: string }
  /** No secret existed anywhere, so one was generated and persisted. */
  | { status: "created"; source: "generated"; envFilePath: string }
  /** A secret is absent and this deployment must not self-provision one. */
  | { status: "absent"; reason: "not_local_trusted" }
  /** Provisioning was attempted and failed; the caller must surface this. */
  | { status: "failed"; envFilePath: string; error: Error };

function isNonEmpty(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function readSecretFromEnvFile(envFilePath: string): string | null {
  if (!fs.existsSync(envFilePath)) return null;
  try {
    const parsed = parseEnvFileContents(fs.readFileSync(envFilePath, "utf-8"));
    const value = parsed[JWT_SECRET_ENV_KEY];
    return isNonEmpty(value) ? value.trim() : null;
  } catch {
    return null;
  }
}

/**
 * Guarantee that this process can mint local agent run tokens.
 *
 * `createLocalAgentJwt` returns null when neither `PAPERCLIP_AGENT_JWT_SECRET`
 * nor `BETTER_AUTH_SECRET` is set, and the heartbeat treats that as a warning
 * and spawns the run anyway. The consequence is not "the run has no token": on
 * `local_trusted` an unauthenticated request is assigned the board principal
 * with `isInstanceAdmin: true`, so every agent on a secretless install runs
 * with a *higher* privilege than an authenticated one, and every write it makes
 * is recorded as the board user rather than as the agent. A missing secret is
 * therefore a silent privilege escalation, not a missing feature.
 *
 * `local_trusted` is a single-user machine-local deployment, so generating and
 * persisting a secret on first start is safe and is what `paperclipai onboard`
 * already does. Doing it here as well means a server started without onboarding
 * — the common path for a clone-and-run install — converges on the same state
 * instead of silently degrading.
 *
 * `authenticated` mode is deliberately not self-provisioned: it already refuses
 * to boot without `BETTER_AUTH_SECRET`, and inventing a signing key for a
 * multi-user deployment would hide a real misconfiguration.
 */
export function ensureLocalAgentJwtSecret(input: {
  deploymentMode: string;
  envFilePath?: string;
}): EnsureLocalAgentJwtSecretOutcome {
  if (
    isNonEmpty(process.env.PAPERCLIP_AGENT_JWT_SECRET)
    || isNonEmpty(process.env.BETTER_AUTH_SECRET)
  ) {
    return { status: "present", source: "process_env" };
  }

  const envFilePath = input.envFilePath ?? resolvePaperclipEnvPath();

  const fromFile = readSecretFromEnvFile(envFilePath);
  if (fromFile) {
    process.env[JWT_SECRET_ENV_KEY] = fromFile;
    return { status: "loaded", source: "env_file", envFilePath };
  }

  if (input.deploymentMode !== "local_trusted") {
    return { status: "absent", reason: "not_local_trusted" };
  }

  const secret = randomBytes(32).toString("hex");
  try {
    const previousContents = fs.existsSync(envFilePath)
      ? fs.readFileSync(envFilePath, "utf-8")
      : null;
    const baseContents = previousContents
      ?? "# Paperclip environment variables\n# Generated by the Paperclip server\n\n";
    writeEnvFileAtomicallyIfChanged(
      envFilePath,
      previousContents,
      updateEnvFileContents(baseContents, { [JWT_SECRET_ENV_KEY]: secret }),
    );
  } catch (error) {
    return {
      status: "failed",
      envFilePath,
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }

  // Set the live value even though the write succeeded above: the process must
  // be able to mint tokens for runs spawned during this boot, not only after a
  // restart re-reads the file.
  process.env[JWT_SECRET_ENV_KEY] = secret;
  return { status: "created", source: "generated", envFilePath };
}
