import { readConfigFile } from "./config-file.js";
import { execFileSync } from "node:child_process";
import { existsSync, realpathSync, writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { randomBytes } from "node:crypto";
import { config as loadDotenv, parse as parseDotenv } from "dotenv";
import { resolvePaperclipEnvPath } from "./paths.js";
import { maybeRepairLegacyWorktreeConfigAndEnvFiles } from "./worktree-config.js";
import {
  AUTH_BASE_URL_MODES,
  BIND_MODES,
  DEPLOYMENT_EXPOSURES,
  DEPLOYMENT_MODES,
  SECRET_PROVIDERS,
  STORAGE_PROVIDERS,
  type BindMode,
  type AuthBaseUrlMode,
  type DeploymentExposure,
  type DeploymentMode,
  type SecretProvider,
  type StorageProvider,
  inferBindModeFromHost,
  resolveRuntimeBind,
  validateConfiguredBindMode,
} from "@paperclipai/shared";
import {
  resolveDefaultBackupDir,
  resolveDefaultEmbeddedPostgresDir,
  resolveDefaultSecretsKeyFilePath,
  resolveDefaultStorageDir,
  resolveHomeAwarePath,
} from "./home-paths.js";

const PAPERCLIP_ENV_FILE_PATH = resolvePaperclipEnvPath();
if (existsSync(PAPERCLIP_ENV_FILE_PATH)) {
  loadDotenv({ path: PAPERCLIP_ENV_FILE_PATH, override: false, quiet: true });
}

const CWD_ENV_PATH = resolve(process.cwd(), ".env");
const isSameFile = existsSync(CWD_ENV_PATH) && existsSync(PAPERCLIP_ENV_FILE_PATH)
  ? realpathSync(CWD_ENV_PATH) === realpathSync(PAPERCLIP_ENV_FILE_PATH)
  : CWD_ENV_PATH === PAPERCLIP_ENV_FILE_PATH;
if (!isSameFile && existsSync(CWD_ENV_PATH)) {
  loadDotenv({ path: CWD_ENV_PATH, override: false, quiet: true });
}

maybeRepairLegacyWorktreeConfigAndEnvFiles();

const TAILSCALE_DETECT_TIMEOUT_MS = 3000;

// Auto-generate PAPERCLIP_AGENT_JWT_SECRET on first boot so agents can authenticate
// without requiring a separate `pnpm paperclipai onboard` step.
if (!process.env.PAPERCLIP_AGENT_JWT_SECRET?.trim()) {
  const secret = randomBytes(32).toString("hex");
  const envDir = dirname(PAPERCLIP_ENV_FILE_PATH);
  mkdirSync(envDir, { recursive: true });
  const existing = existsSync(PAPERCLIP_ENV_FILE_PATH)
    ? parseDotenv(readFileSync(PAPERCLIP_ENV_FILE_PATH, "utf-8"))
    : {};
  existing.PAPERCLIP_AGENT_JWT_SECRET = secret;
  const lines = [
    "# Paperclip environment variables",
    "# Auto-generated by Paperclip server",
    ...Object.entries(existing).map(([k, v]) => `${k}=${v}`),
    "",
  ];
  writeFileSync(PAPERCLIP_ENV_FILE_PATH, lines.join("\n"), { mode: 0o600 });
  process.env.PAPERCLIP_AGENT_JWT_SECRET = secret;
}

type DatabaseMode = "embedded-postgres" | "postgres";

export interface Config {
  deploymentMode: DeploymentMode;
  deploymentExposure: DeploymentExposure;
  bind: BindMode;
  customBindHost: string | undefined;
  host: string;
  port: number;
  allowedHostnames: string[];
  authBaseUrlMode: AuthBaseUrlMode;
  authPublicBaseUrl: string | undefined;
  authDisableSignUp: boolean;
  databaseMode: DatabaseMode;
  databaseUrl: string | undefined;
  databaseMigrationUrl: string | undefined;
  embeddedPostgresDataDir: string;
  embeddedPostgresPort: number;
  databaseBackupEnabled: boolean;
  databaseBackupIntervalMinutes: number;
  databaseBackupRetentionDays: number;
  databaseBackupDir: string;
  // Merged-PR reconciler (BLO-9150): a scheduled sweep that backfills the no-ref
  // tail so the efficiency coverage % is measured, not a vacuous forward-only 100%.
  // Worker-tier only (gated on paperclipNodeRole !== "api" in index.ts).
  prReconcilerEnabled: boolean;
  prReconcilerIntervalMinutes: number;
  prReconcilerWindowDays: number;
  prReconcilerEnrichLoc: boolean;
  serveUi: boolean;
  uiDevMiddleware: boolean;
  secretsProvider: SecretProvider;
  secretsStrictMode: boolean;
  secretsMasterKeyFilePath: string;
  storageProvider: StorageProvider;
  storageLocalDiskBaseDir: string;
  storageS3Bucket: string;
  storageS3Region: string;
  storageS3Endpoint: string | undefined;
  storageS3Prefix: string;
  storageS3ForcePathStyle: boolean;
  feedbackExportBackendUrl: string | undefined;
  feedbackExportBackendToken: string | undefined;
  heartbeatSchedulerEnabled: boolean;
  heartbeatSchedulerIntervalMs: number;
  // Process role for HA topology. When set to "api", the process serves
  // HTTP traffic only — no in-process plugin workers, no heartbeat
  // scheduler. When set to "worker", the process owns the heartbeat
  // scheduler + plugin workers (and may also serve HTTP — though typically
  // only an internal Service points at workers). When set to "all" (the
  // default), behavior is identical to pre-split single-pod paperclip:
  // one process owns everything.
  // Set via PAPERCLIP_NODE_ROLE env. Used by index.ts to gate which
  // subsystems start.
  paperclipNodeRole: "api" | "worker" | "all";
  // Base URL of the worker tier's internal Service, e.g.
  // "http://paperclip-workers:3100". Only consulted on the API tier
  // (PAPERCLIP_NODE_ROLE=api): worker-dependent plugin routes reverse-proxy
  // here so plugin lifecycle/bridge calls land on the pod that actually
  // owns pluginWorkerManager. Unset → those routes 503 via the API-tier
  // stub as before (no worker tier reachable). Set via
  // PAPERCLIP_WORKERS_INTERNAL_URL env.
  paperclipWorkersInternalUrl: string | null;
  companyDeletionEnabled: boolean;
  linearOAuthClientId: string;
  linearOAuthClientSecret: string;
  linearOAuthRedirectUri: string;
  // Shared secret configured on the GitHub webhook ("Secret" field in
  // the repo / org / app webhook settings). Used to verify
  // x-hub-signature-256 on POST /api/webhooks/github. When unset the
  // route refuses every request -- accepting unsigned webhooks would
  // let any caller drive paperclip wakes by impersonating GitHub.
  githubWebhookSecret: string;
  // Agent ID that receives an additional wake on `pull_request.opened`,
  // `pull_request.ready_for_review`, and `pull_request_review.submitted`
  // events to drive PR review automation. When unset, the github-webhook
  // route only wakes the issue assignee (legacy behavior).
  githubPrReviewerAgentId: string;
  githubDependabotAgentId: string;
  githubDependabotMinSeverity: string;
  // GitHub App creds (from the `paperclip-github-app-creds` secret) used to mint
  // short-lived installation tokens so the server can authoritatively verify, via
  // the GitHub API, that a PR-review run actually left a review/comment before
  // flagging it `pr_review_output_missing`. All empty when unmounted -> the
  // verification is inert and the run falls back to the text-heuristic result.
  githubAppId: string;
  githubAppInstallationId: string;
  githubAppPrivateKey: string;
  // GitHub login of the PR-reviewer bot (the GitHub App's bot user, e.g.
  // "allyblockcast[bot]") used to filter reviews/comments during verification.
  prReviewerBotLogin: string;
  telemetryEnabled: boolean;
}

function detectTailnetBindHost(): string | undefined {
  const explicit = process.env.PAPERCLIP_TAILNET_BIND_HOST?.trim();
  if (explicit) return explicit;

  try {
    const stdout = execFileSync("tailscale", ["ip", "-4"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
      timeout: TAILSCALE_DETECT_TIMEOUT_MS,
    });
    return stdout
      .split(/\r?\n/)
      .map((line) => line.trim())
      .find(Boolean);
  } catch {
    return undefined;
  }
}

export function loadConfig(): Config {
  const fileConfig = readConfigFile();
  const fileDatabaseMode =
    (fileConfig?.database.mode === "postgres" ? "postgres" : "embedded-postgres") as DatabaseMode;

  const fileDbUrl =
    fileDatabaseMode === "postgres"
      ? fileConfig?.database.connectionString
      : undefined;
  const fileDatabaseBackup = fileConfig?.database.backup;
  const fileSecrets = fileConfig?.secrets;
  const fileStorage = fileConfig?.storage;

  const providerFromEnvRaw = process.env.PAPERCLIP_SECRETS_PROVIDER;
  const providerFromEnv =
    providerFromEnvRaw && SECRET_PROVIDERS.includes(providerFromEnvRaw as SecretProvider)
      ? (providerFromEnvRaw as SecretProvider)
      : null;
  const providerFromFile = fileSecrets?.provider;
  const secretsProvider: SecretProvider = providerFromEnv ?? providerFromFile ?? "local_encrypted";

  const storageProviderFromEnvRaw = process.env.PAPERCLIP_STORAGE_PROVIDER;
  const storageProviderFromEnv =
    storageProviderFromEnvRaw && STORAGE_PROVIDERS.includes(storageProviderFromEnvRaw as StorageProvider)
      ? (storageProviderFromEnvRaw as StorageProvider)
      : null;
  const storageProvider: StorageProvider = storageProviderFromEnv ?? fileStorage?.provider ?? "local_disk";
  const storageLocalDiskBaseDir = resolveHomeAwarePath(
    process.env.PAPERCLIP_STORAGE_LOCAL_DIR ??
      fileStorage?.localDisk?.baseDir ??
      resolveDefaultStorageDir(),
  );
  const storageS3Bucket = process.env.PAPERCLIP_STORAGE_S3_BUCKET ?? fileStorage?.s3?.bucket ?? "paperclip";
  const storageS3Region = process.env.PAPERCLIP_STORAGE_S3_REGION ?? fileStorage?.s3?.region ?? "us-east-1";
  const storageS3Endpoint = process.env.PAPERCLIP_STORAGE_S3_ENDPOINT ?? fileStorage?.s3?.endpoint ?? undefined;
  const storageS3Prefix = process.env.PAPERCLIP_STORAGE_S3_PREFIX ?? fileStorage?.s3?.prefix ?? "";
  const storageS3ForcePathStyle =
    process.env.PAPERCLIP_STORAGE_S3_FORCE_PATH_STYLE !== undefined
      ? process.env.PAPERCLIP_STORAGE_S3_FORCE_PATH_STYLE === "true"
      : (fileStorage?.s3?.forcePathStyle ?? false);
  const feedbackExportBackendUrl =
    process.env.PAPERCLIP_FEEDBACK_EXPORT_BACKEND_URL?.trim() ||
    process.env.PAPERCLIP_TELEMETRY_BACKEND_URL?.trim() ||
    undefined;
  const feedbackExportBackendToken =
    process.env.PAPERCLIP_FEEDBACK_EXPORT_BACKEND_TOKEN?.trim() ||
    process.env.PAPERCLIP_TELEMETRY_BACKEND_TOKEN?.trim() ||
    undefined;

  const deploymentModeFromEnvRaw = process.env.PAPERCLIP_DEPLOYMENT_MODE;
  const deploymentModeFromEnv =
    deploymentModeFromEnvRaw && DEPLOYMENT_MODES.includes(deploymentModeFromEnvRaw as DeploymentMode)
      ? (deploymentModeFromEnvRaw as DeploymentMode)
      : null;
  const deploymentMode: DeploymentMode = deploymentModeFromEnv ?? fileConfig?.server.deploymentMode ?? "local_trusted";
  const strictModeFromEnv = process.env.PAPERCLIP_SECRETS_STRICT_MODE;
  const secretsStrictMode =
    strictModeFromEnv !== undefined
      ? strictModeFromEnv === "true"
      : (fileSecrets?.strictMode ?? deploymentMode === "authenticated");
  const deploymentExposureFromEnvRaw = process.env.PAPERCLIP_DEPLOYMENT_EXPOSURE;
  const deploymentExposureFromEnv =
    deploymentExposureFromEnvRaw &&
    DEPLOYMENT_EXPOSURES.includes(deploymentExposureFromEnvRaw as DeploymentExposure)
      ? (deploymentExposureFromEnvRaw as DeploymentExposure)
      : null;
  const deploymentExposure: DeploymentExposure =
    deploymentMode === "local_trusted"
      ? "private"
      : (deploymentExposureFromEnv ?? fileConfig?.server.exposure ?? "private");
  const bindFromEnvRaw = process.env.PAPERCLIP_BIND;
  const bindFromEnv =
    bindFromEnvRaw && BIND_MODES.includes(bindFromEnvRaw as BindMode)
      ? (bindFromEnvRaw as BindMode)
      : null;
  const configuredHost = process.env.HOST ?? fileConfig?.server.host ?? "127.0.0.1";
  const tailnetBindHost = detectTailnetBindHost();
  const bind =
    bindFromEnv ??
    fileConfig?.server.bind ??
    inferBindModeFromHost(configuredHost, { tailnetBindHost });
  const customBindHost = process.env.PAPERCLIP_BIND_HOST ?? fileConfig?.server.customBindHost;
  const authBaseUrlModeFromEnvRaw = process.env.PAPERCLIP_AUTH_BASE_URL_MODE;
  const authBaseUrlModeFromEnv =
    authBaseUrlModeFromEnvRaw &&
    AUTH_BASE_URL_MODES.includes(authBaseUrlModeFromEnvRaw as AuthBaseUrlMode)
      ? (authBaseUrlModeFromEnvRaw as AuthBaseUrlMode)
      : null;
  const publicUrlFromEnv = process.env.PAPERCLIP_PUBLIC_URL;
  const authPublicBaseUrlRaw =
    process.env.PAPERCLIP_AUTH_PUBLIC_BASE_URL ??
    process.env.BETTER_AUTH_URL ??
    process.env.BETTER_AUTH_BASE_URL ??
    publicUrlFromEnv ??
    fileConfig?.auth?.publicBaseUrl;
  const authPublicBaseUrl = authPublicBaseUrlRaw?.trim() || undefined;
  const authBaseUrlMode: AuthBaseUrlMode =
    authBaseUrlModeFromEnv ??
    fileConfig?.auth?.baseUrlMode ??
    (authPublicBaseUrl ? "explicit" : "auto");
  const disableSignUpFromEnv = process.env.PAPERCLIP_AUTH_DISABLE_SIGN_UP;
  const authDisableSignUp: boolean =
    disableSignUpFromEnv !== undefined
      ? disableSignUpFromEnv === "true"
      : (fileConfig?.auth?.disableSignUp ?? false);
  const allowedHostnamesFromEnvRaw = process.env.PAPERCLIP_ALLOWED_HOSTNAMES;
  const allowedHostnamesFromEnv = allowedHostnamesFromEnvRaw
    ? allowedHostnamesFromEnvRaw
      .split(",")
      .map((value) => value.trim().toLowerCase())
      .filter((value) => value.length > 0)
    : null;
  const publicUrlHostname = authPublicBaseUrl
    ? (() => {
      try {
        return new URL(authPublicBaseUrl).hostname.trim().toLowerCase();
      } catch {
        return null;
      }
    })()
    : null;
  const allowedHostnames = Array.from(
    new Set(
      [
        ...(allowedHostnamesFromEnv ?? fileConfig?.server.allowedHostnames ?? []),
        ...(publicUrlHostname ? [publicUrlHostname] : []),
      ]
        .map((value) => value.trim().toLowerCase())
        .filter(Boolean),
    ),
  );
  const companyDeletionEnvRaw = process.env.PAPERCLIP_ENABLE_COMPANY_DELETION;
  const companyDeletionEnabled =
    companyDeletionEnvRaw !== undefined
      ? companyDeletionEnvRaw === "true"
      : deploymentMode === "local_trusted";
  // PAPERCLIP_NODE_ROLE — defaults to "all" (single-pod, pre-split behavior).
  // Set to "api" for HTTP-only API replicas (no plugin workers, no scheduler).
  // Set to "worker" for the singleton workload that drives heartbeat dispatch
  // and hosts plugin workers. Unknown values fall back to "all" to preserve
  // safety (the worst case is a single process doing everything).
  const paperclipNodeRoleRaw = process.env.PAPERCLIP_NODE_ROLE ?? "all";
  const paperclipNodeRole: "api" | "worker" | "all" =
    paperclipNodeRoleRaw === "api" || paperclipNodeRoleRaw === "worker"
      ? paperclipNodeRoleRaw
      : "all";
  const databaseBackupEnabled =
    process.env.PAPERCLIP_DB_BACKUP_ENABLED !== undefined
      ? process.env.PAPERCLIP_DB_BACKUP_ENABLED === "true"
      : (fileDatabaseBackup?.enabled ?? true);
  const databaseBackupIntervalMinutes = Math.max(
    1,
    Number(process.env.PAPERCLIP_DB_BACKUP_INTERVAL_MINUTES) ||
      fileDatabaseBackup?.intervalMinutes ||
      60,
  );
  const databaseBackupRetentionDays = Math.max(
    1,
    Number(process.env.PAPERCLIP_DB_BACKUP_RETENTION_DAYS) ||
      fileDatabaseBackup?.retentionDays ||
      7,
  );
  const databaseBackupDir = resolveHomeAwarePath(
    process.env.PAPERCLIP_DB_BACKUP_DIR ??
      fileDatabaseBackup?.dir ??
      resolveDefaultBackupDir(),
  );
  // Merged-PR reconciler (BLO-9150). Enabled by default: the efficiency metric is
  // only honest once the no-ref tail is enumerated. Window defaults to 21d to
  // match the BLO-9103 cost-analysis window; interval defaults to 6h (merged PRs
  // are slow-moving, re-enumerating a 21d window every 6h is ample).
  const prReconcilerEnabled =
    process.env.PAPERCLIP_PR_RECONCILER_ENABLED !== undefined
      ? process.env.PAPERCLIP_PR_RECONCILER_ENABLED === "true"
      : true;
  const prReconcilerIntervalMinutes = Math.max(
    1,
    Number(process.env.PAPERCLIP_PR_RECONCILER_INTERVAL_MINUTES) || 360,
  );
  const prReconcilerWindowDays = Math.max(
    1,
    Number(process.env.PAPERCLIP_PR_RECONCILER_WINDOW_DAYS) || 21,
  );
  const prReconcilerEnrichLoc =
    process.env.PAPERCLIP_PR_RECONCILER_ENRICH_LOC !== undefined
      ? process.env.PAPERCLIP_PR_RECONCILER_ENRICH_LOC === "true"
      : true;
  const bindValidationErrors = validateConfiguredBindMode({
    deploymentMode,
    deploymentExposure,
    bind,
    host: configuredHost,
    customBindHost,
  });
  if (bindValidationErrors.length > 0) {
    throw new Error(bindValidationErrors[0]);
  }
  const resolvedBind = resolveRuntimeBind({
    bind,
    host: configuredHost,
    customBindHost,
    tailnetBindHost,
  });
  if (resolvedBind.errors.length > 0) {
    throw new Error(resolvedBind.errors[0]);
  }

  return {
    deploymentMode,
    deploymentExposure,
    bind: resolvedBind.bind,
    customBindHost: resolvedBind.customBindHost,
    host: resolvedBind.host,
    port: Number(process.env.PORT) || fileConfig?.server.port || 3100,
    allowedHostnames,
    authBaseUrlMode,
    authPublicBaseUrl,
    authDisableSignUp,
    databaseMode: fileDatabaseMode,
    databaseUrl: process.env.DATABASE_URL ?? fileDbUrl,
    databaseMigrationUrl: process.env.DATABASE_MIGRATION_URL,
    embeddedPostgresDataDir: resolveHomeAwarePath(
      fileConfig?.database.embeddedPostgresDataDir ?? resolveDefaultEmbeddedPostgresDir(),
    ),
    embeddedPostgresPort: fileConfig?.database.embeddedPostgresPort ?? 54329,
    databaseBackupEnabled,
    databaseBackupIntervalMinutes,
    prReconcilerEnabled,
    prReconcilerIntervalMinutes,
    prReconcilerWindowDays,
    prReconcilerEnrichLoc,
    databaseBackupRetentionDays,
    databaseBackupDir,
    serveUi:
      process.env.SERVE_UI !== undefined
        ? process.env.SERVE_UI === "true"
        : fileConfig?.server.serveUi ?? true,
    uiDevMiddleware: process.env.PAPERCLIP_UI_DEV_MIDDLEWARE === "true",
    secretsProvider,
    secretsStrictMode,
    secretsMasterKeyFilePath:
      resolveHomeAwarePath(
        process.env.PAPERCLIP_SECRETS_MASTER_KEY_FILE ??
          fileSecrets?.localEncrypted.keyFilePath ??
          resolveDefaultSecretsKeyFilePath(),
      ),
    storageProvider,
    storageLocalDiskBaseDir,
    storageS3Bucket,
    storageS3Region,
    storageS3Endpoint,
    storageS3Prefix,
    storageS3ForcePathStyle,
    feedbackExportBackendUrl,
    feedbackExportBackendToken,
    heartbeatSchedulerEnabled:
      // API role implies scheduler off regardless of HEARTBEAT_SCHEDULER_ENABLED.
      // Setting both lets `kubectl set env` toggles work the way operators expect.
      paperclipNodeRole === "api"
        ? false
        : process.env.HEARTBEAT_SCHEDULER_ENABLED !== "false",
    heartbeatSchedulerIntervalMs: Math.max(10000, Number(process.env.HEARTBEAT_SCHEDULER_INTERVAL_MS) || 30000),
    paperclipNodeRole,
    paperclipWorkersInternalUrl:
      process.env.PAPERCLIP_WORKERS_INTERNAL_URL?.trim().replace(/\/+$/, "") || null,
    companyDeletionEnabled,
    linearOAuthClientId: process.env.PAPERCLIP_LINEAR_CLIENT_ID ?? "",
    linearOAuthClientSecret: process.env.PAPERCLIP_LINEAR_CLIENT_SECRET ?? "",
    linearOAuthRedirectUri:
      process.env.PAPERCLIP_LINEAR_REDIRECT_URI ??
      `http://localhost:${Number(process.env.PORT) || fileConfig?.server.port || 3100}/api/auth/linear/callback`,
    githubWebhookSecret: process.env.GITHUB_WEBHOOK_SECRET ?? "",
    // Agent ID that receives an additional wake on `pull_request.opened`,
    // `pull_request.ready_for_review`, and `pull_request_review.submitted`
    // events to drive PR review automation. When unset, the github-webhook
    // route only wakes the issue assignee (legacy behavior). The reviewer
    // wake fires regardless of whether the PR branch references a paperclip
    // identifier, so PRs without a BLO-XXX in the branch/title/body still
    // get reviewed.
    githubPrReviewerAgentId: process.env.PAPERCLIP_PR_REVIEWER_AGENT_ID ?? "",
    githubDependabotAgentId: process.env.PAPERCLIP_DEPENDABOT_AGENT_ID ?? "",
    githubDependabotMinSeverity: process.env.PAPERCLIP_DEPENDABOT_MIN_SEVERITY ?? "high",
    // GitHub App creds for server-side installation-token minting (PR-review
    // evidence verification). `private_key.pem` may arrive with escaped "\n"
    // depending on how it is injected, so normalize them to real newlines.
    githubAppId: process.env.GITHUB_APP_ID ?? "",
    githubAppInstallationId: process.env.GITHUB_APP_INSTALLATION_ID ?? "",
    githubAppPrivateKey: (process.env.GITHUB_APP_PRIVATE_KEY ?? "").replace(/\\n/g, "\n"),
    prReviewerBotLogin: process.env.PAPERCLIP_PR_REVIEWER_BOT_LOGIN ?? "allyblockcast[bot]",
    telemetryEnabled: fileConfig?.telemetry?.enabled ?? true,
  };
}
