#!/bin/bash
set -e

# Paperclip Deployment Script
# This script sets up and deploys Paperclip in a production environment

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env.prod"
COMPOSE_FILE="$PROJECT_DIR/docker-compose.prod.yml"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
print_header() {
    echo -e "\n${BLUE}===================================================${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}===================================================${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

check_requirements() {
    print_header "Checking Requirements"

    # Check Docker
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed"
        exit 1
    fi
    print_success "Docker is installed"

    # Check Docker Compose
    if ! command -v docker-compose &> /dev/null; then
        print_error "Docker Compose is not installed"
        exit 1
    fi
    print_success "Docker Compose is installed"

    # Check openssl
    if ! command -v openssl &> /dev/null; then
        print_error "openssl is not installed"
        exit 1
    fi
    print_success "openssl is installed"

    # Check git
    if ! command -v git &> /dev/null; then
        print_error "git is not installed"
        exit 1
    fi
    print_success "git is installed"
}

setup_environment() {
    print_header "Environment Setup"

    if [ -f "$ENV_FILE" ]; then
        print_warning "Environment file already exists: $ENV_FILE"
        read -p "Overwrite? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            print_success "Using existing environment file"
            return
        fi
    fi

    # Generate secrets
    print_warning "Generating security secrets..."
    BETTER_AUTH_SECRET=$(openssl rand -base64 32)
    DB_PASSWORD=$(openssl rand -base64 32)

    # Get configuration
    print_warning "Please provide configuration:"

    read -p "Database user [paperclip_prod]: " DB_USER
    DB_USER=${DB_USER:-paperclip_prod}

    read -p "Database name [paperclip_prod]: " DB_NAME
    DB_NAME=${DB_NAME:-paperclip_prod}

    read -p "Public URL (e.g., https://paperclip.yourdomain.com): " PUBLIC_URL
    if [ -z "$PUBLIC_URL" ]; then
        print_error "Public URL is required"
        exit 1
    fi

    read -p "Deployment mode [authenticated]: " DEPLOYMENT_MODE
    DEPLOYMENT_MODE=${DEPLOYMENT_MODE:-authenticated}

    read -p "Log level [info]: " LOG_LEVEL
    LOG_LEVEL=${LOG_LEVEL:-info}

    # Create environment file
    cat > "$ENV_FILE" << EOF
# Generated by deploy.sh on $(date)
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_NAME=$DB_NAME
BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
DEPLOYMENT_MODE=$DEPLOYMENT_MODE
DEPLOYMENT_EXPOSURE=private
PUBLIC_URL=$PUBLIC_URL
LOG_LEVEL=$LOG_LEVEL
EOF

    print_success "Environment file created: $ENV_FILE"
    echo -e "${YELLOW}⚠ Save the secrets below securely:${NC}"
    echo "  - DB_PASSWORD: $DB_PASSWORD"
    echo "  - BETTER_AUTH_SECRET: $BETTER_AUTH_SECRET"
}

verify_docker_config() {
    print_header "Verifying Docker Configuration"

    if [ ! -f "$COMPOSE_FILE" ]; then
        print_error "docker-compose.prod.yml not found"
        exit 1
    fi
    print_success "docker-compose.prod.yml exists"

    if [ ! -f "$PROJECT_DIR/nginx.conf" ]; then
        print_error "nginx.conf not found"
        exit 1
    fi
    print_success "nginx.conf exists"

    if [ ! -f "$PROJECT_DIR/Dockerfile" ]; then
        print_error "Dockerfile not found"
        exit 1
    fi
    print_success "Dockerfile exists"
}

build_images() {
    print_header "Building Docker Images"

    cd "$PROJECT_DIR"

    # Export environment
    export $(cat "$ENV_FILE" | xargs)

    print_warning "Building images (this may take several minutes)..."
    docker-compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" build --no-cache

    print_success "Images built successfully"
}

start_services() {
    print_header "Starting Services"

    cd "$PROJECT_DIR"

    print_warning "Starting services..."
    docker-compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d

    print_success "Services started"

    echo -e "\n${YELLOW}Waiting for services to be healthy...${NC}"
    sleep 5

    # Check service health
    if docker-compose -f "$COMPOSE_FILE" ps | grep -q "unhealthy\|Exit"; then
        print_warning "Some services may not be healthy yet. Checking logs..."
        docker-compose -f "$COMPOSE_FILE" logs --tail=20
        echo -e "\n${YELLOW}Retrying in 5 seconds...${NC}"
        sleep 5
    fi

    print_success "Services are running"
}

setup_systemd() {
    print_header "Setting up Systemd Service"

    if [ ! -f "/etc/systemd/system/paperclip-docker.service" ]; then
        read -p "Setup systemd service for auto-start? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            sudo cp "$PROJECT_DIR/paperclip-docker.service" /etc/systemd/system/
            sudo systemctl daemon-reload
            sudo systemctl enable paperclip-docker
            print_success "Systemd service installed"
        fi
    else
        print_success "Systemd service already installed"
    fi
}

verify_deployment() {
    print_header "Verifying Deployment"

    print_warning "Checking health endpoints..."

    # Check API health
    if curl -s -f http://localhost:3100/health > /dev/null 2>&1; then
        print_success "API is healthy"
    else
        print_warning "API health check failed (may still be starting)"
    fi

    # Check Nginx
    if curl -s -f http://localhost/health > /dev/null 2>&1; then
        print_success "Nginx is responding"
    else
        print_warning "Nginx not responding (may still be starting)"
    fi
}

show_next_steps() {
    print_header "Deployment Complete!"

    echo -e "${GREEN}Paperclip is deployed and running.${NC}\n"

    echo "Next steps:"
    echo ""
    echo "1. Access Paperclip:"
    grep "PUBLIC_URL=" "$ENV_FILE" | sed 's/^/   /'
    echo ""
    echo "2. View logs:"
    echo "   cd $PROJECT_DIR"
    echo "   docker-compose -f docker-compose.prod.yml logs -f"
    echo ""
    echo "3. Setup HTTPS:"
    echo "   sudo certbot certonly --standalone -d your-domain.com"
    echo "   Then update nginx.conf with certificate paths"
    echo ""
    echo "4. Manage services:"
    echo "   docker-compose -f docker-compose.prod.yml ps"
    echo "   docker-compose -f docker-compose.prod.yml restart"
    echo ""
    echo "5. Database backup:"
    echo "   $PROJECT_DIR/scripts/backup-db.sh"
    echo ""
    echo -e "${YELLOW}Important:${NC}"
    echo "   - Change BETTER_AUTH_SECRET and DB_PASSWORD regularly"
    echo "   - Setup HTTPS for production"
    echo "   - Configure automated backups"
    echo "   - Monitor logs and health"
    echo ""
}

# Main execution
main() {
    echo -e "${BLUE}"
    echo "╔═══════════════════════════════════════════════╗"
    echo "║   Paperclip Production Deployment Script      ║"
    echo "╚═══════════════════════════════════════════════╝"
    echo -e "${NC}"

    check_requirements
    setup_environment
    verify_docker_config
    build_images
    start_services
    sleep 5  # Give services time to stabilize
    verify_deployment
    setup_systemd
    show_next_steps
}

# Run main if not sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
