#!/usr/bin/env bash

set -euo pipefail

readonly GITHUB_REPOSITORY="paperclipai/paperclip"
readonly TRAIN_LABEL="dotta-dev"
readonly TRAIN_BRANCH="dev/dotta"
readonly MIGRATIONS_PREFIX="packages/db/src/migrations/"
readonly MANIFEST_SCHEMA_VERSION=1
readonly MANIFEST_GENERATOR="scripts/dotta-dev-train.sh"

dry_run=false
manifest_path=".paperclip/dotta-dev-manifest.json"
manifest_worktree_path=""

usage() {
  cat <<'USAGE'
Usage: scripts/dotta-dev-train.sh [--dry-run] [--manifest PATH]

Build dev/dotta from origin/master plus every open pull request labeled
dotta-dev. The script skips conflicting pull requests and writes a JSON
manifest. --dry-run builds the local branch and manifest without changing
GitHub labels or pushing the branch.
USAGE
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: required command not found: $1" >&2
    exit 1
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      dry_run=true
      shift
      ;;
    --manifest)
      if [[ $# -lt 2 || -z "$2" ]]; then
        echo "error: --manifest requires a path" >&2
        usage >&2
        exit 2
      fi
      manifest_path="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

require_command git
require_command gh
require_command jq
require_command mktemp

repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || {
  echo "error: run this script inside a git worktree" >&2
  exit 1
}
cd "$repo_root"

if [[ "$manifest_path" != /* ]]; then
  manifest_worktree_path="${manifest_path#./}"
  manifest_path="$repo_root/$manifest_worktree_path"
else
  manifest_dir="$(dirname "$manifest_path")"
  if [[ -d "$manifest_dir" ]] &&
    [[ "$(git -C "$manifest_dir" rev-parse --show-toplevel 2>/dev/null || true)" == "$repo_root" ]]; then
    manifest_worktree_path="$(git -C "$manifest_dir" rev-parse --show-prefix)$(basename "$manifest_path")"
  fi
fi

if tracked_manifest_path="$(git ls-files --error-unmatch -- "$manifest_path" 2>/dev/null)"; then
  echo "error: refusing to overwrite tracked manifest path: $tracked_manifest_path" >&2
  exit 1
fi

if [[ -e "$manifest_path" || -L "$manifest_path" ]]; then
  if [[ ! -f "$manifest_path" || -L "$manifest_path" ]] ||
    ! jq -e \
      --argjson schemaVersion "$MANIFEST_SCHEMA_VERSION" \
      --arg generatedBy "$MANIFEST_GENERATOR" \
      --arg repository "$GITHUB_REPOSITORY" \
      --arg branch "$TRAIN_BRANCH" \
      'type == "object" and
       .schemaVersion == $schemaVersion and
       .generatedBy == $generatedBy and
       .repository == $repository and
       .branch == $branch' \
      "$manifest_path" >/dev/null 2>&1; then
    echo "error: refusing to overwrite manifest path not generated by $MANIFEST_GENERATOR: $manifest_path" >&2
    exit 1
  fi
fi

status_pathspecs=(.)
if [[ -n "$manifest_worktree_path" ]]; then
  status_pathspecs+=(":(exclude,top,literal)$manifest_worktree_path")
fi

if [[ -n "$(git status --porcelain --untracked-files=all -- "${status_pathspecs[@]}")" ]]; then
  echo "error: the worktree must be clean before rebuilding $TRAIN_BRANCH" >&2
  git status --short -- "${status_pathspecs[@]}" >&2
  exit 1
fi

tmp_dir="$(mktemp -d "${TMPDIR:-/tmp}/dotta-dev-train.XXXXXX")"
pr_list_path="$tmp_dir/pr-list.json"
included_path="$tmp_dir/included.jsonl"
skipped_path="$tmp_dir/skipped.jsonl"
: >"$included_path"
: >"$skipped_path"

cleanup() {
  if git rev-parse -q --verify MERGE_HEAD >/dev/null 2>&1; then
    git merge --abort >/dev/null 2>&1 || true
  fi
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

if [[ "$dry_run" == false ]]; then
  gh label create "$TRAIN_LABEL" \
    --repo "$GITHUB_REPOSITORY" \
    --color "7B61FF" \
    --description "Include this PR in the disposable dev/dotta assembly branch" \
    --force >/dev/null
fi

gh pr list \
  --repo "$GITHUB_REPOSITORY" \
  --state open \
  --base master \
  --label "$TRAIN_LABEL" \
  --limit 1000 \
  --json number,headRefOid,title >"$pr_list_path"

if ! jq -e '
  type == "array" and
  all(.[]; (.number | type == "number") and (.headRefOid | type == "string") and (.title | type == "string"))
' "$pr_list_path" >/dev/null; then
  echo "error: gh returned invalid pull request metadata" >&2
  exit 1
fi

git fetch origin
base_master_sha="$(git rev-parse 'origin/master^{commit}')"
git switch --force-create "$TRAIN_BRANCH" origin/master
git reset --hard "$base_master_sha"

while IFS= read -r pr_json; do
  number="$(jq -r '.number' <<<"$pr_json")"
  expected_head_sha="$(jq -r '.headRefOid' <<<"$pr_json")"
  title="$(jq -r '.title' <<<"$pr_json")"

  changed_files_path="$tmp_dir/pr-$number-files.txt"
  gh api --paginate \
    "repos/$GITHUB_REPOSITORY/pulls/$number/files?per_page=100" \
    --jq '.[].filename' >"$changed_files_path"
  migrations=false
  while IFS= read -r changed_file; do
    if [[ "$changed_file" == "$MIGRATIONS_PREFIX"* ]]; then
      migrations=true
      break
    fi
  done <"$changed_files_path"

  pr_ref="refs/dotta-dev/pr-$number"
  if ! git fetch --force origin "+refs/pull/$number/head:$pr_ref"; then
    jq -cn \
      --argjson number "$number" \
      --arg headSha "$expected_head_sha" \
      --arg title "$title" \
      --argjson migrations "$migrations" \
      --arg reason "could not fetch PR head" \
      '{number: $number, headSha: $headSha, title: $title, migrations: $migrations, reason: $reason}' \
      >>"$skipped_path"
    continue
  fi

  fetched_head_sha="$(git rev-parse "$pr_ref^{commit}")"
  if [[ "$fetched_head_sha" != "$expected_head_sha" ]]; then
    jq -cn \
      --argjson number "$number" \
      --arg headSha "$expected_head_sha" \
      --arg title "$title" \
      --argjson migrations "$migrations" \
      --arg reason "head changed while assembling (fetched $fetched_head_sha)" \
      '{number: $number, headSha: $headSha, title: $title, migrations: $migrations, reason: $reason}' \
      >>"$skipped_path"
    continue
  fi

  if git merge --no-ff --no-edit -m "dotta-dev: merge PR #$number" "$pr_ref"; then
    jq -cn \
      --argjson number "$number" \
      --arg headSha "$fetched_head_sha" \
      --arg title "$title" \
      --argjson migrations "$migrations" \
      '{number: $number, headSha: $headSha, title: $title, migrations: $migrations}' \
      >>"$included_path"
    continue
  fi

  conflict_files="$(git diff --name-only --diff-filter=U | paste -sd ',' -)"
  merge_in_progress=false
  if git rev-parse -q --verify MERGE_HEAD >/dev/null 2>&1; then
    merge_in_progress=true
    git merge --abort
  else
    git reset --hard HEAD
  fi

  reason="git merge failed"
  if [[ "$merge_in_progress" == true && -n "$conflict_files" ]]; then
    reason="merge conflict: $conflict_files"
  fi
  jq -cn \
    --argjson number "$number" \
    --arg headSha "$fetched_head_sha" \
    --arg title "$title" \
    --argjson migrations "$migrations" \
    --arg reason "$reason" \
    '{number: $number, headSha: $headSha, title: $title, migrations: $migrations, reason: $reason}' \
    >>"$skipped_path"
done < <(jq -c 'sort_by(.number)[]' "$pr_list_path")

if tracked_manifest_path="$(git ls-files --error-unmatch -- "$manifest_path" 2>/dev/null)"; then
  echo "error: refusing to overwrite tracked manifest path introduced while assembling $TRAIN_BRANCH: $tracked_manifest_path" >&2
  exit 1
fi

mkdir -p "$(dirname "$manifest_path")"
manifest_tmp="$tmp_dir/manifest.json"
train_commit_sha="$(git rev-parse 'HEAD^{commit}')"
jq -n \
  --argjson schemaVersion "$MANIFEST_SCHEMA_VERSION" \
  --arg generatedBy "$MANIFEST_GENERATOR" \
  --arg repository "$GITHUB_REPOSITORY" \
  --arg branch "$TRAIN_BRANCH" \
  --arg baseMasterSha "$base_master_sha" \
  --arg trainCommitSha "$train_commit_sha" \
  --arg generatedAt "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
  --argjson dryRun "$dry_run" \
  --slurpfile included "$included_path" \
  --slurpfile skipped "$skipped_path" \
  '{
    schemaVersion: $schemaVersion,
    generatedBy: $generatedBy,
    repository: $repository,
    branch: $branch,
    baseMasterSha: $baseMasterSha,
    trainCommitSha: $trainCommitSha,
    generatedAt: $generatedAt,
    dryRun: $dryRun,
    included: $included,
    skipped: $skipped
  }' >"$manifest_tmp"
mv "$manifest_tmp" "$manifest_path"

echo
echo "Dotta development PR train"
echo "  Base master: $base_master_sha"
echo "  Branch:      $TRAIN_BRANCH"
echo "  Manifest:    $manifest_path"
echo
echo "Included ($(jq '.included | length' "$manifest_path")):"
jq -r '
  .included[] |
  "  #\(.number) \(.headSha[0:12]) migrations=\(.migrations): \(.title | gsub("[\\r\\n\\t]"; " "))"
' "$manifest_path"
echo
echo "Skipped ($(jq '.skipped | length' "$manifest_path")):"
jq -r '
  .skipped[] |
  "  #\(.number) \(.headSha[0:12]) migrations=\(.migrations): \(.title | gsub("[\\r\\n\\t]"; " ")) — \(.reason)"
' "$manifest_path"

if [[ "$dry_run" == true ]]; then
  echo
  echo "Dry run complete. The script did not push $TRAIN_BRANCH."
else
  # paperclip-allow-git-push: operator-invoked update of the disposable assembly branch
  git push --force-with-lease origin "$TRAIN_BRANCH:refs/heads/$TRAIN_BRANCH"
  echo
  echo "Pushed $TRAIN_BRANCH to origin with --force-with-lease."
fi
