@echo off
set "HERMES_WSL_DISTRO_VALUE=%HERMES_WSL_DISTRO%"
if "%HERMES_WSL_DISTRO_VALUE%"=="" set "HERMES_WSL_DISTRO_VALUE=Ubuntu"
set "HERMES_WSL_PATH_VALUE=%HERMES_WSL_PATH%"
if "%HERMES_WSL_PATH_VALUE%"=="" set "HERMES_WSL_PATH_VALUE=hermes"
wsl.exe -d "%HERMES_WSL_DISTRO_VALUE%" -- "%HERMES_WSL_PATH_VALUE%" %*
exit /b %ERRORLEVEL%
