#!/usr/bin/env bash
set -euo pipefail

APP_NAME="${APP_NAME:-tye-paperclip-prod}"

required_vars=(
  DATABASE_URL
  BETTER_AUTH_SECRET
  GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET
  MICROSOFT_CLIENT_ID
  MICROSOFT_CLIENT_SECRET
  PAPERCLIP_SAAS_CONTROL_TOKEN
  PAPERCLIP_STORAGE_S3_BUCKET
  PAPERCLIP_STORAGE_S3_ENDPOINT
  PAPERCLIP_STORAGE_S3_REGION
)

for key in "${required_vars[@]}"; do
  if [[ -z "${!key:-}" ]]; then
    echo "Missing required env: $key"
    exit 1
  fi
done

flyctl secrets set \
  DATABASE_URL="$DATABASE_URL" \
  BETTER_AUTH_SECRET="$BETTER_AUTH_SECRET" \
  GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID" \
  GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET" \
  MICROSOFT_CLIENT_ID="$MICROSOFT_CLIENT_ID" \
  MICROSOFT_CLIENT_SECRET="$MICROSOFT_CLIENT_SECRET" \
  PAPERCLIP_SAAS_CONTROL_TOKEN="$PAPERCLIP_SAAS_CONTROL_TOKEN" \
  PAPERCLIP_DEPLOYMENT_MODE="authenticated" \
  PAPERCLIP_DEPLOYMENT_EXPOSURE="public" \
  PAPERCLIP_AUTH_BASE_URL_MODE="explicit" \
  PAPERCLIP_AUTH_PUBLIC_BASE_URL="https://app.tye.ai" \
  PAPERCLIP_SECRETS_STRICT_MODE="true" \
  PAPERCLIP_STORAGE_PROVIDER="s3" \
  PAPERCLIP_STORAGE_S3_BUCKET="$PAPERCLIP_STORAGE_S3_BUCKET" \
  PAPERCLIP_STORAGE_S3_REGION="$PAPERCLIP_STORAGE_S3_REGION" \
  PAPERCLIP_STORAGE_S3_ENDPOINT="$PAPERCLIP_STORAGE_S3_ENDPOINT" \
  PAPERCLIP_STORAGE_S3_FORCE_PATH_STYLE="true" \
  --app "$APP_NAME"

echo "Secrets set for Fly app: $APP_NAME"
