#!/bin/bash
# scripts/sync-and-deploy.sh — one-shot wrapper for the canonical-overlay
# regeneration workflow. Use when the user says "update the Paperclip
# overlay" and you don't want to type the individual steps.
#
# Companion to the paperclip-overlay-update skill. Steps 1–4 in that skill are
# what this script wraps; steps 5–8 (rebase + push + add-agent) are still manual
# because they require user judgment.
#
# Usage:
#   bash scripts/sync-and-deploy.sh [--apply]
#
# Modes:
#   (default)   dry-run: regenerate, verify, show diff. Do NOT commit.
#   --apply     regenerate, verify, then commit on overlay/genesis with a
#               default commit message. Always verify the diff first.
#
# Exit codes:
#   0  all in sync (or committed successfully)
#   1  sync script reports out-of-sync (after --apply)
#   2  fatal: not on overlay/genesis branch, or canonical missing, etc.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Verify we're on the overlay branch
current_branch=$(git symbolic-ref --short HEAD 2>/dev/null || true)
if [ "$current_branch" != "overlay/genesis" ]; then
    echo "ERROR: must be on overlay/genesis branch (currently on '$current_branch')." >&2
    echo "Run: git checkout overlay/genesis" >&2
    exit 2
fi

# Verify working tree is clean (don't fight with uncommitted edits)
if [ -n "$(git status --porcelain | grep -v '^??' | head -1)" ]; then
    echo "ERROR: working tree has tracked-file changes. Commit or stash first." >&2
    git status --short >&2
    exit 2
fi

# Verify canonical exists
canonical="instances/default/companies/4b7fd6fc-b920-430e-a3bd-defc09fc4326/shared/GENESIS-WEBSITE-GUARDRAILS.md"
if [ ! -f "$canonical" ]; then
    echo "ERROR: canonical file not found at $canonical" >&2
    exit 2
fi

MODE="dryrun"
case "${1:-}" in
    --apply) MODE="apply" ;;
    "")      MODE="dryrun" ;;
    *)      echo "usage: $0 [--apply]" >&2; exit 2 ;;
esac

echo "[1/4] Regenerating per-agent AGENTS.md from canonical..."
if [ "$MODE" = "dryrun" ]; then
    python3 scripts/sync-genesis-overlay.py
    echo
    echo "Inspect the diff above. If it looks right, re-run with --apply."
    exit 0
fi

# --apply path
python3 scripts/sync-genesis-overlay.py --apply
echo

echo "[2/4] Verifying all agents in sync..."
python3 scripts/sync-genesis-overlay.py --check --quiet
echo

echo "[3/4] Staging changes..."
git add instances/default/companies/4b7fd6fc-b920-430e-a3bd-defc09fc4326/
git status --short

echo
echo "[4/4] Committing on overlay/genesis..."
# Default commit message — caller can amend if needed
ts=$(date -u +%Y-%m-%d)
read -r -d '' msg <<EOF
overlay/genesis: regenerate per-agent guardrail from canonical (${ts})

Auto-generated by scripts/sync-and-deploy.sh. Edits the canonical
GENESIS-WEBSITE-GUARDRAILS.md source only; the per-agent AGENTS.md
files are regenerated, not hand-edited.

After this commit, run:
  python3 scripts/sync-genesis-overlay.py --check
and confirm exit 0.
EOF

git -c user.email='benjamin@hermes.local' -c user.name='Benjamin' commit -m "$msg"
git log --oneline -1

echo
echo "Done. Next steps:"
echo "  - Inspect: git show HEAD"
echo "  - Push (optional): git push -u origin overlay/genesis"
echo "  - If upstream moved, rebase: git checkout master && git pull --rebase origin master && git checkout overlay/genesis && git rebase master"
