import { describe, expect, it } from "vitest";
import { resourceManifestAttachmentSchema } from "./resource.js";

describe("Resource output configuration", () => {
  it("accepts run-specific output actions and metadata", () => {
    expect(resourceManifestAttachmentSchema.parse({
      resourceId: "00000000-0000-0000-0000-000000000001",
      mode: "input_output",
      version: "branch:main",
      output: {
        action: "pull_request",
        targetRef: "main",
        branch: "bizbox/campaign-update",
        title: "Update campaign",
        body: "Generated by the workflow.",
      },
    })).toMatchObject({ output: { action: "pull_request", targetRef: "main" } });
  });

  it("rejects local-only commit output", () => {
    expect(() => resourceManifestAttachmentSchema.parse({
      resourceId: "00000000-0000-0000-0000-000000000001",
      mode: "output",
      output: { action: "commit" },
    })).toThrow();
  });
});
