-- One-off operator script: convert activity_log, heartbeat_run_events, and
-- agent_wakeup_requests into monthly range-partitioned tables.
--
-- Run AFTER migration 0106_log_partition_helpers has been applied. Idempotent:
-- tables already partitioned (parent in pg_partitioned_table) are skipped.
--
-- Usage (embedded postgres):
--   psql "$(paperclipai postgres connection-string)" \
--     -v ON_ERROR_STOP=1 -f server/scripts/partition-log-tables.sql
--
-- Usage (external postgres):
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f server/scripts/partition-log-tables.sql
--
-- IMPORTANT
-- ---------
--   * Each table is converted inside a single transaction. While the
--     transaction holds ACCESS EXCLUSIVE on the source table, writes block.
--     For small tables (default embedded-pg installs) this is sub-second.
--     For instances with millions of rows, schedule a maintenance window.
--   * The script drops the FK heartbeat_runs.wakeup_request_id ->
--     agent_wakeup_requests.id because PostgreSQL does not allow FKs to a
--     partitioned table unless the partition key is part of the referenced
--     UNIQUE constraint. The pointer column is preserved as a plain uuid.
--   * Composite PRIMARY KEY becomes (id, created_at) on every partitioned
--     table (PostgreSQL requires the partition key in any UNIQUE constraint).
--     Drizzle queries are unaffected -- id remains globally unique because
--     it is generated by gen_random_uuid() / bigserial.

BEGIN;

CREATE OR REPLACE FUNCTION pg_temp.paperclip_partition_table(
  p_table text,
  p_id_column text
) RETURNS void
LANGUAGE plpgsql AS $fn$
DECLARE
  v_min_created timestamptz;
  v_max_created timestamptz;
  v_month date;
  v_first_month date;
  v_last_month date;
BEGIN
  IF paperclip_is_table_partitioned(p_table) THEN
    RAISE NOTICE '%: already partitioned, skipping', p_table;
    RETURN;
  END IF;

  RAISE NOTICE '%: starting conversion to monthly range partitions', p_table;

  EXECUTE format('ALTER TABLE %I RENAME TO %I', p_table, p_table || '_legacy');

  EXECUTE format(
    'CREATE TABLE %I (LIKE %I INCLUDING DEFAULTS INCLUDING IDENTITY EXCLUDING CONSTRAINTS EXCLUDING INDEXES) PARTITION BY RANGE (created_at)',
    p_table, p_table || '_legacy'
  );

  EXECUTE format(
    'ALTER TABLE %I ADD CONSTRAINT %I PRIMARY KEY (%I, created_at)',
    p_table, p_table || '_pkey', p_id_column
  );

  EXECUTE format('SELECT min(created_at), max(created_at) FROM %I', p_table || '_legacy')
    INTO v_min_created, v_max_created;

  v_first_month := date_trunc('month', COALESCE(v_min_created, now()))::date;
  v_last_month  := date_trunc('month', COALESCE(v_max_created, now()) + interval '2 months')::date;

  FOR v_month IN
    SELECT generate_series(v_first_month, v_last_month, interval '1 month')::date
  LOOP
    PERFORM paperclip_ensure_log_partition(p_table, v_month);
  END LOOP;

  PERFORM paperclip_ensure_log_partitions_window(p_table, 0, 2);

  EXECUTE format('INSERT INTO %I SELECT * FROM %I', p_table, p_table || '_legacy');

  EXECUTE format('DROP TABLE %I CASCADE', p_table || '_legacy');

  RAISE NOTICE '%: conversion complete', p_table;
END;
$fn$;

ALTER TABLE heartbeat_runs
  DROP CONSTRAINT IF EXISTS heartbeat_runs_wakeup_request_id_agent_wakeup_requests_id_fk;

SELECT pg_temp.paperclip_partition_table('activity_log', 'id');
SELECT pg_temp.paperclip_partition_table('agent_wakeup_requests', 'id');
SELECT pg_temp.paperclip_partition_table('heartbeat_run_events', 'id');

CREATE INDEX IF NOT EXISTS activity_log_company_created_idx
  ON activity_log (company_id, created_at);
CREATE INDEX IF NOT EXISTS activity_log_run_id_idx
  ON activity_log (run_id);
CREATE INDEX IF NOT EXISTS activity_log_entity_type_id_idx
  ON activity_log (entity_type, entity_id);

CREATE INDEX IF NOT EXISTS agent_wakeup_requests_company_agent_status_idx
  ON agent_wakeup_requests (company_id, agent_id, status);
CREATE INDEX IF NOT EXISTS agent_wakeup_requests_company_requested_idx
  ON agent_wakeup_requests (company_id, requested_at);
CREATE INDEX IF NOT EXISTS agent_wakeup_requests_agent_requested_idx
  ON agent_wakeup_requests (agent_id, requested_at);

CREATE INDEX IF NOT EXISTS heartbeat_run_events_run_seq_idx
  ON heartbeat_run_events (run_id, seq);
CREATE INDEX IF NOT EXISTS heartbeat_run_events_company_run_idx
  ON heartbeat_run_events (company_id, run_id);
CREATE INDEX IF NOT EXISTS heartbeat_run_events_company_created_idx
  ON heartbeat_run_events (company_id, created_at);

COMMIT;

ANALYZE activity_log;
ANALYZE agent_wakeup_requests;
ANALYZE heartbeat_run_events;
