export const OPENCLAW_GATEWAY_PROTOCOL_VERSION = 4;

export const OPENCLAW_GATEWAY_PROTOCOL_RANGE = {
  minProtocol: OPENCLAW_GATEWAY_PROTOCOL_VERSION,
  maxProtocol: OPENCLAW_GATEWAY_PROTOCOL_VERSION,
} as const;
